### PR TITLE
Shovel: handle `connection.(un)blocked` messages

### PR DESCRIPTION
**Pull request by gomoripeti**
## Proposed Changes

This is a follow-up of https://github.com/rabbitmq/rabbitmq-server/pull/5715 to allow a shovel to be blocked not just by credit-flow but also by an explicit `connection.blocked` message. This is in hope so that less messages would be in flight in buffers (which can be lost if a connection is closed) when the destination cluster has resource alarms. This mostly targets on-publish mode, but works for the other ack-modes as well.

(EDIT: the below part has been moved out of the scope of this PR

> Also now that shovels can be blocked for different reasons this is also reflected on the UI shovel status page.
> 
> Currently there is a known limitation that if the shovel is idle after
> it was unblocked by credit flow, then the status won't get updated until
> the next message. I would appreciate some advice if this needs to be fixed and how.
> 
> Historically why does [`credit_flow:state/0`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit_common/src/credit_flow.erl#L167) have a state-change-interval delay? Is it because of performance optimisation or is it for UX so that even a very short period of `flow` state won't get unnoticed on the mgmt UI?
> 
> As a solution I can imagine
> - starting a timer every time a shovel transitions from flow to running and reporting the status after 1 second (I'm concerned about the performance impact of starting and canceling a lot of timers)
> - don't use `credit_flow:state/0` but store `credit_blocked_at` in the shovel status table, and replicate the logic at lookup time (this sounds more efficient but duplicates code)
> - do nothing, keep the limitation)
 

TODO make sure docs are up-to-date

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by gomoripeti** [comment]
Indeed in a mixed version cluster a new node can return a shovel status (flow or blocked) that an old node cannot format.

There is also a failing test case in the shovel_management plugin suite that I need to fix.

**Comment by michaelklishin** [comment]
@gomoripeti builds fail because `rabbit_amqp091_shovel:reset_pending/1` is unused and our build system treats warnings in the RabbitMQ's own code as errors.

Once that is fixed, there are Dialyzer errors.

**Review by michaelklishin — CHANGES_REQUESTED** [review]
Builds fail because rabbit_amqp091_shovel:reset_pending/1 is unused and our build system treats warnings in the RabbitMQ's own code as errors.

Once that is fixed, there are Dialyzer errors.

**Comment by michaelklishin** [comment]
```
compile: warnings being treated as errors
rabbit_amqp091_shovel.erl:406:1: function reset_pending/1 is unused
```

```
rabbit_shovel_worker.erl:59:10: Record construction
          #state{type :: 'dynamic' | 'static',
                 last_reported_status :: 'undefined'} violates the declared type of field last_reported_status ::
          'blocked' | 'flow' | 'running'
```

**Comment by gomoripeti** [comment]
I will move the "report flow/blocked status" part to a separate PR as there are aspects of it I did not think of
- should work in mixed version clusters
- should address the "state-change-interval delay" of credit flow
- should not send `shovel_worker_status` rabbit events for every flow/blocked/running status change

**Comment by gomoripeti** [comment]
the `dynamic_SUITE` fails across multiple jobs, so it must be a legitimate failure, but it does not fail for me if I just run this suite locally with `make -C deps/rabbitmq_shovel ct-dynamic`. Is there any way to see some more details about the failures from the CI?

**Comment by michaelklishin** [comment]
CI uses Bazel.

```
bazel test --config=local //deps/rabbitmq_shovel:dynamic_SUITE
```

```
bazel test --config=local //deps/rabbitmq_shovel:all
```

My `user.bazelrc` in the repo looks like this:

``` starlark
build:local --@rules_erlang//:erlang_home=/path/to/otp/25.1
build:local --@rules_erlang//:erlang_version=25.1
build:local --//:elixir_home=/path/to/.kiex/elixirs/elixir-1.13.4/lib/elixir/

# rabbitmqctl wait shells out to 'ps', which is broken in the bazel macOS
# sandbox (https://github.com/bazelbuild/bazel/issues/7448)
# adding "--spawn_strategy=local" to the invocation is a workaround
build --spawn_strategy=local

# --experimental_strict_action_env breaks memory size detection on macOS,
# so turn it off for local runs
build --noexperimental_strict_action_env
build:buildbuddy --experimental_strict_action_env

# don't re-run flakes automatically on the local machine
build --flaky_test_attempts=1

build:buildbuddy --remote_header=x-buildbuddy-api-key=YOUR_API_KEY

# cross compile for linux (if on macOS) with rbe
# build:rbe --host_cpu=k8
# build:rbe --cpu=k8

build --@io_bazel_rules_docker//transitions:enable=false
```

**Comment by michaelklishin** [comment]
You can download build artifacts from the [Build Buddy build results page](https://app.buildbuddy.io/invocation/a546ccc7-e718-4139-a820-89f0af5b92d5#artifacts).

It takes a while to figure out what goes where at first but here are the [target run results](https://app.buildbuddy.io/invocation/a546ccc7-e718-4139-a820-89f0af5b92d5?target=%2F%2Fdeps%2Frabbitmq_shovel%3Adynamic_SUITE): for `dynamic_SUITE`:

```
RabbitMQ node(s) in directory /buildbuddy/remotebuilds/4a322cf0-42f5-4381-b303-da3689b2ce4b/bazel-out/k8-fastbuild/testlogs/deps/rabbitmq_shovel/dynamic_SUITE/test.outputs/ct_run.ct-rabbitmq_shovel-dynamic_SUITE@localhost.2022-10-23_11.26.43/deps.rabbitmq_shovel.dynamic_SUITE.logs/run.2022-10-23_11.26.43/log_private
Waiting for pid file '/buildbuddy/remotebuilds/4a322cf0-42f5-4381-b303-da3689b2ce4b/bazel-out/k8-fastbuild/testlogs/deps/rabbitmq_shovel/dynamic_SUITE/test.outputs/ct_run.ct-rabbitmq_shovel-dynamic_SUITE@localhost.2022-10-23_11.26.43/deps.rabbitmq_shovel.dynamic_SUITE.logs/run.2022-10-23_11.26.43/log_private//rmq-ct-dynamic_SUITE-1-21000@localhost/rmq-ct-dynamic_SUITE-1-21000@localhost.pid' to appear
pid is 289
Waiting for erlang distribution on node 'rmq-ct-dynamic_SUITE-1-21000@localhost' while OS process '289' is running
Waiting for applications 'rabbit_and_plugins' to start on node 'rmq-ct-dynamic_SUITE-1-21000@localhost'
Applications 'rabbit_and_plugins' are running on node 'rmq-ct-dynamic_SUITE-1-21000@localhost'
Exit code: 0 (pid <0.113.0>)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
rabbit_top_util:obtain_name failed
Reason: {undef,[{rabbit_top_util,...},{...}|...]}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Testing deps.rabbitmq_shovel.dynamic_SUITE: *** FAILED test case 14 of 19 ***
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
gen_server:call failed on line 382
Reason: {{shutdown,{server_initiated_close,...}},{gen_server,call,...}}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Testing deps.rabbitmq_shovel.dynamic_SUITE: *** FAILED test case 15 of 19 ***
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
gen_server:call failed on line 382
Reason: {{shutdown,{server_initiated_close,...}},{gen_server,call,...}}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Testing deps.rabbitmq_shovel.dynamic_SUITE: *** FAILED test case 16 of 19 ***
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
gen_server:call failed on line 382
Reason: {{shutdown,{server_initiated_close,...}},{gen_server,call,...}}
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Testing deps.rabbitmq_shovel.dynamic_SUITE: *** FAILED test case 17 of 19 ***
```

and then there are CT logs to download.

**Comment by michaelklishin** [comment]
Finally, if you want to switch to Bazel from erlang.mk, you have to either `gmake distclean` then wipe `deps` and then `git reset --hard` or use a separate clone.

Bazel does not assume that external dependencies would be stored under `deps/`.

**Comment by michaelklishin** [comment]
The `undef` about `rabbit_top_util` is due to a missing runtime dependency in `deps/rabbitmq_shovel/BUILD.bazel`:

``` starlark
RUNTIME_DEPS = [
    "//deps/amqp10_client:erlang_app",
    "//deps/rabbitmq_top:erlang_app",
]
```

fixed it for me.

**Comment by gomoripeti** [comment]
thank you very much for all the pointers and details, they are very helpful

the use of `rabbit_top_util:obtain_name` is really not necessary, and could be considered a leftover from my debugging the test case which I should remove.

**Comment by michaelklishin** [comment]
Hm, the idea to add `rabbitmq_top` to runtime dependencies in `deps/rabbitmq_shovel/BUILD.bazel` is obvious a terrible one. We should add a test dependency equivalent.

**Comment by gomoripeti** [comment]
I removed the `rabbit_top_util` call from the test suite and now all checks pass 🎉

**Comment by michaelklishin** [comment]
The change delay must have to do with the management UI minimum refresh rate but also the fact that credit flow can go in and out of effect dozens of times a second.

I don't think we should discuss what to do with it in comments in a PR that intentionally ignores this part of Shovel behavior :)

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
