### PR TITLE
Move rabbit and plugins from `deps` to `apps`

### PR DESCRIPTION
**Pull request by pjk25**
## Proposed Changes

Moves the erlang applications from `deps`, which Erlang.mk normally uses for fetched deps, to `apps`, where "local" apps/deps are kept by convention. This make the layout of the project a little less unique. It should also restore proper behavior of `make distclean`.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

There are Concourse pipelines that likely refer to paths in the `deps` directory, so merging them is likely to cause breakage. Therefore this is best applied when the pipelines are in a "quiet" period.

### CODE REVIEW

**Comment by pjk25** [comment]
@lhoguin what do you think about this for post 3.9 GA?

**Comment by lhoguin** [comment]
Sounds good.

**Comment by pjk25** [comment]
@Mergifyio rebase

**Comment by pjk25** [comment]
@Mergifyio rebase

**Comment by pjk25** [comment]
I think we are unlikely to make this change given the limited benefit, but high amount of disruption to open PRs. I will close it.

**Pull request closed without merging**
