### PR TITLE
Pass all members to synchronous Ra operations

### PR DESCRIPTION
**Pull request by kjnilsson**
As this will make these more work reliably when leadership is in flux.

Also ensure that servers started and added after the initial declare
uses the same configuration.

requires https://github.com/rabbitmq/ra/pull/100.

### CODE REVIEW

**Comment by gerhard** [comment]
Looks good, ship it. How to we stress-test this in LREs? Would this help? https://github.com/rabbitmq/rabbitmq-server-boshrelease/tree/master/jobs/periodic_shutdown

**Comment by kjnilsson** [comment]
I think it's tricky to test this specific thing but lots of queue declare during leader elections would be the way I'd approach it.

**Comment by gerhard** [comment]
If nodes get periodically shut-down and consumers get forcefully disconnect, when consumers reconnect they should first try to declare queues before consuming from them. Would that work?

**Comment by michaelklishin** [comment]
@kjnilsson @dcorbacho FYI, this has a legitimate conflict with https://github.com/rabbitmq/rabbitmq-server/pull/2053.

**Pull request merged**
