### PR TITLE
Fix of unquoting of env vars

### PR DESCRIPTION
**Pull request by strollo**
## Proposed Changes

Supports the unquoting of RABBITMQ_CONFIG_FILE and RABBITMQ_ADVANCED_CONFIG_FILE keeping compatibility with windows paths with spaces.

At the moment RABBITMQ_CONFIG_FILE and RABBITMQ_ADVANCED_CONFIG_FILE are correctly converted just if declared with quotes:
e.g.
  "C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12"

With this patch the quoting is no more required so both forms:
"C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12"
and
C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12

will be ok!

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

Just tested locally by easily calling the rabbitmq-server.bat/rabbitmq-service.bat that are impacted by this env vars.
Used both quoted (previously supported) and the unquoted (now supported) versions.

If it is not enough to pass the revision feel free to ask to add tests / docs.
Cheers,
  Daniele

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@strollo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-server&pullRequestId=1979)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-server&pullRequestId=1979) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@strollo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-server&pullRequestId=1979)!

**Comment by lukebakken** [comment]
Thanks for the contribution. Could you please attach example `rabbitmq-env-conf.bat` files that demonstrate exactly what this fixes? I _think_ I understand it but I don't want to guess.

**Comment by strollo** [comment]
Thank you for your attention.
Well at the moment the better way I found to demostrate the different
results you can obtain by using the two different parameter passing style
can be summarized in the attached file (renamed as .txt to be attached
bypassing email rules).

The trick at the base is: apply (when necessary) the native unquoting at
the parameter and than pass it in quoted form to be sure to do not loose
the part after the space.

The unquote function is the one provided in your distrib just it's called
in a different fashion.

If any other example is needed don't hesitate to ask.


How I simply tested it....

At the beginning essentially I had an environment variable RABBITMQ_CONFIG_FILE
in the form...

set RABBITMQ_CONFIG_FILE=C:\Program Files (x86)\Other Path With
Spaces\rabbitmq-server-3.7.12

after that patched rabbitmq-server.bat at line 65 this way

>
> CALL :convert_forward_slashes !RABBITMQ_CONFIG_FILE! RABBITMQ_CONFIG_FILE
> CALL :get_noex !RABBITMQ_CONFIG_FILE! RABBITMQ_CONFIG_FILE_NOEX
> echo "The value of RABBITMQ_CONFIG_FILE_NOEX is
> [%RABBITMQ_CONFIG_FILE_NOEX%]"
> exit /B 0
> # REM so that it prints converted value and exits


A different result will return the call of script if:

set RABBITMQ_CONFIG_FILE="C:\Program Files (x86)\Other Path With
Spaces\rabbitmq-server-3.7.12"

Cheers,
  Daniele

@echo off
setlocal

setlocal enabledelayedexpansion
setlocal enableextensions

REM --- ORIGINAL ---
set PATHO1="C:/Program Files (x86)/Other Path With Spaces/rabbitmq-server-3.7.12"
set PATHO2=C:/Program Files (x86)/Other Path With Spaces/rabbitmq-server-3.7.12
set PATHO3="C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12"
set PATHO4=C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12
set PATHO5=C:\PROGRA~2\OTHERP~1\rabbitmq-server-3.7.12

echo "Orig part"
CALL :unquote PATH1 %PATHO1%
CALL :unquote PATH2 %PATHO2%
CALL :unquote PATH3 %PATHO3%
CALL :unquote PATH4 %PATHO4%
CALL :unquote PATH5 %PATHO5%

echo "PATH1: [!PATH1!]"	
echo "PATH2: [!PATH2!]"	
echo "PATH3: [!PATH3!]"	
echo "PATH4: [!PATH4!]"	
echo "PATH5: [!PATH5!]"	

REM --- PROPOSED PATCH ---
set PATHN1="C:/Program Files (x86)/Other Path With Spaces/rabbitmq-server-3.7.12"
set PATHN2=C:/Program Files (x86)/Other Path With Spaces/rabbitmq-server-3.7.12
set PATHN3="C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12"
set PATHN4=C:\Program Files (x86)\Other Path With Spaces\rabbitmq-server-3.7.12
set PATHN5=C:\PROGRA~2\OTHERP~1\rabbitmq-server-3.7.12

echo "Patched part"
CALL :unquote PATH1 "%PATHN1:"=%"
CALL :unquote PATH2 "%PATHN2:"=%"
CALL :unquote PATH3 "%PATHN3:"=%"
CALL :unquote PATH4 "%PATHN4:"=%"
CALL :unquote PATH5 "%PATHN5:"=%"

echo "PATH1: [!PATH1!]"	
echo "PATH2: [!PATH2!]"	
echo "PATH3: [!PATH3!]"	
echo "PATH4: [!PATH4!]"	
echo "PATH5: [!PATH5!]"	



REM --- END OF SCRIPT ---
EXIT /B 0


REM --- ORIG RABBITMQ SCRIPTS ---
:unquote
set %1=%~2
EXIT /B 0

endlocal
endlocal
endlocal

**Comment by lukebakken** [comment]
For what it's worth, if I set either of these environment variables the `rabbitmq.conf` file is not read:

```
set RABBITMQ_CONFIG_FILE=C:\ProgramData\TEST 1979\rabbitmq.conf
set RABBITMQ_CONFIG_FILE="C:\ProgramData\TEST 1979\rabbitmq.conf"
```

So, while this PR may address one issue there is still an issue with spaces in this configuration value. I am testing with Windows 8.1.

**Comment by strollo** [comment]
Attached a PR 
- Related to Bug rabbitmq#1756
- Include PR rabbitmq#1979

Basically Paths with long names (e.g. D:\Program Files (x86)...) are properly handled in the env vars that is crucial when installing on drives with 8dot3 flag disabled so their names cannot be shorted.

**Comment by lukebakken** [comment]
When you set an environment variable to a value that includes space characters, it is not necessary to double-quote it. If a user *does* use double-quotes, they are included as part of the variables's value, and are an error. I am still undecided about the changes proposed here.

As part of #2068 I am reviewing the `.bat` files to ensure that variables are double-quoted when _used_ as an argument to a command or sub-function. I am also going to create a series of tests to validate that spaces and non-ASCII characters work.

**Comment by lukebakken** [comment]
As unlikely as it may be, the proposed patch will remove valid double-quotes if they make up part of the path:

```
@echo off
setlocal

setlocal enabledelayedexpansion
setlocal enableextensions

REM --- PROPOSED PATCH ---
set PATHN1=C:\Program Files (x86)\Other Path With "Quotes"\rabbitmq-server-3.7.12

echo "Patched part"
CALL :unquote PATH1 "%PATHN1:"=%"

echo PATH1: [!PATH1!]

REM --- END OF SCRIPT ---
EXIT /B 0

REM --- ORIG RABBITMQ SCRIPTS ---
:unquote
set %1=%~2
EXIT /B 0

endlocal
endlocal
endlocal
```

At this point I don't believe this is something we should solve. If a user incorrectly double-quotes a variable value perhaps we can detect that and issue a warning, but I don't think we should try to fix it.

I have incorporated fixes for paths with spaces into #2068, however.

@michaelklishin thoughts?

**Comment by michaelklishin** [comment]
I agree that it's an edge case we can document as unsupported.

**Comment by lukebakken** [comment]
I first thought [this method](https://github.com/rabbitmq/rabbitmq-server/pull/2068/commits/cef6052d5b749507c36bcf969cea88c273ee48e2) would be the correct way to remove double-quotes, but it doesn't work with paths like this:

```
set RABBITMQ_BASE="C:\ProgramData\찦차를 타고 온 펲시맨과 쑛다리 똠방각하 (Korean)\RabbitMQ"
```

However, [this code](https://github.com/rabbitmq/rabbitmq-server/pull/2068/commits/33283cda1851e706094cda35da85dedc5159df44) works in all cases. Thanks @strollo for pointing out some options for dealing with extra double-quotes.

Fixed by #2068

**Pull request closed without merging**
