### PR TITLE
Add `exclusive` item to `rabbitmqctl list_queues`

### PR DESCRIPTION
**Pull request by binarin**
In addition to owner_pid, which makes little sense to beginners.

Just as described in #371

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you! This looks good. We have a fairly non-trivial PR landing in the same area in the near future (see #303) but there's less overlap than I expected.

Can you please rebase this against `stable` and re-submit? This can go into `3.5.7`.

**Comment by videlalvaro** [comment]
@michaelklishin why would this go into 3.5.7 considering that it adds new things to CTL? Why not wait for 3.6.0 which anyway is happening soon?

**Comment by michaelklishin** [comment]
@videlalvaro it's not a breaking change and it is very small, why not ship it earlier?

**Comment by videlalvaro** [comment]
Because there are version numbers for a reason? Other wise what's the meaning of them if we don't respect them? We could use just one increasing integer…

Also, what's the rush?

**Comment by michaelklishin** [comment]
@videlalvaro we've been shipping small features in earlier `3.5.x` releases. Please keep your snark to yourself.

**Comment by michaelklishin** [comment]
@dumbbell do you have an opinion on this?

**Comment by michaelklishin** [comment]
@binarin no need to rebase anything: we can cherry-pick to stable if we decide to do so. Thanks again for your contribution.

**Comment by dumbbell** [comment]
@michaelklishin, @videlalvaro: I'm fine with small low-impact new features in a stable branch. We already did that in the past. We can discuss what we mean behind our version numbers outside of this issue though, and in particular if we want to follow "semver" rules or not.

In this specific case, does an old `rabbitmqctl` still work with a new RabbitMQ? And the opposite?

**Comment by michaelklishin** [comment]
@dumbbell we never tried to support cross-version `rabbitmq-server` and `rabbitmqctl`. But this change is hardly breaking: it only adds a new stats info and output column.

**Comment by michaelklishin** [comment]
@binarin thank you. Works like a charm.

**Comment by michaelklishin** [comment]
Cherry-picked to `stable`.

**Pull request merged**
