### PR TITLE
Ra 2.13.1

### PR DESCRIPTION
**Pull request by kjnilsson**
This release contains improvements to the checkpointing feature
needed for quorum queues v4 and the following fixes:

* Add read to file:open/2 options in ra_lib:sync_file/1
* Emit the new local_query tuple only if query options are set
* bug fixes for checkpoints

### CODE REVIEW

**Comment by dumbbell** [comment]
Shouldn’t the commit message and this pull request’s description point to Ra’s pull request instead of RabbitMQ’s ones?

**Comment by michaelklishin** [comment]
@dumbbell I have updated the links

**Comment by kjnilsson** [comment]
@mkuratczyk might have found a bug so converting this back to draft

**Comment by kjnilsson** [comment]
> @mkuratczyk might have found a bug so converting this back to draft

bug addressed - ready for review again.

**Review by dumbbell — APPROVED** [review]

**Pull request merged**
