### PR TITLE
Reduce mnesia contention when nodes restart master

### PR DESCRIPTION
**Pull request by michaelklishin**
This is #1526 based on master, originally submitted as #1527 and reverted in #1567 after a discovered Erlang 19.3 incompatibility).

### CODE REVIEW

**Comment by gerhard** [comment]
Ta for the merge! I suppose that we are expecting for the pipeline to pass for `master` before we merge this into `v3.7.x`. I can see that [build-test-package-debian#128](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x/jobs/build-test-package-debian/builds/128) failed, meaning that no alpha artefact was produced from this merge.

Anything we can do to help?

cc @dumbbell

**Comment by dumbbell** [comment]
Sorry I missed the ping...

I believe all failures in the `v3.8.x` pipeline are fixed by now. However, the `v3.7.x` pipeline is stuck right in the middle for no apparent reason: new resources don't reach the upgrades testing stage.

**Comment by gerhard** [comment]
I see what you mean. What are your plans on getting it un-stuck? Anything I can do to help?

**Comment by dumbbell** [comment]
I believe I see light at the end of the tunnel :-) There was a chain of small issues with Concourse, our pipeline, the Erlang Solutions Debian repository and so on. The last thing on the radat is a regression with Concourse 3.11.0: the Git resource doesn't fetch tags anymore, we have to do it ourselves. A fix for this is being tested.

**Comment by gerhard** [comment]
That is excellent news! I'm waiting for a build to go through the pipeline so that I can share the artefacts. Let me know if there is anything that I can help with!

**Comment by dumbbell** [comment]
And that was without anticipating the next problem: no space left on workers!

Anyway, a 3.7.x snapshot was published yesterday:
https://dl.bintray.com/rabbitmq/all-dev/rabbitmq-server/3.7.5-alpha.23/

Hopefully, it will allow you to make progress.

**Comment by gerhard** [comment]
I could definitely watch this movie 🍿 

`3.7.5-alpha.23` is missing some commits that made it into `master` but not `v3.7.x`. Let's chat in person, this is turning into a high latency game of ping-pong comments.

**Pull request merged**
