### PR TITLE
Remove use of accept_ack

### LINKED ISSUE #1835: Ranch no longer calls accept_ack for a transport
See rabbitmq/rabbitmq-management#652

### PR DESCRIPTION
**Pull request by lukebakken**
Ranch no longer calls accept_ack for a transport, which means a couple important operations are missed for new sockets.

Fixes #1835 and rabbitmq/rabbitmq-management#652

@essen - `accept_ack` is marked as deprecated ... should it still be called by Ranch somehow?

### CODE REVIEW

**Comment by essen** [comment]
Oh geez. Yes it was indeed missing from the non-proxy protocol branch. Sorry about that.

About `accept_ack`, it's now `handshake` that performs  the equivalent operation in Ranch. The only difference is a new socket is returned; it mirrors the interface changes in the ssl application. In Ranch 2.0 the only way to obtain the socket will be through `handshake`.

**Comment by essen** [comment]
It does. Current Ranch has both the old `accept_ack` and the new `handshake`, and RabbitMQ switched to the new function. You can call either of them (not both!) until Ranch 2.0.

**Comment by lukebakken** [comment]
I probably don't understand how `accept_ack` is supposed to work, but [this ranch 1.5.0 code](https://github.com/ninenines/ranch/blob/1.5.0/src/ranch.erl#L128-L132) will call `Transport:accept_ack`, whereas versions 1.6 and later never call `Transport:accept_ack`, instead calling `handshake/1`. It was the call to `Transport:accept_ack` that RabbitMQ depended on to increment the socket stat as well as tune the socket buffers. Were we using `accept_ack` incorrectly?

**Comment by essen** [comment]
Once Ranch has accepted a socket it needs to start a connection process and gives controlling_process to this new process. The `accept_ack` waits for that to happen. For ssl it also performs the TLS handshake.

The principle is the same with `handshake` except it was made to work like ssl's handshake function, which it calls when the transport is ssl. There was a slow move toward handshake over the past few releases which culminate in `accept_ack` now being just a wrapper around `handshake`, but the functionality hasn't changed; only the interface is being phased out: https://github.com/ninenines/ranch/blob/1.7.0/src/ranch.erl#L231

**Comment by lukebakken** [comment]
Backported to `v3.7.x`

**Pull request merged**
