### PR TITLE
Fix typos in deps/rabbit/src/

### PR DESCRIPTION
**Pull request by szepeviktor**
## Proposed Changes

Fix misspellings with `typos`.

There are 283 more.
Is anyone willing to continue my work?

### CODE REVIEW

**Comment by szepeviktor** [comment]
`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "deps/rabbitmq_management/selenium/test/",
    "deps/rabbit/test/definition_import_SUITE_data/",
    "deps/rabbitmq_management/priv/www/js/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    '"hello thar"',
    '"poing"',
    '"\[O\]nce',
    "3, tre\\)",
]

[default.extend-words]
"alog" = "alog"

[default.extend-identifiers]
"AFE" = "AFE"
"DELETEing" = "DELETEing"
"MsgIds2ndHalf" = "MsgIds2ndHalf"
"Ser" = "Ser"

# Typos
"Github" = "GitHub"
```

**Comment by michaelklishin** [comment]
Sorry but this renames functions, atoms used in returned/thrown error values, and so on. We won't accept typo fixes to anything but the comments and log messages. Which may be difficult to identify with whatever tool you have used.

**Comment by szepeviktor** [comment]
Thank you for your response.
I've never received _We won't accept typo fixes_ for a PR.

**Comment by lukebakken** [comment]
> I've never received We won't accept typo fixes for a PR

Well, now you have 😄

The risk of introducing a bug is too great for us to accept PRs like this, as @michaelklishin  said.

**Comment by michaelklishin** [comment]
@szepeviktor please don't take it personally. We have seen similar PRs that introduced very subtle breaking changes that were managed to detect at the last possible moment. Typo fixes in bulk are simply not worth this risk for a large enough project such as RabbitMQ.

**Comment by szepeviktor** [comment]
Thank you for your lines.

**Pull request closed without merging**
