### PR TITLE
Test 3rd side pacemaker HA github workflow

### PR DESCRIPTION
**Pull request by bogdando**
## Proposed Changes

Add a CI job to smoke test (TBD: verify HA functions with Jepsen) of
scripts/rabbitmq-server-ha.ocf (OCF RA for pacemaker).

Uses external prebuilt container images and vagrantfile.
Executes a simple smoke test
against changes submitted/proposed for the in-tree OCF RA.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by bogdando** [comment]
not sure what is needed to have the jobs started, some approve for testing perhaps? I've tested that in my fork, like https://github.com/bogdando/rabbitmq-server/runs/3143235316

**Comment by bogdando** [comment]
@pjk25 @michaelklishin PTAL

**Comment by pjk25** [comment]
@bogdando The checks have run given what I'm seeing here. The smoke test passed, but the jepsen test failed.

**Comment by bogdando** [comment]
@michaelklishin @pjk25 The fixed Jepsen case seems worked as well https://github.com/rabbitmq/rabbitmq-server/runs/3159462965?check_suite_focus=true, I'll re-add it back via a follow up PR. This is good to go as is.

**Comment by michaelklishin** [comment]
Thank you for putting in the time. I don't know if we would be interested in having these Pacemarker/OCF resource tests in this repo.
We do not maintain the OCF resource and do not see Pacemaker as a major component of the distributed RabbitMQ landscape today or in the future.

I'd suggest moving this to a separate repository or CI service under control of those who actually maintain the OCF resource

**Comment by bogdando** [comment]
@michaelklishin ok, how about the rabbitmq-server-release repo then? These same travis CI test cases used to be there before.

**Comment by michaelklishin** [comment]
@bogdando that repository was superseded by https://github.com/rabbitmq/rabbitmq-packaging. My point is that we should not add any tests to our repos if we do not maintain or recommend the feature they are testing.

**Comment by bogdando** [comment]
@michaelklishin I see, thank you. I thought has been considered as maintained. There is documentation https://www.rabbitmq.com/pacemaker.html#auto-pacemaker and contributions have been going in through years since that OCF RA had been upstreamed. We plan to eventually switch to that script in our TripleO project for OpenStack. What would you recommend then?

**Comment by michaelklishin** [comment]
It is maintained but not by the core team (we simply merge PRs). The doc guide has been retained for similar reasons: a few OpenStack vendors/users still need it. But adding OCF testing to Actions would send a message we wouldn't sign up for: "this stuff is important enough to be tested by the RabbitMQ core team".

**Comment by michaelklishin** [comment]
We welcome ongoing OpenStack community PRs for the OCF itself. However, since anything related to Pacemaker is not really maintained by the core team, we should not tie our release automation to any Pacemarker-related tests. This is
something that should be tested outside of the RabbitMQ repositories.

**Pull request closed without merging**
