### PR TITLE
Shovel crashes with delete-after=0, causes RabbitMQ to not boot after

### PR DESCRIPTION
**Pull request by luos**
Hi,

We ran into an issue when a shovel is created with delete-after=0. It is accepted by RabbitMQ as a valid shovel, however it fails to start and it also does not clean up.

Example command:
```
rabbitmqctl set_parameter shovel my-shovel '{"dest-uri": "amqp://guest:guest@localhost", "src-uri": "amqp://guest:guest@localhost", "ack-mode": "on-confirm", "delete-after": 0, "dest-queue": "target", "src-queue": "source", "reconnect-delay": 30 }'
```

It crashes with the following:

```
{error,
         {{exception,
           {case_clause,
            {error,
             {{{case_clause,0},
               [{rabbit_shovel_dyn_worker_sup,init,1,
                 [{file,"rabbit_shovel_dyn_worker_sup.erl"},{line,45}]},
                {supervisor2,init,1,[{file,"supervisor2.erl"},{line,348}]},
                {gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},
                {gen_server,init_it,6,[{file,"gen_server.erl"},{line,385}]},
                {proc_lib,init_p_do_apply,3,
                 [{file,"proc_lib.erl"},{line,226}]}]},
              {child,undefined,
               {<<"/">>,<<"test">>},
               {rabbit_shovel_dyn_worker_sup,start_link,
```

I think if the shovel addition is scripted, it is quite possible to have this situation. Therefore I fixed this in a way that a shovel with 0 is accepted, then cleaned up, to make sure script writers don't have to worry about this case. 

If RabbitMQ is restarted with this shovel it will not boot up. The shovel plugin needs to be disabled and the parameter cleared manually. 

Alternatively, the validation could be changed to not support this case. 

Let me know what you think. 

## Proposed Changes

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by pjk25** [comment]
It appears that the tests are currently passing, however since this is a PR, build credentials are not injected and causing the checks to fail. I have made some slight changes to the workflows on master that I hope will alleviate that particular issue going forward.

**Comment by michaelklishin** [comment]
I can't think of a reason to use `0` for the auto-delete timeout. We can both accept this change and a follow-up one that would make such definitions invalid for `3.10`.

**Comment by luos** [comment]
Hi,

It is not a timeout but number of messages in the queue. 
In any case, currently, RabbitMQ accepts it but then will not boot, so effectively it is not supported now either. :-)

**Comment by michaelklishin** [comment]
@luos OK, let's merge this for 3.9 and 3.8 and please submit a PR that makes this combination of parameters invalid for `3.10`, just in case.

**Comment by michaelklishin** [comment]
Will backport all the way to `3.8.x` and assign appropriate milestones to the backport PRs.

**Pull request merged**
