### PR TITLE
Ensure monitor is started when dequeuing

### LINKED ISSUE #4976: When queue type rapidly "changes" due to redeclaration, live publishers can get an internal error response
While working on adding quorum queue support to the NServiceBus RabbitMQ transport, we've come across a strange problem that causes an `INTERNAL_ERROR` to be thrown.

The scenario seems to be the following:
1. Have a classic queue and publish a message to it
2. Use a different channel to `BasicGet` the message
3. Delete the queue and recreate it as a quorum queue
4. Try to publish a message to the queue using the same channel that the `BasicGet` was done from

Here's a repro that demonstrates the problem:
```csharp
using RabbitMQ.Client;

var factory = new ConnectionFactory();

var arguments = new Dictionary<string, object> { { "x-queue-type", "quorum" } };
using var connection = factory.CreateConnection();

using var channel = connection.CreateModel();
channel.ConfirmSelect();

//replace all secondChannel usage with channel and the code will work properly
using var secondChannel = connection.CreateModel();
secondChannel.ConfirmSelect();

channel.QueueDeclare("main", true, false, false); //create classic queue
channel.BasicPublish(string.Empty, "main", channel.CreateBasicProperties(), ReadOnlyMemory<byte>.Empty);
channel.WaitForConfirmsOrDie();

var message = secondChannel.BasicGet("main", false);
secondChannel.BasicAck(message.DeliveryTag, false);

channel.QueueDelete("main");
channel.QueueDeclare("main", true, false, false, arguments); //create quorum queue

secondChannel.BasicPublish(string.Empty, "main", secondChannel.CreateBasicProperties(), ReadOnlyMemory<byte>.Empty);
secondChannel.WaitForConfirmsOrDie(); //throws AlreadyClosedException here

channel.QueueDelete("main");
```

This code throws the following exception:
```
RabbitMQ.Client.Exceptions.AlreadyClosedException
  HResult=0x80131500
  Message=Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=541, text='INTERNAL_ERROR', classId=0, methodId=0
  Source=RabbitMQ.Client
  StackTrace:
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirms(TimeSpan timeout, Boolean& timedOut)
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie()
   at RabbitMQ.Client.Impl.AutorecoveringModel.WaitForConfirmsOrDie()
   at Program.<Main>$(String[] args) in C:\Code\RabbitChannelBugRepro\Program.cs:line 28
```

The repro code is located at https://github.com/andreasohlund/RabbitChannelBugRepro if you want to try it out for yourself.

The repository also includes packet captures of the repro code running, both as-is ([broken.pcapng](https://github.com/andreasohlund/RabbitChannelBugRepro/raw/main/captures/broken.pcapng)) and with only a single channel used ([works.pcapng](https://github.com/andreasohlund/RabbitChannelBugRepro/raw/main/captures/works.pcapng)). There is a also a [server log file](https://github.com/andreasohlund/RabbitChannelBugRepro/raw/main/captures/rabbit%40RabbitMQ.log) of when the code is run, showing the error that is logged.

Looking at the packet captures, nothing stood out to me as obviously different/wrong, so I suppose this could be a broker problem and not a client problem, but I'm not sure, so I opened the issue here first.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #4976

Thanks @kjnilsson for knowing exactly how to fix this 🎉

### CODE REVIEW

**Comment by lukebakken** [comment]
To reproduce the issue:

```
git clone https://github.com/lukebakken/rabbitmq-server-4976.git
cd rabbitmq-server-4976

# maybe edit hostname in Program.cs

dotnet run
```

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
I could reproduce the issue using `github.com/lukebakken/rabbitmq-server-4976` with 3.11.13 but not this branch.

Note that the change only affects consumers that poll (with `basic.get`).

**Comment by michaelklishin** [comment]
Unlike with `3.12.x`, `3.11.x` does not provide access to queue name in `rabbit_classic_queue:dequeue/3`, so the fix will be 3.12-specific, at least as it is.

**Comment by lukebakken** [comment]
I'll look into what's involved in a `3.11.x` backport.

**Comment by lukebakken** [comment]
@ansd @kjnilsson @michaelklishin to backport #7943, I would have to include commit https://github.com/rabbitmq/rabbitmq-server/commit/8a2a82e19bc07db9951c41f9fe141c9848dcf010 as well. What do you all think?

**Comment by michaelklishin** [comment]
@lukebakken I'm afraid we cannot backport feature flag-related changes like that. But 3.12 is shipping in the next couple of weeks, and this issue does not seem to affect a lot of people.

**Pull request merged**
