### PR TITLE
STOMP: introduce a max frame size limit

### PR DESCRIPTION
**Pull request by ikvmw**
## Proposed Changes

Add frame size limit.

The default is 4 MiB.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

I would like to have it inside parser, it's way more intrusive in parser. It's a work in progress, but this size limit needed urgently so here it is. I will migrate it to parser via bigger PR.

### CODE REVIEW

**Comment by ikvmw** [comment]
@michaelklishin @mkuratczyk I'm open to changing the default limit. Also current implementation is coarse with tolerance up to buffer size (well it read from network already anyway). If end of the frame is inside of newly read buffer and it exceeds the limit parser is allowed to continue and return frame.     in the next round I will move this check inside parser itself.

**Comment by michaelklishin** [comment]
Let's start with a 1 MiB limit and ship this in 3.13.0.

**Comment by ikvmw** [comment]
why no backport to 3.12?

**Comment by michaelklishin** [comment]
Because previously there was no limit and now there is, and any system where STOMP frame size exceeds it will run into rejected publishes.

**Comment by ikvmw** [comment]
I see it more like a critical bug fix. But I'll gladly accept your POV.

**Comment by michaelklishin** [comment]
Maybe a higher limit such as 8 MiB would be acceptable. I'm OK with using that and backporting. Let me bump the limit one more time.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
The OCI build failures seem unrelated.

**Pull request merged**
