### PR TITLE
Delay generating a guid for basic_messages until it is needed

### PR DESCRIPTION
**Pull request by kjnilsson**
`rabbit_guid:gen()` has a noticeable cost and only classic queues use/require it.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lhoguin it a merge/rebase artifact.

**Comment by kjnilsson** [comment]
Honestly not sure where that commit came from
I'll see if I can fix

**Comment by kjnilsson** [comment]
OK I think it's ok now.

**Comment by michaelklishin** [comment]
@mergifyio backport v3.10.x v3.9.x

**Pull request merged**
