### PR TITLE
Remove extra dollar sign

### LINKED ISSUE #7161: LDAP default configuration for user_dn_pattern is not valid
Reported here: https://groups.google.com/g/rabbitmq-users/c/rPHEv6o9uEk

https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_auth_backend_ldap/BUILD.bazel#L17

### PR DESCRIPTION
**Pull request by lukebakken**
Not needed with bazel

Fixes #7161

### CODE REVIEW

**Comment by lukebakken** [comment]
@pjk25 - I checked the rest of the `.bazel` files this way:

```
rg --fixed-strings '$$' --glob '*.bazel'
```

I'm reasonably sure the rest of the `$$` characters are for shell scripts that get written on-the-fly.

**Comment by pjk25** [comment]
> @pjk25 - I checked the rest of the `.bazel` files this way:
> 
> ```
> rg --fixed-strings '$$' --glob '*.bazel'
> ```
> 
> I'm reasonably sure the rest of the `$$` characters are for shell scripts that get written on-the-fly.

I did a global search as well, and I believe this was the only error of this sort.

**Comment by pjk25** [comment]
I guess there is not a test case that covers #7161 directly?

**Comment by lukebakken** [comment]
Probably not. I can add one that confirms the default value.

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
