### PR TITLE
Track messages that were not routed anywhere and also not published as mandatory

### PR DESCRIPTION
**Pull request by michaelklishin**
## Proposed Changes

This introduces a metric for messages that were not routed anywhere but also weren't published as
mandatory, so they have to be dropped. See #1904 for background.

This metric won't be reported by older nodes so we will hide it behind a [feature flag](https://www.rabbitmq.com/blog/2019/04/23/simplifying-rolling-upgrades-between-minor-versions-with-feature-flags/).

Depends on

 * https://github.com/rabbitmq/rabbitmq-common/pull/324
 * https://github.com/rabbitmq/rabbitmq-management-agent/pull/79
 * https://github.com/rabbitmq/rabbitmq-management/pull/695

Pair: @dcorbacho.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in related repositories

## Further Comments

Part of #1904.

[#165548314]

### CODE REVIEW

**Comment by gerhard** [comment]
👍 :shipit: 

image


image

image


Try it:

```
cd rabbitmq_prometheus
git pull && git checkout c976f66
cd docker
docker-compose up
```

**Comment by michaelklishin** [comment]
@gerhard we should try to explain better why some messages were returned vs. dropped. That's why @dcorbacho and I decided to use explicit metric names such as "unroutable (returned)" and "unroutable (dropped)" in management UI.

**Comment by gerhard** [comment]
image

**Comment by michaelklishin** [comment]
@gerhard 👍

**Comment by gerhard** [comment]
I can see some failing tests related to this change:

[rabbit_mgmt_gc_SUITE > non_parallel_tests > channel_stats](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git/jobs/test-rabbitmq-management-agent/builds/36#L5cc1d9db:811)

```erl
    #1. {error,
            {{badmatch,[]},
             [{rabbit_mgmt_gc_SUITE,channel_stats,1,
                  [{file,"test/rabbit_mgmt_gc_SUITE.erl"},{line,389}]},
              {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1748}]},
              {test_server,run_test_case_eval1,6,
                  [{file,"test_server.erl"},{line,1263}]},
              {test_server,run_test_case_eval,9,
                  [{file,"test_server.erl"},{line,1195}]}]}}
```

[src/rabbit_mgmt_db.erl:463 `rabbit_mgmt_db:fetch_slides/3` calls undefined function `rabbit_mgmt_data_compat:fill_drop_unroutable_metric/1`](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git/jobs/test-rabbitmq-management/builds/71#L5cc1d8b3:705)

```sh
src/rabbit_mgmt_db.erl:463 `rabbit_mgmt_db:fetch_slides/3` calls undefined function `rabbit_mgmt_data_compat:fill_drop_unroutable_metric/1`
src/rabbit_mgmt_data_compat.erl `rabbit_mgmt_data_compat:fill_drop_unroutable_metric/1` is not defined as a function
erlang.mk:6874: recipe for target 'xref' failed
```

**Comment by michaelklishin** [comment]
`rabbit_mgmt_data_compat` [comes from `rabbitmq_management_agent`](https://github.com/rabbitmq/rabbitmq-management-agent/blob/master/src/rabbit_mgmt_data_compat.erl#L53).

**Comment by michaelklishin** [comment]
@gerhard I cannot reproduce:

```
gmake ct-rabbit_mgmt_gc

# ... snip ...

TEST INFO: 1 test(s), 8 case(s) in 1 suite(s)

== rabbit_mgmt_gc_SUITE ==

  * [non_parallel_tests]
    queue_stats (00:02.038)
    quorum_queue_stats (00:01.723)
    connection_stats (00:01.255)
    channel_stats (00:01.223)
    vhost_stats (00:01.232)
    exchange_stats (00:01.213)
    node_stats (00:00.171)
    consumer_stats (00:01.187)
```

**Comment by gerhard** [comment]
Smells like race-condition to me. If you run 100 times only that specific tests, does it always pass?

**Comment by dcorbacho** [comment]
@gerhard I can't reproduce it either

**Pull request merged**
