### PR TITLE
Send www-authenticate header when basic auth present but it's wrong

### LINKED ISSUE #3181: HTTP API incorrectly returns HTTP 401 response when credentials are present but incorrect
Summary:  RabbitMQ 3.8.14 (EDIT: I could also reproduce this on 3.8.3) returns an invalid HTTP 401 response when I try to access the management api with wrong credentials.

Steps to reproduce: Direct with curl
```
C:\Windows\system32>curl -v http://<HOST>:15672/api/overview -u wronguser:wrongpw
*   Trying <IP_OF_HOST>...
* TCP_NODELAY set
* Connected to <HOST> (<IP_OF_HOST>) port 15672 (#0)
* Server auth using Basic with user 'wronguser'
> GET /api/overview HTTP/1.1
> Host: <HOST>:15672
> Authorization: Basic d3Jvbmd1c2VyOndyb25ncHc=
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< content-length: 50
< content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'
< content-type: application/json
< date: Thu, 08 Jul 2021 15:05:00 GMT
< server: Cowboy
< vary: origin
<
{"error":"not_authorised","reason":"Login failed"}
```

What goes wrong?

That seems like a reasonable response, but isn't. [RFC-7235](https://datatracker.ietf.org/doc/html/rfc7235#section-3.1) demands that a HTTP 401 response MUST be accompanied by an `WWW-Authenticate` header. This header is present upon a GET request without credentials, but not when (wrong) credentials are provided.

What was expected instead?

Either the 401 response should contain the header even when a login attempt failed or the response should have status HTTP 403 instead.

### PR DESCRIPTION
**Pull request by deadtrickster**
## Proposed Changes

Send the `www-authenticate` header as per RFC.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

Closes #3181

### CODE REVIEW

**Comment by essen** [comment]
Wrong username, I'm @lhoguin for day job. Will look tomorrow.

**Review by lhoguin — APPROVED** [review]
LGTM

**Comment by lhoguin** [comment]
It should probably be backported to v3.8.x and v3.9.x.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Comment by michaelklishin** [comment]
Backported to `v3.9.x`.

**Pull request merged**
