### PR TITLE
avoid synchronous call to a connection process from a channel process

### PR DESCRIPTION
**Pull request by velimir**
Performance optimisation, see #2168 and #1886 for background.

## Proposed Changes

Pass amqp parameters for a direct channel as part of rabbit_channel start up arguments.

## Types of Changes

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

No tests except performance/smoke tests were performed. PR just to clarify a proposed change/issue: #2168

### CODE REVIEW

**Comment by velimir** [comment]
Feels like `#conf.source` is no longer needed in the state of the channel.

**Comment by michaelklishin** [comment]
Channel source was introduced in https://github.com/rabbitmq/rabbitmq-server/pull/1886. I have removed it and its related functions and running various test suites now. @velimir @acogoluegnes  can you please double check that this change does not undo what #1886 was introduced to address? A couple more reviewers would not hurt.

**Comment by velimir** [comment]
My understanding that #1886 was introduced mainly to avoid call to the connection process when channel is instantiated by a network client: https://github.com/rabbitmq/rabbitmq-server/pull/1886/files#diff-98224c82bfd7f4172da6a5adff2c42b0R1026

Since this PR removes the call for all connections (not only those which are spawned by `rabbit_reader`) it covers the case of the mentioned PR, however I would run performance tests for AMQP clients just to be sure.

**Comment by michaelklishin** [comment]
Superseded by #2172.

**Pull request closed without merging**
