### PR TITLE
rabbit_common add support for OTP 22

### PR DESCRIPTION
**Pull request by vkatsuba**
PR is related to https://github.com/rabbitmq/rabbitmq-server/issues/3307

### CODE REVIEW

**Comment by michaelklishin** [comment]
I'm sorry but we are not interested in adding this kind of complexity. Erlang 22 is no longer supported by RabbitMQ. Those who need to use `rabbit_common` on Erlang 22 can use an older version.

**Comment by michaelklishin** [comment]
By the way, `pg` and `pg2` may seem to be almost a drop-in replacement of one another but they are not. `pg2` relies on distributed locks and `pg` is strongly eventually consistent by design. This [can matter a great deal](https://github.com/rabbitmq/rabbitmq-server/pull/3263). I would not recommend anyone to assume that a macro shim would be safe to use or provide in a library.

**Comment by vkatsuba** [comment]
@michaelklishin thanks for code review and for providing explanation. Nevertheless it sounds sad, a lot of libraries try to support the last three versions and this means that everyone who uses this library will have to make a choice stop support OTP 22 or not etc. But in any case, many thanks for info.

Regards,
--V

**Comment by michaelklishin** [comment]
If the choice is between dropping support for 22 or not adopting 24, the answer is obvious: OTP 24 has so much to offer that people will be picking it over OTP 22 any day of the week.

**Pull request closed without merging**
