### PR TITLE
reject-publish strategy support for quorum queues

### PR DESCRIPTION
**Pull request by kjnilsson**
This PR includes 3 primary changes:

1. The rabbit_fifo machine version is updated from v0 to v1. See [Ra docs](https://github.com/rabbitmq/ra/blob/master/docs/internals/INTERNALS.md#state-machine-versioning) around machine versioning.

2. The ready messages data structure used by the state machine is changed from a map to a queue. The map is no longer needed as there is no need for arbitrary access to messages in the ready queue and has lower memory use per entry.

3. Reject publish overflow strategy for quorum queues:

The reject publish overflow strategy for quorum queues is an inexact
implementation that relies on the cooperation of publishing channels.
When a channel first wants to publish to a quorum queue it first issues
a synchonous register_enqueuer command which will return the current
queue overflow state as reject_publish if the queue is full.

The queue will also notify any active enqueuers when it reaches the
limit but will continue to accept any enqueues it receives after that.

Once the queue size goes below 80% of the limit(s) the queue will again
notify enqueuers that they can resume publishin inte the queue.

UPDATE: this PR now includes Queue TTL support for quorum queues.

### CODE REVIEW

**Comment by kjnilsson** [comment]
Ok so there are some failing tests suites. A lot of them seem to be a consequence of using Ra machine versioning with mixed 2 node clusters. It is not possible to declare a QQ in a mixed (machine version) cluster as Ra members will only ever vote for members with the same machine version as themselves. This is to ensure that the machine version never goes backwards. For some suites such as `dead_lettering it may be sufficient to bump the node count to 3. For others I will go through and see if the tests can be disabled for mixed mode or not.

**Review by Vanlightly — COMMENTED** [review]
Passed rigorous testing of both the reject-publish feature and tests of upgrading of machine version.

**Review by Vanlightly — APPROVED** [review]

**Comment by lukebakken** [comment]
This is awesome! One more nail in the HA queue coffin.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` for `3.8.10`.

**Pull request merged**
