### PR TITLE
Fix all dialyzer warnings in `rabbitmq_stomp`

### PR DESCRIPTION
**Pull request by binarin**
To fix all warnings, some bazel stuff is still needed.

### CODE REVIEW

**Comment by binarin** [comment]
@rin not sure how important it is to include elixir things in the plt

**Comment by pjk25** [comment]
I've made some changes in rules_erlang main that will help with this. I think we can leave this a draft until I release them with rules_erlang 3.9.0

**Comment by pjk25** [comment]
https://github.com/rabbitmq/rabbitmq-server/pull/6919 is in progress to solve the clash

**Comment by pjk25** [comment]
This should be rebased/merged with #6919

**Comment by michaelklishin** [comment]
@mergifyio rebase main

**Pull request merged**
