### PR TITLE
(Opt-in) Prometheus scraping endpoint authentication

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Added basic_authentication support to rabbitmq_prometheus plugin.

Refactored code:
Move is_authorized* from `rabbitmq_mgmt_util` to `rabbitmq_web_dispatch_util`, with any other function needed to 
do the refactor. Did not change rabbitmq_mgmt_util API at all.

New hrl file: `rabbitmq_web_dispatch_records.hrl`
That contains the context record (previously stored in ` rabbit_mgmt_records.hrl`) and an 'auth_settings' record.

No logic changes, other than the now use of auth_settings to provide config if basic_auth and oauth is enabled, provide 
oauth_id and auth realm.

All tests pass without changes (other than deps changes)

I would like to get extra eyes on `app.bzl` and `BUILD.bazel` files changed, so that I did not include unnecessary dependencies.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [x] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by SimonUnge** [comment]
I noticed Selenium failed - can I somehow run those locally?

**Comment by michaelklishin** [comment]
@SimonUnge see under [deps/rabbitmq_management/selenium](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_management/selenium).

**Comment by michaelklishin** [comment]
@MarcialRosales do you see anything obvious changes that the Selenium suite may need as a result of these changes?

**Comment by MarcialRosales** [comment]
@michaelklishin it is related to the changes done on this PR. Only the negative `idp-initited` test cases are failing.  On these test cases users hit the `login` POST [endpoint](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_management/src/rabbit_mgmt_login.erl#L23) with wrong credentials. The code `case rabbit_mgmt_util:is_authorized_user(Req0, #context{}, <<"">>, AccessToken, false) of` must be throwing a different error this time and this is causing a different outcome on the client side.

**Comment by michaelklishin** [comment]
@SimonUnge when you introduce new modules or test suites, or dependency tree between them changes, please run

``` shell
bazel run gazelle
```

and commit the changes. Gazelle is a new Bazel subproject that maintains build metadata using other sources (such as the codebase itself, plus some extensions).

**Comment by SimonUnge** [comment]
@MarcialRosales Thanks, I'm looking into what could have changed for that path! Don't see anything obvious but hunting it down.

**Comment by SimonUnge** [comment]
@michaelklishin Oh what a life save `bazel run gazelle` was! Amazing tool! One day I will try to actually understand bazel.

@MarcialRosales Found the issue, thank you!

**Review by michaelklishin — CHANGES_REQUESTED** [review]
Instead of dumping these functions into `rabbit_web_dispatch_util` we should introduce a new module, `rabbit_web_dispatch_access_control` or something like that.

**Comment by SimonUnge** [comment]
@michaelklishin Sounds good, will do.

**Review by michaelklishin — APPROVED** [review]
This looks good. I will do a bit more testing with HTTP API client libraries tomorrow.

Most likely this will have to wait until after `3.12.1` and `3.11.19`  ship.

**Pull request merged**
