### PR TITLE
Make cleanups and ct-master introduction

### PR DESCRIPTION
**Pull request by lhoguin**
More cleanups.

### CODE REVIEW

**Comment by lhoguin** [comment]
This is ready for review.

**Comment by lhoguin** [comment]
I probably broke tests.

**Review by michaelklishin — COMMENTED** [review]
I have been using this PR for a couple of days, mostly by starting nodes and running test suites "in the background" (in parallel to doing something else).

The speed-up is easy to observe. However, when I run all `deps/rabbit` suites, some fail with

```
rabbit_stream_queue_SUITE > cluster_size_3_parallel_4
    {error,
        {{assertEqual,
             [{module,rabbit_ct_broker_helpers},
              {line,1157},
              {expression,"CrashesCount"},
              {expected,0},
              {value,3}]},
         [{rabbit_ct_broker_helpers,find_crashes_in_logs,2,
              [{file,"rabbit_ct_broker_helpers.erl"},{line,1157}]},
          {rabbit_ct_broker_helpers,stop_rabbitmq_nodes,1,
              [{file,"rabbit_ct_broker_helpers.erl"},{line,1117}]},
          {rabbit_ct_helpers,run_steps,2,
              [{file,"rabbit_ct_helpers.erl"},{line,135}]},
          {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1793}]},
          {test_server,run_test_case_eval1,6,
              [{file,"test_server.erl"},{line,1390}]},
          {test_server,run_test_case_eval,9,
              [{file,"test_server.erl"},{line,1234}]}]}}

unit_cluster_formation_locking_mocks_SUITE > non_parallel_tests > init_with_lock_ignore_after_errors
    #1. {error,
            {{assertEqual,
                 [{module,unit_cluster_formation_locking_mocks_SUITE},
                  {line,63},
                  {expression,
                      "rabbit_peer_discovery : join_selected_node ( rabbit_peer_discovery_classic_config , missing@localhost , disc )"},
                  {expected,
                      {error,
                          {aborted_feature_flags_compat_check,
                              {error,feature_flags_file_not_set}}}},
                  {value,
                      {error,
                          {aborted_feature_flags_compat_check,
                              {error,{erpc,noconnection}}}}}]},
             [{unit_cluster_formation_locking_mocks_SUITE,
                  init_with_lock_ignore_after_errors,1,
                  [{file,"unit_cluster_formation_locking_mocks_SUITE.erl"},
                   {line,63}]},
              {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1793}]},
              {test_server,run_test_case_eval1,6,
                  [{file,"test_server.erl"},{line,1302}]},
              {test_server,run_test_case_eval,9,
                  [{file,"test_server.erl"},{line,1234}]}]}}

unit_cluster_formation_locking_mocks_SUITE > non_parallel_tests > init_with_lock_not_supported
    #1. {error,
            {{assertEqual,
                 [{module,unit_cluster_formation_locking_mocks_SUITE},
                  {line,71},
                  {expression,
                      "rabbit_peer_discovery : join_selected_node ( rabbit_peer_discovery_classic_config , missing@localhost , disc )"},
                  {expected,
                      {error,
                          {aborted_feature_flags_compat_check,
                              {error,feature_flags_file_not_set}}}},
                  {value,
                      {error,
                          {aborted_feature_flags_compat_check,
                              {error,{erpc,noconnection}}}}}]},
             [{unit_cluster_formation_locking_mocks_SUITE,
                  init_with_lock_not_supported,1,
                  [{file,"unit_cluster_formation_locking_mocks_SUITE.erl"},
                   {line,71}]},
              {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1793}]},
              {test_server,run_test_case_eval1,6,
                  [{file,"test_server.erl"},{line,1302}]},
              {test_server,run_test_case_eval,9,
                  [{file,"test_server.erl"},{line,1234}]}]}}

unit_cluster_formation_locking_mocks_SUITE > non_parallel_tests > init_with_lock_supported
    #1. {error,
            {{assertEqual,
                 [{module,unit_cluster_formation_locking_mocks_SUITE},
                  {line,80},
                  {expression,
                      "rabbit_peer_discovery : join_selected_node ( rabbit_peer_discovery_classic_config , missing@localhost , disc )"},
                  {expected,
                      {error,
                          {aborted_feature_flags_compat_check,
                              {error,feature_flags_file_not_set}}}},
                  {value,
                      {error,
                          {aborted_feature_flags_compat_check,
                              {error,{erpc,noconnection}}}}}]},
             [{unit_cluster_formation_locking_mocks_SUITE,
                  init_with_lock_supported,1,
                  [{file,"unit_cluster_formation_locking_mocks_SUITE.erl"},
                   {line,80}]},
              {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1793}]},
              {test_server,run_test_case_eval1,6,
                  [{file,"test_server.erl"},{line,1302}]},
              {test_server,run_test_case_eval,9,
                  [{file,"test_server.erl"},{line,1234}]}]}}

unit_config_value_encryption_SUITE > sequential_tests > decrypt_config
    #1. {error,
            {{badmatch,{error,{already_loaded,rabbit}}},
             [{unit_config_value_encryption_SUITE,do_decrypt_config,1,
                  [{file,"unit_config_value_encryption_SUITE.erl"},{line,71}]},
              {unit_config_value_encryption_SUITE,
                  '-decrypt_config/1-lc$^2/1-2-',6,
                  [{file,"unit_config_value_encryption_SUITE.erl"},{line,66}]},
              {unit_config_value_encryption_SUITE,decrypt_config,1,
                  [{file,"unit_config_value_encryption_SUITE.erl"},{line,67}]},
              {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1793}]},
              {test_server,run_test_case_eval1,6,
                  [{file,"test_server.erl"},{line,1302}]},
              {test_server,run_test_case_eval,9,
                  [{file,"test_server.erl"},{line,1234}]}]}}
```

which might have something to do with the changes to how CT suites are started.

Otherwise functionally it works as expected and the speed-up of many operations is really appreciated.

**Comment by lhoguin** [comment]
Make sure to `make -C deps/rabbitmq_ct_helpers` so it catches the changes. Right now it is not always rebuilt (because our projects are in deps/). This should help solve the `noconnection` issues. If not, then perhaps something else is afoot.

The first one about crashes in logs is expected and should not result in test failure.

The last one about rabbit already being loaded... I'm not sure. But since it's loading rabbit within the test we can change the test to accomodate. I will look into it.

**Comment by michaelklishin** [comment]
FTR, there was an automatically generated follow-up PR https://github.com/rabbitmq/rabbitmq-server/pull/12197.

**Comment by lhoguin** [comment]
Right, thanks.

**Pull request merged**
