### PR TITLE
Don't expand plugins that are already unpacked

### PR DESCRIPTION
**Pull request by binarin**
This prevents creating unnecessary files when running in embedded
mode, and in development mode it keeps code path clean and compatible
with different interactive tools.

### CODE REVIEW

**Comment by hairyhum** [comment]
Looks good. Though I'm a bit concerned about using `plugins_dist_dir` in the `active/0` function, because it's unzipping an `.app` file every time. On other hand, the function is not widely used (only in plugin operation), so it should be fine.

**Comment by binarin** [comment]
I've updated the commit message.

**Comment by michaelklishin** [comment]
We will postpone this until after 3.6.10 GA ships.

**Comment by michaelklishin** [comment]
@binarin I updated a few error messages and tuple tags in https://github.com/rabbitmq/rabbitmq-server/pull/1227. Can you please update this PR accordingly? Thank you.

**Comment by binarin** [comment]
I've cherry-picked fb17eed here.

**Pull request merged**
