### PR TITLE
Stricter test setup for simple_ha_SUITE

### PR DESCRIPTION
**Pull request by pjk25**
This change is aimed at reducing spurious test failures in CI.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Should this be backported or an effectiveness conclusion is still pending?

**Comment by pjk25** [comment]
I believe yes. It's run 4 or 5 times, and the suite in question hasn't flaked. Even if this fails to fix it, the error should be more informative.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Comment by pjk25** [comment]
Backported to 3.8 https://github.com/rabbitmq/rabbitmq-server/commit/4112120bddd0953a2917112228786332a5e59967

**Comment by pjk25** [comment]
Backported to `v3.7.x`.

**Pull request merged**
