### PR TITLE
Fix GHA yaml for Windows build

### PR DESCRIPTION
**Pull request by lukebakken**
Reference:
https://github.com/rabbitmq/rabbitmq-server/actions/runs/7210082496/workflow

### CODE REVIEW

**Comment by pjk25** [comment]
Is this still needed given that #10803 was merged?

**Comment by lukebakken** [comment]
I'm not sure. The Windows GHA is still broken - https://github.com/rabbitmq/rabbitmq-server/actions/runs/8429757111

**Comment by pjk25** [comment]
> I'm not sure. The Windows GHA is still broken - https://github.com/rabbitmq/rabbitmq-server/actions/runs/8429757111

The error is not one I've seen before
```Executing tests from //deps/rabbit:mc_unit_SUITE
-----------------------------------------------------------------------------
The system cannot find the batch label specified - no_focus_no_shard
```

Will have to look into it

**Comment by pjk25** [comment]
> > I'm not sure. The Windows GHA is still broken - https://github.com/rabbitmq/rabbitmq-server/actions/runs/8429757111
> 
> The error is not one I've seen before
> 
> ```
> -----------------------------------------------------------------------------
> The system cannot find the batch label specified - no_focus_no_shard
> ```
> 
> Will have to look into it

Ah, I remember now. Very short suite names break one of the windows scripts in rules_erlang, for reasons I cannot fathom. The solution in the past was just to rename the suite so that the [name]_SUITE had name longer than 2 characters.

**Comment by pjk25** [comment]
we can merge this because it should reduce the number of dependabot PRs

**Comment by pjk25** [comment]
> Ah, I remember now. Very short suite names break one of the windows scripts in rules_erlang, for reasons I cannot fathom. The solution in the past was just to rename the suite so that the [name]_SUITE had name longer than 2 characters.

Oh, that's not quite right. That did happen, but I see these names are not so short. But they also break the batch script in a similar manner it seems.

**Pull request closed without merging**
