### PR TITLE
Fix rabbit_vm:memory returning stream_queue_coordinator_procs

### PR DESCRIPTION
**Pull request by gomoripeti**
## Proposed Changes

The memory of `rabbit_stream_coordinator` process was reported as "other", because there was a mismatch in ancestors. It is not under `ra_server_sup_sup` but: `[_,ra_coordination_server_sup_sup,_,ra_systems_sup,ra_sup,_]`

Observed with versions ra 2.4.5, 2.4.6 RabbitMQ 3.11.5

I'm not sure if this is the correct fix.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by kjnilsson** [comment]
This looks like it could work but as we now have a separate supervisor for quorum queues and coordination type ra machine we don't need to use `ra_type/1` to distinguish between them. I think it would be better just to use the supervisors + maybe the registered name (for difference coordination types) to distinguish between quorum queue and other memory use.

**Review by michaelklishin — CHANGES_REQUESTED** [review]
Should this be under "stream server sups" instead?

**Comment by gomoripeti** [comment]
Pushed a second try. I kept the stream coordinator separate from stream servers, with the consideration that the former is a raft process, the laters are osiris processes. And we've seen cases when the stream coordinator alone was consuming a lot of memory.

**Comment by gomoripeti** [comment]
Looks like deps.rabbit.classic_queue_prop_SUITE.groups.classic_queue_v1 failed. I dont see how it is related to this change.

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
