### PR TITLE
Fix definitions import for 3.12.x

### LINKED ISSUE #7532: Version 3.12 does not import a definitions file correctly
Original discussion starts here: https://github.com/rabbitmq/rabbitmq-server/pull/5895#issuecomment-1458231497

Project to reproduce:
https://github.com/lukebakken/rabbitmq-server-5895-mqtt

`docker compose up` will start up the `pivotalrabbitmq/rabbitmq:v3.12.0-beta.1-otp-max-bazel` and try to import definitions, which won't happen. It's not just docker, as this doesn't work either:

```
make RABBITMQ_CONFIG_FILE="/home/lbakken/development/lukebakken/rabbitmq-server-5895-mqtt/rabbitmq-local.conf" PLUGINS='rabbitmq_management rabbitmq_top' run-broker
```

`RABBITMQ_IMAGE='rabbitmq:3-management' docker compose up` works correctly.

cc @michaelklishin @janiu-001

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #7532 

Add a lot of debugging to the detection of running nodes to begin with...

### CODE REVIEW

**Comment by lukebakken** [comment]
@michaelklishin this does fix the issue but of course it's a special-case for a target cluster size of 1. Should definitions import be moved later in the start sequence instead?

**Comment by lukebakken** [comment]
I feel like `rabbit_nodes:if_reached_target_cluster_size` and the functions it calls should be fixed, or definition import moved later, than "fixing" it by special-casing `1`

**Comment by michaelklishin** [comment]
@lukebakken it is already after plugin activation, to what step would you move it? or how would you suggest we fix `rabbit_nodes:if_reached_target_cluster_size/2`?

**Comment by michaelklishin** [comment]
We can special case `rabbit_nodes:if_reached_target_cluster_size/2` to immediately consider a single node cluster a success, for example.

**Comment by michaelklishin** [comment]
@mkuratczyk has put together a different solution in https://github.com/rabbitmq/rabbitmq-server/pull/7535. The culprit ended up being #7058.

**Pull request closed without merging**
