### PR TITLE
Fix cluster links statistic

### LINKED ISSUE #4981: "Cluster links" in management UI are broken when TLS dist is enabled
I discovered this issue while testing #4932 

Repro steps:
* Start cluster with inter-node TLS enabled.
* Open management UI, click on cluster node
* "Cluster links" will not have data

The problem is due to [this check](https://github.com/rabbitmq/rabbitmq-server/blob/cca1164afe1b39df4067de5d8ba74360cb0f010b/deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl#L361): [code](https://github.com/rabbitmq/rabbitmq-server/blob/cca1164afe1b39df4067de5d8ba74360cb0f010b/deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl#L361). `is_port/1` returns `false` for a TLS link.

I'm investigating if there is a workaround.

### PR DESCRIPTION
**Pull request by lukebakken**
Search all of the `tcp_inet` ports to find the port associated with disterl, then get stats.

Fixes #4981

### CODE REVIEW

**Comment by lukebakken** [comment]
@michaelklishin if you'd like we could chat about the limitations of these changes.

**Comment by lukebakken** [comment]
@michaelklishin - the "right" way to fix this issue for unencrypted and TLS distribution is to have our own `_dist` modules that have access to the listener socket and thus the stats for it when needed:

https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-4981/deps/rabbit/src/rabbit_tcp_dist.erl

I would save the associated port for the distribution listener to an ETS table and then use that when `node_node_metrics` are emitted.

Obviously, this requires changes to startup scripts, docs, etc so it's a complex solution in that manner.

**Comment by michaelklishin** [comment]
No, sorry. Like what we have here. Our own distribution modules sounds like a non-trivial undertaking to me.

**Comment by lukebakken** [comment]
> distribution modules sounds like a non-trivial undertaking to me

Well, actually...check this out:

https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-4981/deps/rabbit/src/rabbit_tcp_dist.erl

This implements the bare minimum API, delegating the work to the `inet_tcp_dist` module in OTP. We only care about recording the return value of the `listen/2` and `listen/1` calls, because they will contain the socket/port for the dist connection.

I'm going to do the same for TLS just to make sure my idea pans out.

**Comment by lukebakken** [comment]
Guess what, the code we need is already here -

https://github.com/deadtrickster/prometheus.erl/blob/master/src/collectors/vm/prometheus_vm_dist_collector.erl

**Comment by lukebakken** [comment]
@michaelklishin success! Thanks for the inspiration @deadtrickster

**Comment by michaelklishin** [comment]
The failures are unrelated as @pjk25 and I have figured. It's something specific to BuildBuddy's networking setup, some AMQP 1.0 clients fail to connect to/from localhost.

**Pull request merged**
