### PR TITLE
Restore using ERL_DIR

### PR DESCRIPTION
**Pull request by serhiimelnik**

### CODE REVIEW

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ.

We can't accept pull requests without any rationale. Could you please explain this proposed change?

@dumbbell removed the use of `ERL_DIR` in [this commit](https://github.com/rabbitmq/rabbitmq-server/commit/68c30553ccf306325a64b1fe6069e6bcc9c26b41) as it was related to RabbitMQ packaging and not used after that commit.

The expectation is that `erl` is in your `PATH`.

**Comment by pivotal-issuemaster** [comment]
@serhiimelnik Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-server&pullRequestId=2461)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-server&pullRequestId=2461) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by serhiimelnik** [comment]
The old version of ...etc/rabbitmq/rabbitmq-env.conf had params such as `ERL_DIR`, `CLEAN_BOOT_FILE` etc.
This is useful when developing applications with different erl versions.
Why can I change  https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-server#L93 path but cannot change erl path?

**Comment by lukebakken** [comment]
@dumbbell may have more to add, but I doubt we will bring back `ERL_DIR`. If you test with multiple Erlang versions, I suggest using something like `kerl` to switch between them, or manage the `PATH` variable yourself.

**Comment by dumbbell** [comment]
Hi!

I should have noted why I removed the variable. If I remember correctly, the problem with `$ERL_DIR` was that you may end up using a version of Erlang to start the broker (the one in `$ERL_DIR`), but another one for the subsequent uses of the CLI (the one in the `$PATH`).

Because modifying `$PATH` is an easy way to point to a specific non-default version of Erlang, I feel it's less error-prone.

**Comment by serhiimelnik** [comment]
Ok, thanks.

**Pull request closed without merging**
