### PR TITLE
Add ability to customize product name, version & banner [v3.8.x]

### PR DESCRIPTION
**Pull request by dumbbell**
This the equivalent of #2247 for `v3.8.x`.

### CODE REVIEW

**Comment by gerhard** [comment]
Deferring this to 3.8.4 so that investigating & fixing [this CI failure](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.9.x/jobs/test-package-windows-on-windows-server-2012/builds/198) doesn't block the release of v3.8.3.

**Comment by dumbbell** [comment]
Using `os:set_signal/2` on Windows was indeed the cause of the failure in CI. Thsi has been fixed in `master` and this patch was updated accordingly.

**Comment by dumbbell** [comment]
Ci is happy again!

**Comment by dumbbell** [comment]
I will update the patch with the recently written testsuite.

**Pull request merged**
