### PR TITLE
[OCF HA] On neighbor promotion do nothing if we are already clustered

### PR DESCRIPTION
**Pull request by dmitrymex**
[OCF HA] On neighbor promotion do nothing if we are already clustered

 + extracted function checking if we are in the same cluster with
   given node

 + made post-promote ignore promotion of self. Previously it was
   done inside jjj_join, but now we need to do that before the
   new check.

 + now we write "post-promote end" log entry at the very
   end of post-promote, not somewhere in the middle.

### CODE REVIEW

**Comment by dmitrymex** [comment]
please note that this pull request is based on #654, which must be merged first

**Comment by michaelklishin** [comment]
@dmitrymex @bogdando if you want this as well as #653, #654 to make it into `3.6.1`, we have to get a go-ahead from you and merge them today.

**Comment by dmitrymex** [comment]
@bogdando : could you please take a look?

**Comment by dmitrymex** [comment]
@michaelklishin : Thanks for letting us know. These are non-critical enhancements, so it is not that important for them to get into 3.6.1

**Comment by dmitrymex** [comment]
Update: that PR is based on #658 , the previous PR - #654 was made to master

**Comment by bogdando** [comment]
LGTM

**Pull request merged**
