### PR TITLE
Improve error reporting in rabbitmqctl.bat

### LINKED ISSUE #1735: rabbitmqctl.bat fails but returns zero exit code
The simplest way to reproduce the issue is to run `rabbitmqctl.bat` for non-existing node:
```
rabbitmqctl.bat status -n unknown
```

It returns expected "unable to perform an operation on node" result:
```
Status of node unknown@DESKTOP-3N6MII0 ...
Error: unable to perform an operation on node 'unknown@DESKTOP-3N6MII0'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node unknown@DESKTOP-3N6MII0
```

The `%ERRORLEVEL%` variable is not zero:
```
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.3\sbin>echo %ERRORLEVEL%
69
```

But the exit code is zero. The easiest way to check it is to run the same command from PowerShell and check `$LastExitCode`:
```
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.3\sbin> .\rabbitmqctl.bat status -n unknown
...

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.3\sbin> $LASTEXITCODE
0
```

### PR DESCRIPTION
**Pull request by ar7z1**
## Proposed Changes

In this PR I've fixed #1735. The fix is the same as @kjnilsson did in #1053.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you. I definitely think it should be added to `rabbitmq-plugins.bat`. `rabbitmq-diagnostics.bat` is less commonly used and almost always interactively but it's probably worth having there, too, as it can be involved in automation as well.

**Comment by ar7z1** [comment]
@michaelklishin, Should I add the changes in `rabbitmq-plugins.bat` and other bat scripts in this PR? Or create separate PRs?

**Comment by michaelklishin** [comment]
@ar7z1 just amend this PR. Thank you!

**Comment by ar7z1** [comment]
@michaelklishin Pushed! :-)

**Comment by ar7z1** [comment]
@michaelklishin Thank you for review and merge :-)

**Pull request merged**
