### PR TITLE
RFC Channel tracking improvements

### PR DESCRIPTION
**Pull request by gomoripeti**
## Proposed Changes

These changes try to reduce the overhead of channel tracking.

I'd like to request some guidance on a few things
1) changing the #tracked_channel{} record (field order) (https://github.com/rabbitmq/rabbitmq-server/pull/5084/files#diff-95cf3628dbe97cf5a880e399fcc4b397d4717d75229bab78e2696b102768b226R196): This record is returned by the list[_of_user|on_node] functions so could theoretically travel between nodes with different versions. But I dont see these functions used anywhere. And the shape of the record does not change, just the values would be mixed up. What is the correct or practical way to change record format in this case?
2) changing the key field of the channel_tracking table (https://github.com/rabbitmq/rabbitmq-server/pull/5084/files#diff-db98dcef04e61dfe1a3337886a0d45adf3cabf7f70126b4890d64f07e2cb8a6dR245-R255) : the table is memory-only and has a copy on only one node. Therefore it's safe to change attributes order as the table is empty at startup when the upgrade should happen. After I added the custom code for the upgrade I noticed the rabbit_upgrade and rabbit_upgrade_functions modules - is that the right way to do any mnesia table changes? is this a local or mnesia upgrade step?
3) channel-tracking a noop if not used: I skipped adding a rabbit_event handler if user_limits feature is disabled (as an easy fix). However I dont think its enough in practice. A feature cannot be disabled once enabled (if I understand correctly) and even if there is a per-user connection limit, there could be no channel-limit. There could be more clever solutions (like only add the handler if at least one user has channel-limit) Or an explicit solution to add a config to disable channel-tracking. What do you think? Which route should I explore?

Rough results of optimisation (commit a9f1f04d422f5d75df64989db4cccc4b1b1a4732)

Closing 10,000 channels (my flamegraphs are not perfect. it's not visible where `mnesia_lib:db_match_object/3` is called from, but they disappear after the change)
Before
cpu_close_channels_10000_2

After
cpu_close_channels_10000_optimized

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
1. Those functions could be added during development for our own needs (to inspect the tables) or be only used in tests. Running a mixed version cluster and tailing logs of all nodes should quickly tell you if it's actually used or not.
2. `rabbit_upgrade_functions` is like a collection of migration functions. If the table is local, its migration can still affect other nodes because table "shape" changes are reflected in Mnesia schema table changes. But you can try a local upgrade step and then run a mixed version cluster.
3. Having a `gen_event` handler around is not an issue if it doesn't do anything, so we can keep it as a safety measure.

**Comment by gomoripeti** [comment]
thanks for the feedback

**Comment by lukebakken** [comment]
Connection and channel tracking are liabilities in high-churn scenarios - https://github.com/rabbitmq/rabbitmq-server/discussions/4872

I would like to see configuration options to disable one or both, as well as the ability to rate-limit the tracking events being sent to `rabbit_event`

**Comment by mkuratczyk** [comment]
I think https://github.com/rabbitmq/rabbitmq-server/pull/5301 addresses the problem that this PR was supposed to address.

@gomoripeti can you please have a look at https://github.com/rabbitmq/rabbitmq-server/pull/5301 and see if you can reproduce the original problem?

**Comment by gomoripeti** [comment]
sorry I made slow progress because of the holiday season.

great to see #5301 and that it uses ETS tables (as discussed here https://github.com/rabbitmq/rabbitmq-server/pull/5222#issuecomment-1185384246). It covers the most important part of having the channel PID as key.
I appreciate the Core Team takes care of the cumbersome part of upgrade code for mixed-version clusters.

**Pull request closed without merging**
