### PR TITLE
Handle missing delivery marker in CQ v1 index

### PR DESCRIPTION
**Pull request by gomoripeti**
## Proposed Changes

This can happen when a classic queue has messages published on a
pre-3.10 RabbitMQ version, but still present after an upgrade to 3.10+.

The PR implements the workaround suggested in https://github.com/rabbitmq/rabbitmq-server/issues/7904#issuecomment-1519809803

The test cases are not the nicest and a bit intrusive. It is also somewhat random that I added them to the property-based test suite (Initially I thought that there could be random tests starting off from a queue with missing del markers. In the end I just added a few scenarios which cover all 3 functions changed) The scenarios are very time sensitive to when a sync or flush happens, I used `meck:wait` to have the right timings. I am happy to take any suggestions of what to adjust about the tests. (Kept the tests as a separate commit, so I can make sure they all fail without the fix, but should be squashed before merging)

I'd be happy if the fix is released in 3.10.x and 3.11.x as well.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Review by lhoguin — APPROVED** [review]
Looks good to me outside the BUILD.bazel change which I don't know much about.

I have also been running the property suite for a couple hours with no errors.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@gomoripeti we'd be happy to backport this but there are seemingly repeatable failures in the property test suite on `v3.11.x`: https://github.com/rabbitmq/rabbitmq-server/actions/runs/5154728174/jobs/9283524258?pr=8458.

**Comment by michaelklishin** [comment]
@gomoripeti here is the failure:

```
Executing tests from //deps/rabbit:classic_queue_prop_SUITE
-----------------------------------------------------------------------------
Test Suite Structure: [{classic_queue_tests,
                           [classic_queue_v1,lazy_queue_v1,classic_queue_v2,
                            lazy_queue_v2]},
                       {classic_queue_regressions,
                           [reg_v1_full_recover_only_journal,
                            reg_v1_no_del_jif,reg_v1_no_del_idx,
                            reg_v1_no_del_idx_unclean]}]
Total cases: 8
Suite contains 8 cases; In -case sharding mode set shard_count to match
ERROR: wrong_shard_count
```

so apparently it's not a test suite issue but a build system one.

**Comment by michaelklishin** [comment]
I still have failures locally with

``` shell
bt //deps/rabbit:classic_queue_prop_SUITE
```

but let's see how https://github.com/rabbitmq/rabbitmq-server/pull/8458 does on Actions/BuildBuddy now that the shard count was set to 8.

**Comment by michaelklishin** [comment]
Let's move this discussion to https://github.com/rabbitmq/rabbitmq-server/pull/8458.

**Pull request merged**
