### PR TITLE
Syntax and local vars usage fixes to OCF HA

### PR DESCRIPTION
**Pull request by bogdando**
Related Fuel bug:
https://launchpad.net/bugs/1529897

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by bogdando** [comment]
@dmitrymex

**Comment by michaelklishin** [comment]
Will merge as soon as I have a go-ahead from @dmitrymex.

**Comment by dmitrymex** [comment]
@michaelklishin: yep, the change looks good to me

**Comment by michaelklishin** [comment]
Thank you, gents.

**Comment by bogdando** [comment]
You wellcome! I found a completely new bug case for the beam process running unresponsive (like kill -STOP). Hence, new PR incoming ...

**Pull request merged**
