### PR TITLE
Check Shovel parameter for existence when dynamic SHovel worker starts

### LINKED ISSUE #2655: Dynamic shovels that are deleted can be resurrected in clustered environments
Reported here:
https://groups.google.com/g/rabbitmq-users/c/k4Qwge4mC08

Script to reproduce:
https://github.com/lukebakken/deleted-queue-restored-k4Qwge4mC08/blob/master/repro.sh

What's happening is that even though the dynamic shovels are set to auto delete, the `rabbit_shovel_dyn_worker_sup_sup` remains alive. The process survives a full cluster restart thanks to `mirrored_supervisor`, and after a full restart several of the deleted queues are re-created.

You can see that the dynamic shovel parameters have been cleared out as expected when the shovels delete themselves.

This does not happen in single-node environments as there is no way for the supervisor to survive the restart.

@dcorbacho @michaelklishin ideas?

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #2655

### CODE REVIEW

**Comment by lukebakken** [comment]
@michaelklishin I just fixed the `xref` error and I don't believe the other build errors are related if you'd like to re-review.

**Review by michaelklishin — APPROVED** [review]

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@lukebakken out of all the solutions we have tried, I like this the most 👍

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Comment by lukebakken** [comment]
Thank you @michaelklishin

**Pull request merged**
