### PR TITLE
Supervisor2 tests have moved to rabbitmq-common

### PR DESCRIPTION
**Pull request by lukebakken**
Part of rabbitmq/rabbitmq-common#411

### CODE REVIEW

**Comment by michaelklishin** [comment]
Is there a reason why this has to be in `rabbitmq/rabbitmq-common`?

**Comment by michaelklishin** [comment]
I will move the new test suite to https://github.com/rabbitmq/rabbitmq-common/pull/411.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Let's wait for a week or two before backporting.

**Comment by lukebakken** [comment]
Thanks for moving the tests. They were originally in the `rabbitmq-server` repo so I just left them there.

**Pull request merged**
