### PR TITLE
Bazel minor updates

### LINKED ISSUE #6703: bazel: add rabbit-queues cmd to bazel, add default consumer_timeout to bazel (to match Make build default)
bazel is missing the rabbit-queues cmd, so just add the target.
Also, according to the documentation, the default value for consumer_timeout is 30 minutes, but
this value is not set when building source with bazel, so add it to match building with MAKE.

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Fix #6703 
Minor updates to bazel build environment.
Add rabbit-queues target.
Add consumer_timeout default value to match documentation (https://www.rabbitmq.com/consumers.html#acknowledgement-timeout) and MAKE dito.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [x] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This reliably fails with

```
  Creating PLT bazel-out/darwin_arm64-fastbuild/bin/deps/rabbitmq_federation_management/.base_plt.plt ...
rabbit_mgmt_login.erl:23:8: Call to missing or unexported function rabbit_mgmt_util:is_authorized_user/5
```

for me. Curiously `rabbit_mgmt_login.erl` is file that does not seem to exist in `main`.

**Comment by michaelklishin** [comment]
This might be due to Bazel 6, a `bazel clean` seems to have helped.

**Comment by SimonUnge** [comment]
> This might be due to Bazel 6, a `bazel clean` seems to have helped.

Yes, the change is so minor is should not (famous last words) cause any issues

**Comment by michaelklishin** [comment]
@mergifyio rebase

**Comment by michaelklishin** [comment]
Something is off with mixed version cluster testing, bumping Erlang rules has helped with the rest.

**Pull request merged**
