### PR TITLE
Cancel queue federation consumers less frequently

### PR DESCRIPTION
**Pull request by lukebakken**
Only basic.cancel a queue consumer at most every 30 seconds to prevent frequent cancellations when consumer prefetch is low.

@mkuratczyk - The key ingredient of this whole issue is a small prefetch on the client side (in our repro, it's 1). So what happens is:

1. downstream queue is empty
2. therefore, federation subscribes to the upstream queue and gets some messages
3. some of these messages are not immediately delivered, because consumer(s) have a very low prefetch
4. therefore the downstream queue is no longer empty, so federation cancels the subscription
5. very quickly all the ready messages get consumed, so the queue is empty
6. GOTO 1

* VESC-1082
* https://vmware.slack.com/archives/C05J0Q8U6KD/p1692710684158239

### CODE REVIEW

**Comment by mkuratczyk** [comment]
I will think about the potential consequences of this, but my gut feeling is that this could be a 3.13 improvement, but should not be a patch release change. There are some complex federation configurations out there and we could break their equilibrium with this change I guess. I will test it tomorrow to see if I can find any obvious behaviour changes though.

**Comment by michaelklishin** [comment]
@mkuratczyk queue federation uses negative priority for its consumers, so I don't think this will have any negative effects. Regular (application) consumers will still always have higher priority in any realistic environment.

**Comment by mkuratczyk** [comment]
Right. Yeah, then we'll see how the testing goes. If we can't break it and can't come up with a scenario that could break it, I think it'll be a good patch release improvement.

**Comment by mkuratczyk** [comment]
I do see a change in behaviour with this patch. The steps I follow are basically the same as before, although I use perf-test and stop the publisher before starting the consumers, so:
1. Import https://github.com/mkuratczyk/vesc-1079-1082/blob/local-broker/local-defs.json
2. `perf-test -H amqp://localhost/vhost0 -qq -u inventory-fed -y 0 -c 100 -C 100000`
3. then `perf-test -H amqp://localhost/vhost2 -qq -u inventory-fed -x 0 -q 1 -z 5` (one consumer is sufficient)

After that, I'd expect most messages to still be on vhost0, but they are not, which is the first difference (it seems like it won't stop even though it lost the consumer). Secondly, it seems to be doing something even after all messages were moved to the downstream queue. If you watch the recording till the end, you'll see the number of messages ready in vhost2 changes and the federation link status shows a high message rate.


https://github.com/rabbitmq/rabbitmq-server/assets/9566114/1b83c0a1-5e8b-44a0-b800-040e2b2d1e7d

**Comment by eibbojtir** [comment]
> If you watch the recording till the end, you'll see the number of messages ready in vhost2 changes and the federation link status shows a high message rate.
> 
>  Screen.Recording.2023-08-23.at.14.07.06.mov

Please ignore if this is noise: That high message rate reminds me of the issue that was fixed in 3.11.17 here:
https://github.com/rabbitmq/rabbitmq-server/pull/8282

**Comment by lukebakken** [comment]
Thanks @mkuratczyk - I will give that a try.

**Comment by lukebakken** [comment]
@mkuratczyk yessir I can see what you report and indeed this PR is not valid.

**Pull request closed without merging**
