### PR TITLE
Management UI: arranged and reorganized vertical bars in management console when declaring queues

### PR DESCRIPTION
**Pull request by markus812498**
## Proposed Changes

Formatting and organising the vertical bars and list of parameters for queues in the management console to make it look nicer and more structured. 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by michaelklishin** [comment]
@markus812498 @LoisSotoLopez @gomoripeti I would really appreciate if before submitting a PR, any PR, for any branch, CloudAMQP engineers would update the base branch to the latest.

This branch is 148 commits behind. The core team routinely has to rebase contributing over dozens of not several hundreds of commits for contributions from your GitHub fork.

For example, right now I cannot even take a look at the change because there are no "before/after" screenshots and rebasing fails with a conflict.

I have resolved the conflict, and there was another one. And another one. And another one. I have given up on conflict number 6.

Why some of the unrelated changes conflict with forks weeks behind, I don't know. But I do know that PRs from other contributors virtually never have this problem.

**Comment by michaelklishin** [comment]
And yes, I can create a new local branch and cherry-pick https://github.com/rabbitmq/rabbitmq-server/pull/12658/commits/98c2363a79a77c60d3bc934d3c99df8d181c7684 there.

Not every PR has just one commit, and I am not going to squash them to then create a branch to then cherry pick the squashed commit.

**Comment by michaelklishin** [comment]
## Before (4.0.3)

Before rabbitmq-server#12658

## After

After rabbitmq-server#12658

**Comment by markus812498** [comment]
> @markus812498 @LoisSotoLopez @gomoripeti I would really appreciate if before submitting a PR, any PR, for any branch, CloudAMQP engineers would update the base branch to the latest.
> 
> This branch is 148 commits behind. The core team routinely has to rebase dozens of not several hundreds of commits for PRs originating from your GitHub fork.
> 
> For example, right now I cannot even take a look at the change because there are no "before/after" screenshots and rebasing fails with a conflict.
> 
> I have resolved the conflict, and there was another one. And another one. And another one. I have given up on conflict number 6.
> 
> Why some of the unrelated changes conflict with forks weeks behind, I don't know. But I do know that PRs from other contributors virtually never have this problem.

You're right, I must've forgot to pull down the latest changes from upstream. I'll make sure to do that going forward, sorry for the hassle.

**Comment by michaelklishin** [comment]
#12677.

**Pull request closed without merging**
