### PR TITLE
Take "true" case into consideration

### LINKED ISSUE #1682: Node logs a failed assertion after a partial partition
Recently had a RabbitMQ Cluster member die with the below errors 

RabbitMQ 3.7.4 
Erlang 20.2.3
Sensu Core 1.4
CentOS 7.5.1804

Call this node-bad
```
2018-08-24 12:36:28.840 [error] <0.22942.63> Error on AMQP connection <0.22942.63> (127.0.0.1:48462 -> 127.0.0.1:5671, vhost: '/sensu', user: 'sensu', state: running), channel 1:
 {{badmatch,true},
 [{rabbit_amqqueue,retry_wait,4,[{file,"src/rabbit_amqqueue.erl"},{line,509}]},
  {rabbit_channel,handle_method,5,
                  [{file,"src/rabbit_channel.erl"},{line,2189}]},
  {rabbit_channel,handle_method,3,
                  [{file,"src/rabbit_channel.erl"},{line,1390}]},
  {rabbit_channel,handle_cast,2,[{file,"src/rabbit_channel.erl"},{line,523}]},
  {gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},
  {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}
2018-08-24 12:36:28.840 [error] <0.22949.63> ** Generic server <0.22949.63> terminating
** Last message in was {'$gen_cast',{method,{'queue.declare',0,<<"keepalives">>,true,false,false,true,false,[]},none,noflow}}
** When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,<0.22942.63>,<0.22951.63>,<0.22942.63>,<<"127.0.0.1:48462 -> 127.0.0.1:5671">>,{lstate,<0.22950.63>,false},none,1,{[],[]},{user,<<"sensu">>,[],[{rabbit_auth_backend_internal,none}]},<<"/sensu">>,<<"results">>,#{<5401.825.0> => {resource,<<"/sensu">>,queue,<<"results">>}},{state,{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[[<5401.825.0>|#Ref<0.1905404133.1772879874.82952>]],[],[],[],[],[],[],[],[],[],[],[]}}},erlang},#{},#{},{set,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},<0.22941.63>,{state,fine,5000,#Ref<0.1905404133.1834745862.72788>},false,1,{{0,nil},{0,nil}},[],[],{{0,nil},{0,nil}},[{<<"publisher_confirms">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"authentication_failure_close">>,bool,true}],none,1,none,flow,[]}
** Reason for termination ==
** {{badmatch,true},[{rabbit_amqqueue,retry_wait,4,[{file,"src/rabbit_amqqueue.erl"},{line,509}]},{rabbit_channel,handle_method,5,[{file,"src/rabbit_channel.erl"},{line,2189}]},{rabbit_channel,handle_method,3,[{file,"src/rabbit_channel.erl"},{line,1390}]},{rabbit_channel,handle_cast,2,[{file,"src/rabbit_channel.erl"},{line,523}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}
2018-08-24 12:36:28.840 [warning] <0.22942.63> Non-AMQP exit reason '{{badmatch,true},[{rabbit_amqqueue,retry_wait,4,[{file,"src/rabbit_amqqueue.erl"},{line,509}]},{rabbit_channel,handle_method,5,[{file,"src/rabbit_channel.erl"},{line,2189}]},{rabbit_channel,handle_method,3,[{file,"src/rabbit_channel.erl"},{line,1390}]},{rabbit_channel,handle_cast,2,[{file,"src/rabbit_channel.erl"},{line,523}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}'
2018-08-24 12:36:28.841 [error] <0.22949.63> CRASH REPORT Process <0.22949.63> with 0 neighbours exited with reason: no match of right hand value true in rabbit_amqqueue:retry_wait/4 line 509 in gen_server2:terminate/3 line 1166
```
Simultaneously on node-1
```
2018-08-24 12:36:27.261 [info] <0.458.0> rabbit on node 'rabbit@node-bad' down
2018-08-24 12:36:27.261 [error] <0.349.0> ** Node 'rabbit@node-bad' not responding **
** Removing (timedout) connection **
2018-08-24 12:36:27.269 [info] <0.458.0> Node rabbit@node-bad is down, deleting its listeners
2018-08-24 12:36:27.653 [warning] <0.757.0> Management delegate query returned errors:
[{<5402.536.0>,{exit,{nodedown,'rabbit@node-bad'},[]}}]
2018-08-24 12:36:28.839 [error] <0.175.0> Mnesia('rabbit@node-1'): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, 'rabbit@node-bad'}
2018-08-24 12:38:35.368 [info] <0.458.0> node 'rabbit@node-bad' down: net_tick_timeout
2018-08-24 12:38:35.368 [info] <0.458.0> node 'rabbit@node-bad' up
2018-08-24 12:38:35.390 [error] <0.458.0> Partial partition detected:
 * We saw DOWN from rabbit@node-bad
 * We can still see rabbit@node-2 which can see rabbit@node-bad
 * pause_minority mode enabled
We will therefore pause until the *entire* cluster recovers
2018-08-24 12:38:35.390 [warning] <0.458.0> Cluster minority/secondary status detected - awaiting recovery
2018-08-24 12:38:35.390 [error] <0.458.0> Partial partition detected:
 * We saw DOWN from rabbit@node-bad
 * We can still see rabbit@node-3 which can see rabbit@node-bad
 * pause_minority mode enabled
We will therefore pause until the *entire* cluster recovers
2018-08-24 12:38:35.390 [info] <0.30015.66> RabbitMQ is asked to stop...
2018-08-24 12:38:35.391 [warning] <0.458.0> Cluster minority/secondary status detected - awaiting recovery
2018-08-24 12:38:35.391 [error] <0.458.0> Partial partition detected:
 * We saw DOWN from rabbit@node-bad
 * We can still see rabbit@node-4 which can see rabbit@node-bad
 * pause_minority mode enabled
We will therefore pause until the *entire* cluster recovers
2018-08-24 12:38:35.391 [warning] <0.458.0> Cluster minority/secondary status detected - awaiting recovery
2018-08-24 12:38:35.495 [info] <0.30015.66> Stopping RabbitMQ applications and their dependencies in the following order:
```

Later during start up on node-1
```
2018-08-24 12:39:13.852 [info] <0.452.0> Closing all connections in vhost '/' on node 'rabbit@node-1' because the vhost is stopping
2018-08-24 12:39:13.852 [info] <0.452.0> Closing all connections in vhost '/sensu' on node 'rabbit@node-1' because the vhost is stopping
2018-08-24 12:39:13.876 [info] <0.30015.66> Stopping application 'mnesia'
2018-08-24 12:39:13.876 [info] <0.33.0> Application rabbit exited with reason: stopped
2018-08-24 12:39:14.893 [info] <0.33.0> Application mnesia exited with reason: stopped
2018-08-24 12:39:14.893 [info] <0.30015.66> Stopping application 'rabbit_common'
2018-08-24 12:39:14.893 [info] <0.30015.66> Stopping application 'os_mon'
2018-08-24 12:39:14.894 [info] <0.33.0> Application rabbit_common exited with reason: stopped
2018-08-24 12:39:14.897 [info] <0.33.0> Application os_mon exited with reason: stopped
2018-08-24 12:39:14.897 [info] <0.30015.66> Successfully stopped RabbitMQ and its dependencies
2018-08-24 12:39:15.172 [info] <0.33.0> Application lager started on node 'rabbit@node-1'
2018-08-24 12:39:15.173 [info] <0.30015.66> Log file opened with Lager
2018-08-24 12:39:15.223 [info] <0.33.0> Application mnesia started on node 'rabbit@node-1'
2018-08-24 12:39:15.295 [info] <0.33.0> Application mnesia exited with reason: stopped
2018-08-24 12:39:16.123 [error] <0.2846.68> Mnesia('rabbit@node-1'): ** ERROR ** mnesia_event got {inconsistent_database, starting_partitioned_network, 'rabbit@node-bad'}
2018-08-24 12:39:17.246 [info] <0.33.0> Application mnesia started on node 'rabbit@node-1'
2018-08-24 12:39:17.246 [info] <0.33.0> Application os_mon started on node 'rabbit@node-1'
2018-08-24 12:39:17.246 [info] <0.33.0> Application cowlib started on node 'rabbit@node-1'
2018-08-24 12:39:17.247 [info] <0.33.0> Application cowboy started on node 'rabbit@node-1'
2018-08-24 12:39:17.247 [info] <0.33.0> Application rabbit_common started on node 'rabbit@node-1'
2018-08-24 12:39:17.248 [info] <0.12352.68>
 Starting RabbitMQ 3.7.4 on Erlang 20.2.3
 Copyright (C) 2007-2018 Pivotal Software, Inc.
 Licensed under the MPL.  See http://www.rabbitmq.com/
2018-08-24 12:39:17.248 [info] <0.12352.68>
 node           : rabbit@node-1
 home dir       : /var/lib/rabbitmq
 config file(s) : /etc/rabbitmq/rabbitmq.config
 cookie hash    : V5HwGpwX2Yp7nhd7tDRWzg==
 log(s)         : /var/log/rabbitmq/rabbit@mode-1.log
                : /var/log/rabbitmq/rabbit@node-1_upgrade.log
                : <stdout>
 database dir   : /opt/rabbitmq/mnesia/rabbit@node-1

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1682

### CODE REVIEW

**Comment by hairyhum** [comment]
I understand that the original assertion was there to fail if an operation fails on a live queue Pid.
This behaviour will retry the operation if it's failing and then fail with the `timeout` error.
Is there a way to make this behaviour better? Running it for 2000 times and then reporting `timeout` doesn't look less confusing than the failed assertion.

**Comment by lukebakken** [comment]
> I understand that the original assertion was there to fail if an operation fails on a live queue Pid.

Aha, I didn't realize that is the original intent. I will update my PR to produce a more helpful error than `badmatch`. I tried to dig into the history of that line of code but, due to the fact that `rabbit_amqqueue` has moved between several repos, I couldn't find the original commit.

**Comment by lukebakken** [comment]
@hairyhum do you think the following sequence of events could trigger the `badmatch`:

* `with/4` is called on a `stopped` _mirrored_ queue [here](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue.erl?utf8=%E2%9C%93#L480-L484)
* The thunk `F` fails, so we fall into the error handler [here](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue.erl?utf8=%E2%9C%93#L502-L512)
* During that time, the queue pid becomes active
* Since the queue is mirrored, we enter [this code block](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue.erl?utf8=%E2%9C%93#L508-L511), and trigger a `badmatch`

**Comment by hairyhum** [comment]
Maybe. Mirroring does some waiting to avoid false-positives. Unfortunately `F` is an arbitrary function so we don't know why it fails and it's not logged.

**Comment by michaelklishin** [comment]
@lukebakken's hypothesis sounds plausible to me.

**Comment by lukebakken** [comment]
We know that `retry_wait/4` is only called if `F` exits with one of these reasons:

```
noproc
noconnection
nodedown
normal
shutdown
```

Let me know what you think of 9d9f624c9622531849f4cd05a3689c33483a241c. I special-cased the scenario where the queue is mirrored and the pid is alive. Then, in the other case, rather than matching against `false` the error handler func is called.

**Comment by hairyhum** [comment]
The fact that `retry_wait` is not called for every failure makes me wonder what is the difference between mirrored master and non-mirrored queue process becoming available again? I thought that the handler is called on any error.

**Comment by lukebakken** [comment]
Another instance of this error: https://groups.google.com/d/topic/rabbitmq-users/u9URsZ2ova8/discussion

**Comment by lukebakken** [comment]
@hairyhum @michaelklishin @kjnilsson I'm not letting this one go! My latest change is simpler, and tries to do something sane where a crash would have happened.

**Comment by lukebakken** [comment]
Thanks for the review @hairyhum

**Comment by lukebakken** [comment]
Backported to `v3.7.x`

**Pull request merged**
