### PR TITLE
Collect tags from all authz backends

### PR DESCRIPTION
**Pull request by rtraschke**
Fix for issue https://github.com/rabbitmq/rabbitmq-server/issues/338

Have the authorisation code propagate tags into the user record.

A related change to the rabbitmq-auth-backend-ldap plugin propagates tags from there as well. That change also contains the test code. See https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/17

### CODE REVIEW

**Comment by michaelklishin** [comment]
So this changes one `authz` function signature but given that without it things cannot really work as advertised in the docs, I guess this can be considered to be a bug fix.

@gotthardp FYI.

**Comment by rtraschke** [comment]
Ah, shall I add the old 2-tuple version back into the callback list?

**Comment by michaelklishin** [comment]
@rtraschke yes, please. That would prevent authz plugins that don't really care/rely on tags from breaking.

**Comment by rtraschke** [comment]
Done.

**Pull request merged**
