### PR TITLE
Use more optimal default memory allocators where available (Erlang 20.2.3 or later)

### PR DESCRIPTION
**Pull request by essen**
## Proposed Changes

See [this rabbitmq-users thread](https://groups.google.com/d/msg/rabbitmq-users/LSYaac9frYw/LNZDZUlrBAAJ) for background.

We have settled on the following configuration for memory
allocators after testing many different combinations:

+MBas ageffcbf +MHas ageffcbf +MBlmbcs 512 +MHlmbcs 512 +MMmcs 30

They reduce the memory usage and help RabbitMQ reclaim memory,
at the cost of a slight decrease in performance due to an
increased number of memory operations.

We need to start Erlang with these values in order to figure
out whether they are supported. The allocator strategies we
recommend were introduced in Erlang/OTP 20.2.3. The values
can be overriden using RABBITMQ_SERVER_ERL_ARGS.

cc @gerhard

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)
- [x] Optimization (peak and median RAM consumption)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by essen** [comment]
@dumbbell Please give it a small look and tell me if we're going the wrong way about this.

I also have not been able to test on Windows (I wrote a small script testing for memory allocators, tested it and then incorporated it into rabbitmq-server.bat which I then didn't test, I'm hoping you have a CI environment for Windows).

**Comment by michaelklishin** [comment]
I tested it on 19.3 and 20.3, it works as expected. The effects of these allocators flag on actual workloads needs more research and user feedback.

**Comment by dumbbell** [comment]
The patch looks good and yes, we have Windows VMs in CI. However, I need to verify which version of Erlang we use there.

**Comment by dumbbell** [comment]
We use Erlang 20.0 on all Windows VMs. I need to figure out a way to test with at least two versions of Erlang, like we do for Linux.

**Comment by dumbbell** [comment]
My concern is mostly how I integrate that into Concourse configuration :-) Otherwise, we use a new Windows VM each time we do a Windows installer test and throw it away, so installing Erlang is not an issue.

**Comment by hairyhum** [comment]
Should it also be in `rabbitmq-service.bat`?

**Comment by gerhard** [comment]
Started testing this against various workloads, all having the following in common:

* [n1-highcpu-8](https://cloud.google.com/compute/pricing)
* Ubuntu 14.04.5 LTS  4.4.0-124-generic x86_64
* Erlang/OTP 20.3.6
* RabbitMQ v3.7.5
* perf-test v2.1.2
* 5 minute averages

## [ndq-autoack](https://github.com/rabbitmq/workloads/tree/master/ndq-autoack)

|  | Before | After |
|-|-|-|
| Messages/s | 55k | 56k |
| Memory | 81 MiB | 81 MiB |
| GC/s | 27K | 33K |

screen shot 2018-05-21 at 18 39 49 3

## [ndq-multiack](https://github.com/rabbitmq/workloads/tree/master/ndq-multiack)

## [ndq-10q-multiack](https://github.com/rabbitmq/workloads/tree/master/ndq-10q-multiack)

## [dq-3n-confirm-multiack](https://github.com/rabbitmq/workloads/tree/master/dq-3n-confirm-multiack)
 
## [lqs-ha-confirm-multiack ](https://github.com/rabbitmq/workloads/tree/master/lqs-ha-confirm-multiack )

**Comment by essen** [comment]
I have added the changes to `rabbitmq-service.bat`.

Should I work on a separate PR to include it in 3.6.16?

**Comment by michaelklishin** [comment]
@essen if we are certain those things are safe for R16B03 and 19.3 users (yes, we technically still allow running on R16B03, even though the docs say it is unsupported), please do. I produced an RC of 3.6.16 earlier today but we can include this into RC2.

**Comment by gerhard** [comment]
Even though we haven't benchmarked the impact of this on durable, mirrored or lazy queues, are the above benchmarks against non-durable queues sufficient to make a call whether this change is a good default?

**Comment by michaelklishin** [comment]
We haven't identified any meaningful (statistically significant) regressions with these new defaults and there's some empirical evidence on the mailing list that the new defaults make a big difference for some users. So I think we should adopt these changes.

**Comment by essen** [comment]
Woo!!

**Comment by gerhard** [comment]
Are we planning to merge this into 3.7.6?

How about 3.6.16? #1612

**Comment by michaelklishin** [comment]
It was cherry-picked to 3.7.6. We haven't done any 3.6.x testing yet. Also, our 3.7.x LRE runs OTP 20.1.7, so it would be cool to have that upgraded to 20.3.6 before 3.7.6 GA.

**Comment by gerhard** [comment]
I can look into that on Monday, the LRE deployments are very outdated at this point. Does anyone want to join the fun or should I Hans Solo it?

**Comment by michaelklishin** [comment]
If you bring your Millennium Falcon someone might join you :)

**Comment by gerhard** [comment]
I was wondering whether it would be worth mentioning in the release notes how to go back to the previous defaults, `+MBas aoffcbf +MHas aoffcbf +MBlmbcs 5120 +MHlmbcs 5120 +MMmcs 10`

**Comment by michaelklishin** [comment]
@gerhard good idea.

**Comment by michaelklishin** [comment]
#1612 was merged, currently a backport of this PR is on track to be included into 3.6.16.

**Pull request merged**
