### PR TITLE
Switch to kB, MB, GB (as opposed to kiB, MiB, GiB) in vm_memory_monitor where possible 

### LINKED ISSUE #1233: Log resource limits in kiB, MiB, GiB (as those are the limits we and other tools actually use)
When we do conversions to MB inside `vm_memory_monitor` we use [1 MiB (1048576 bytes)](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/vm_memory_monitor.erl#L46), as in the [log messages](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/vm_memory_monitor.erl#L225). But when we convert values such as the high watermark, we use [1MB (1000000 bytes)](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/rabbit_resource_monitor_misc.erl#L40).

Detected while testing https://github.com/rabbitmq/rabbitmq-server/issues/1224

### PR DESCRIPTION
**Pull request by dcorbacho**
Closes #1233

### CODE REVIEW

**Comment by michaelklishin** [comment]
There is a bunch of other places that imply mebibytes/gibibytes, e.g. https://github.com/rabbitmq/rabbitmq-server/blob/91fc8a18225ae72e104d9fab2578f7fe56bf8e96/src/vm_memory_monitor.erl#L364 and https://github.com/rabbitmq/rabbitmq-server/blob/91fc8a18225ae72e104d9fab2578f7fe56bf8e96/src/vm_memory_monitor.erl#L389.

Should also we switch other places to the currently defined IEC value of 1 kilobytes/megabyte/gigabyte?

**Comment by michaelklishin** [comment]
According to [Red Hat documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-proc-meminfo.html), `/proc/meminfo` actually reports values in kibibytes when it says "kilobyte". I wouldn't be surprised if more OS'es did the same. So this needs an investigation first.

**Comment by dumbbell** [comment]
> According to Red Hat documentation, /proc/meminfo actually reports values in kibibytes when it says "kilobyte". I wouldn't be surprised if more OS'es did the same. So this needs an investigation first.

I believe this is true for most cases. Historically, "kilobytes", "megabytes" and so on were used to qualify values base on power-of-two units. Only persistent storage device makers used SI units on their products. For instance a hard disk of 80 GB is exactly what it says: 80,000,000,000 bytes, unlike what people expected (80 x 1024 x 1024 x 1024 = 85899345920 bytes).

The power-of-two units were introduced in 1998 [1][2] and it took time for people to start to use them. Now, applications usually report the same power-of-two-based values but might have fixed the unit to display "kiB", "MiB", "GiB", ...

IMHO we should do the same: keep the power-of-two-based values and fix the unit we display or document, because nobody uses the power-of-ten values, even if the unit is spelled "MB".

[1] https://en.wikipedia.org/wiki/Mebibyte
[2] http://physics.nist.gov/cuu/Units/binary.html

**Comment by lukebakken** [comment]
FWIW, I always assume `MB` means `2^20` (the power-of-two value) unless docs say otherwise. I think the values should remain power-of-two (`kiB`, `MiB`, `GiB`) and if the power-of-ten abbreviations are displayed, they could be switched to the IEC abbreviations.

Check out the man page for `dd` as yet another example of potential confusion:

```
N and BYTES may be followed by the following multiplicative suffixes: c =1, w =2, b =512, kB =1000, K =1024, MB =1000*1000, M =1024*1024, xM =M, GB =1000*1000*1000, G =1024*1024*1024, and so on for T, P, E, Z, Y.
```

**Comment by michaelklishin** [comment]
We decided to not change the calculations and instead change the unit we display (to be MiB, GiB, etc) and log.

The reason for that was mentioned by @dumbbell in https://github.com/rabbitmq/rabbitmq-server/pull/1235#issuecomment-305731143: there is plenty of existing tools that use kibibytes, mebibytes, etc at the OS, filesystem, networking layers. Some tools (e.g. `/proc/meminfo`) claim to use kilobytes but actually use kibibytes.

Some monitoring tools (e.g. Data Dog) use MiB, GiB values as well. So switching to kB, MB, GB may end up making things more confusing, not less.

**Pull request closed without merging**
