### PR TITLE
Add rabbit_tracer boot step for running Looking Glass

### PR DESCRIPTION
**Pull request by essen**
Part of https://github.com/rabbitmq/rabbitmq-common/issues/198

It will run only if RABBITMQ_TRACER is defined. It contain a
list of M:F (for example RABBITMQ_TRACER="abc:def,ghi:jkl")
that are functions returning Looking Glass trace specifications.

This commit comes with one such function, rabbit_tracer:connections.
It will trace all existing and future connection processes across
all rabbit and rabbit_common applications.

More functions will need to be added to trace specific parts of
RabbitMQ, or to trace plugins. For example there could be functions
for tracing channels, or data collection for management. Trace
specifications can be combined to get the target you need.

An example usage follows:

    make run-broker RABBITMQ_TRACER="rabbit_looking_glass:connections"

In another shell:

    bin/runjava com.rabbitmq.perf.PerfTest

Then some time later stop the test and the node, then run:

    make profile
    qcachegrind

### CODE REVIEW

**Comment by essen** [comment]
This is an example function returning trace patterns: https://github.com/rabbitmq/rabbitmq-server/pull/1225/files#diff-9cd14a2bfbc44ba926e2fd2c4219e589R38

All patterns from Looking Glass can be set here so no extra changes will be necessary moving forward.

**Comment by essen** [comment]
After these PRs get merged some extra work will be necessary to add more functions for the various important parts of RabbitMQ and plugins.

**Comment by michaelklishin** [comment]
I do see `trace.lz4.*` files created in the server directory after stopping the node but `gmake profile` fails with an `undef`:

```
gmake profile
 GEN    profile
{"init terminating in do_boot",{undef,[{lz4_nif,lz4f_create_decompression_context,[],[]},{lg_file_reader,fold,3,[{file,"src/lg_file_reader.erl"},{line,20}]},{lg_callgrind,profile,3,[{file,"src/lg_callgrind.erl"},{line,76}]},{lg_callgrind,'-profile_many/3-lc$^1/1-1-',2,[{file,"src/lg_callgrind.erl"},{line,98}]},{lg_callgrind,profile_many,3,[{file,"src/lg_callgrind.erl"},{line,98}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]}]}}
init terminating in do_boot ()
```

**Comment by michaelklishin** [comment]
@essen we already have a module named `rabbit_trace` which has to do with message tracing.

I suggest that we rename `rabbit_tracer` to `rabbit_looking_glass_tracing`.

**Comment by essen** [comment]
I cannot reproduce these on a fresh master. It sounds like the lz4 app is a plugin in your environment, when it shouldn't be (that's what part of the rabbit-common patch prevents). I'm not sure what could be the issue.

I will rename the module in a few minutes.

**Comment by essen** [comment]
That one is done. I'll have some LG improvements tomorrow around noon that I couldn't finish tonight, got disturbed.

**Comment by michaelklishin** [comment]
I start a node with Looking Glass like so:

```
```

then run PerfTest or another way to generate some connection activity, then C-c the node.

The entire time I have 8 trace files in the working directory that are all empty:

```
deps/rabbit/ rabbitmq-common-198 ls -lha . | grep trace
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.1
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.2
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.3
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.4
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.5
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.6
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.7
-rw-r--r--    1 antares  staff     0B Jun 27 11:13 traces.lz4.8
```

@essen is this expected?

**Comment by michaelklishin** [comment]
I think now I know why, when PerfTest is running, the log is full of exceptions such as:

```
2017-06-27 11:23:32.088 [info] <0.380.0> accepting AMQP connection <0.380.0> (127.0.0.1:62440 -> 127.0.0.1:5672)
2017-06-27 11:23:32.136 [info] <0.380.0> connection <0.380.0> (127.0.0.1:62440 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
2017-06-27 11:23:32.167 [info] <0.405.0> accepting AMQP connection <0.405.0> (127.0.0.1:62441 -> 127.0.0.1:5672)
2017-06-27 11:23:32.174 [info] <0.405.0> connection <0.405.0> (127.0.0.1:62441 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
2017-06-27 11:23:32.900 [warning] <0.416.0> The on_load function for module lz4_nif returned:
{error,{load_failed,"Failed to load NIF library: 'dlopen(../lz4/priv/lz4_nif.so, 2): Library not loaded: /usr/local/lib/liblz4.1.dylib\n  Referenced from: /Users/antares/Development/RabbitMQ/umbrella.git/deps/lz4/priv/lz4_nif.so\n  Reason: image not found'"}}
2017-06-27 11:23:32.984 [error] <0.373.0> CRASH REPORT Process <0.373.0> with 0 neighbours crashed with reason: call to undefined function lz4_nif:lz4f_compress_frame(<<0,67,131,104,4,100,0,2,105,110,103,100,0,12,114,97,98,98,105,116,64,117,114,97,110,111,0,0,1,...>>, #{})
2017-06-27 11:23:32.985 [error] <0.368.0> Supervisor {<0.368.0>,lg_tracer_pool} had child {tracer,5} started with lg_file_tracer:start_link(5, "traces.lz4") at <0.373.0> exit with reason call to undefined function lz4_nif:lz4f_compress_frame(<<0,67,131,104,4,100,0,2,105,110,103,100,0,12,114,97,98,98,105,116,64,117,114,97,110,111,0,0,1,...>>, #{}) in context child_terminated
2017-06-27 11:23:33.042 [warning] <0.419.0> The on_load function for module lz4_nif returned:
{error,{load_failed,"Failed to load NIF library: 'dlopen(../lz4/priv/lz4_nif.so, 2): Library not loaded: /usr/local/lib/liblz4.1.dylib\n  Referenced from: /Users/antares/Development/RabbitMQ/umbrella.git/deps/lz4/priv/lz4_nif.so\n  Reason: image not found'"}}
2017-06-27 11:23:33.079 [error] <0.370.0> CRASH REPORT Process <0.370.0> with 0 neighbours crashed with reason: call to undefined function lz4_nif:lz4f_compress_frame(<<0,72,131,104,4,100,0,2,105,110,103,100,0,12,114,97,98,98,105,116,64,117,114,97,110,111,0,0,1,...>>, #{})
2017-06-27 11:23:33.079 [error] <0.368.0> Supervisor {<0.368.0>,lg_tracer_pool} had child {tracer,2} started with lg_file_tracer:start_link(2, "traces.lz4") at <0.370.0> exit with reason call to undefined function lz4_nif:lz4f_compress_frame(<<0,72,131,104,4,100,0,2,105,110,103,100,0,12,114,97,98,98,105,116,64,117,114,97,110,111,0,0,1,...>>, #{}) in context child_terminated
2017-06-27 11:23:33.630 [warning] <0.421.0> The on_load function for module lz4_nif returned:
{error,{load_failed,"Failed to load NIF library: 'dlopen(../lz4/priv/lz4_nif.so, 2): Library not loaded: /usr/local/lib/liblz4.1.dylib\n  Referenced from: /Users/antares/Development/RabbitMQ/umbrella.git/deps/lz4/priv/lz4_nif.so\n  Reason: image not found'"}}
2017-06-27 11:23:33.641 [error] <0.369.0> CRASH REPORT Process <0.369.0> with 0 neighbours crashed with reason: call to undefined function lz4_nif:lz4f_compress_frame(<<0,67,131,104,4,100,0,2,105,110,103,100,0,12,114,97,98,98,105,116,64,117,114,97,110,111,0,0,1,...>>, #{})
2017-06-27 11:23:33.642 [error] <0.368.0> Supervisor {<0.368.0>,lg_tracer_pool} had child {tracer,1} started with lg_file_tracer:start_link(1, "traces.lz4") at <0.369.0> exit with reason call to undefined function lz4_nif:lz4f_compress_frame(<<0,67,131,104,4,100,0,2,105,110,103,100,0,12,114,97,98,98,105,116,64,117,114,97,110,111,0,0,1,...>>, #{}) in context child_terminated
2017-06-27 11:23:35.681 [warning] <0.380.0> closing AMQP connection <0.380.0> (127.0.0.1:62440 -> 127.0.0.1:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection
2017-06-27 11:23:37.096 [warning] <0.405.0> closing AMQP connection <0.405.0> (127.0.0.1:62441 -> 127.0.0.1:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection
```

**Comment by essen** [comment]
OK first to be clear, you do not need to specify the PLUGINS variable. Just RABBITMQ_TRACER. LG cannot be loaded as a plugin since it is a NIF. The proper configuration is setup just by using RABBITMQ_TRACER.

Second is curious, let me try on an OSX environment (that's OSX right?).

**Comment by michaelklishin** [comment]
It is on OS X Sierra, I can try a Debian machine to compare.

**Comment by michaelklishin** [comment]
The shared library that can't be loaded by the node (`../lz4/priv/lz4_nif.so`) exists and contains the following:

```
nm -gU ../lz4/priv/lz4_nif.so
0000000000003370 S _atom__nif_thread_ret_
0000000000003378 S _atom_done
0000000000003380 S _atom_ok
00000000000016e0 T _dtor_LZ4F_cctx
0000000000001710 T _dtor_LZ4F_dctx
0000000000001560 T _load
0000000000001960 T _lz4_erlang_lz4f_compress_begin
0000000000001d40 T _lz4_erlang_lz4f_compress_end
0000000000001740 T _lz4_erlang_lz4f_compress_frame
0000000000001ac0 T _lz4_erlang_lz4f_compress_update
00000000000018a0 T _lz4_erlang_lz4f_create_compression_context
0000000000001e60 T _lz4_erlang_lz4f_create_decompression_context
0000000000001f40 T _lz4_erlang_lz4f_decompress
0000000000001c20 T _lz4_erlang_lz4f_flush
0000000000001f20 T _lz4_erlang_lz4f_get_frame_info
0000000000002750 T _nif_create_main_thread
0000000000002860 T _nif_destroy_main_thread
00000000000016d0 T _nif_init
00000000000024b0 T _nif_thread_call
0000000000002140 T _nif_thread_cast
0000000000003360 S _res_LZ4F_cctx
0000000000003368 S _res_LZ4F_dctx
00000000000016c0 T _unload
0000000000001690 T _upgrade
```

I tried re-cloning and rebuilding LZ4* and Looking Glass from scratch.

**Comment by essen** [comment]
You need to install the LZ4 library (`brew install lz4`).

**Comment by michaelklishin** [comment]
Indeed that was the root cause, sorry for the noise.

**Pull request merged**
