### PR TITLE
4.0: Remove classic mirrored queues

### PR DESCRIPTION
**Pull request by dcorbacho**
## Types of Changes
- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by ansd** [comment]
It looks like consumer argument `x-cancel-on-ha-failover` should have been deleted as part of this PR.

Likewise, MQTT connections don't need to perform failover for mirrored classic queues in https://github.com/rabbitmq/rabbitmq-server/blob/c67c940bcc5d14ff47ebc78e3d7203478ed734b4/deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl#L2000-L2004 anymore.

**Comment by michaelklishin** [comment]
Filed https://github.com/rabbitmq/rabbitmq-server/issues/11540 for those two.

**Comment by michaelklishin** [comment]
It is not entirely obvious to me, what the `rabbit_channel` of `x-cancel-on-ha-failover` should do now: always recover? For classic (no longer replicated) queues the choice is less obvious.

**Comment by ansd** [comment]
Copied from internal Slack:

> Channels should not try to re-register consumers.
> If the classic queue is down, consumption is stopped and the client gets notified.
> Likewise, MQTT connection should not try to re-consume. Instead, the MQTT connection will be terminated.
> I think it would be less confusing just to always cancel the consumer

**Pull request merged**
