### PR TITLE
#10330 /api/node/{node} should return 404 and not 500 when the node is not a cluster member

### LINKED ISSUE #10330: HTTP API request to `/api/nodes/{node_name}` where `{node_name}` isn't a valid RabbitMQ node fails with 500 error.
### Describe the bug

HTTP API request to `/api/nodes/{node_name}` where `{node_name}` isn't a valid RabbitMQ node fails with 500 error.

A 404 would be a more appropriate response.

### Reproduction steps

1. `curl -v http://localhost:15672/api/nodes/NOTANODENAME'`
2. observe 500 response code
3.
...

### Expected behavior

404 would be the expected response when a resource does not exist.

### Additional context

https://github.com/rabbitmq/rabbitmq-server/blob/9ff387e47363502d11f597dafb117841604ddacd/deps/rabbitmq_management/src/rabbit_mgmt_wm_node.erl#L74-L78

This function does not handle unknown node names correction, however the intire `resouce_exist` callback impl could be substantially optimised by just checking the the node is in `rabbit_nodes:list_members/0`

### PR DESCRIPTION
**Pull request by ikavgo**
## Proposed Changes

Fix #10330

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Review by kjnilsson — CHANGES_REQUESTED** [review]
How about just checking if the requested node in `resource_exists/2` is in `rabbit_nodes:list_members/0` ?

**Comment by ikavgo** [comment]
> How about just checking if the requested node in `resource_exists/2` is in `rabbit_nodes:list_members/0` ?

@kjnilsson since there is this pattern of not only checking resource existence but also loading it I chose the less invasive method.

:node/memory for example works differently - it indeed checks node exists first. Well, then it does it second time in to_json. So anyway, I'd really advise against further changes here unless we want to touch :node/memory too for at least some degree of uniformity.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
I agree that this is a more generic solution. Any attempt at generalize this likely would have to worry about these functions, or introduce new helpers and use them in `resource_exists/2` carefully everywhere where a certain type of resource is present in the list of `:param`s.

**Comment by michaelklishin** [comment]
At the same time, there are three modules that use this specific function:

``` erl
     {"/nodes/:node",                                          rabbit_mgmt_wm_node, []},
     {"/nodes/:node/memory",                                   rabbit_mgmt_wm_node_memory, [absolute]},
     {"/nodes/:node/memory/relative",                          rabbit_mgmt_wm_node_memory, [relative]},
     {"/nodes/:node/memory/ets",                               rabbit_mgmt_wm_node_memory_ets, [absolute]},
     {"/nodes/:node/memory/ets/relative",                      rabbit_mgmt_wm_node_memory_ets, [relative]},
     {"/nodes/:node/memory/ets/:filter",                       rabbit_mgmt_wm_node_memory_ets, [absolute]},
     {"/nodes/:node/memory/ets/:filter/relative",              rabbit_mgmt_wm_node_memory_ets, [relative]},
```

I'm giving extracting a new small "non-HTTP handler" module like we have for HSTS, for example.

**Comment by michaelklishin** [comment]
I've combined part of Ilya's work in this PR and @kjnilsson's suggestion in https://github.com/rabbitmq/rabbitmq-server/pull/10417.

**Pull request closed without merging**
