### PR TITLE
Use openssl.cnf config when generating new CSR

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Noticed in one of our environments running tests that has multiple openssl installations, the default one was used and not the one in the config file (as the config file was not used in this target generating the CSR). Noticed by  @alexnkdev

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [x] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution
you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@SimonUnge no objections from me but just for our collective understanding, what kind of side effects have stemmed from an incorrect `openssl.cnf` being picked up in this environment?

**Comment by alexnkdev** [comment]
@michaelklishin we have an internal environment where OpenSSL is consumed from external location. If openssl.cnf flag is not passed, it will be use the default one, this caused other tests to fail (that rely on certificates created by rabbitmq_ct_helper).

**Comment by michaelklishin** [comment]
@alexnkdev I understand what the end result is, mostly curious about what specifically is `openssl.cnf`-dependent in our tests. The majority of our TLS tests are fairly generic.

**Comment by michaelklishin** [comment]
Be that as it may, I do not have any objections to this changes, in particular if it allows you to run tests in more demanding or heavily tuned environments.

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
