### PR TITLE
See #5957. CLI cmd to generate hashed password from cleartext password

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Add cli cmd that generates a valid hashed password according to configured rabbitmq algorithm
Addresses cli cmd part of #5957 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ √] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Review by lukebakken — DISMISSED** [review]
Thank you!

**Comment by michaelklishin** [comment]
@SimonUnge can you please rebase this PR?

**Comment by SimonUnge** [comment]
> @SimonUnge can you please rebase this PR?

Done @michaelklishin

**Comment by michaelklishin** [comment]
We don't have to do this in this PR but one thing the community is guaranteed to ask for is support for password entry via standard input. See `rabbitmqctl change_passowrd` and `rabbitmqctl add_user` for examples of how we do it in other places.

**Pull request merged**
