### PR TITLE
Add vm_memory_calculation_strategy to cuttlefish schema

### LINKED ISSUE #1264: Add vm_memory_use_process_rss to cuttlefish schema
See #1223 and #1259

The setting should be added [in the schema for `3.7.0`](https://github.com/rabbitmq/rabbitmq-server/blob/master/priv/schema/rabbitmq.schema#L622-L684)

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1264 

Also adds a test for `memory_monitor_interval`

### CODE REVIEW

**Comment by lukebakken** [comment]
@michaelklishin I'll keep an eye on [this](https://github.com/rabbitmq/rabbitmq-server/pull/1259#issuecomment-308467425) and will update this PR accordingly.

**Comment by gerhard** [comment]
Config property has changed to `vm_memory_calculation_strategy` and can be `(rss|erlang)`: https://github.com/rabbitmq/rabbitmq-website/commit/970bca75d0b9866dbc54bb2e52e95459cae94ae8

**Comment by michaelklishin** [comment]
@lukebakken this needs a rebase against `master`.

**Comment by lukebakken** [comment]
@michaelklishin done!

**Pull request merged**
