### PR TITLE
mqtt_processor: Get local port from already available adapter_info

### PR DESCRIPTION
**Pull request by gomoripeti**
## Proposed Changes

This replaces `rabbit_net:socket_ends/2` which also tries to fetch peer
host and port. Fetching peer can return an error if the socket is
already closed (which used to crash the mqtt connection process). This
can happen after a resource alarm, when the processing of CONNECT frame
was delayed and the client closes the connection meanwhile.

```
** Reason for termination ==
** {{badmatch,{error,einval}},
    [{rabbit_mqtt_processor,process_login,4,
                            [{file,"rabbit_mqtt_processor.erl"},{line,585}]},
     {rabbit_mqtt_processor,process_request,3,
                            [{file,"rabbit_mqtt_processor.erl"},{line,143}]},
     {rabbit_mqtt_processor,process_frame,2,
                            [{file,"rabbit_mqtt_processor.erl"},{line,69}]},
     {rabbit_mqtt_reader,process_received_bytes,2,
                         [{file,"src/rabbit_mqtt_reader.erl"},{line,307}]},
```

Now the logs look as follows:
```
 [info] <0.303.0> vm_memory_high_watermark set. Memory used:130613248 allowed:171

 [debug] <0.871.0> MQTT accepting TCP connection <0.871.0> (127.0.0.1:53503 -> 127.0.0.1:21005)

 [info] <0.303.0> vm_memory_high_watermark clear. Memory used:130334720 allowed:6871947673

 [debug] <0.871.0> Received a CONNECT, client ID: "simpleClient" (expanded to "simpleClient"), username: undefined, clean session: true, protocol version: 3, keepalive: 90
 [debug] <0.871.0> MQTT vhost picked using plugin configuration or default
 [warning] <0.871.0> AMQP 0-9-1 client call timeout was 70000 ms, is updated to a safe effective value of 130000 ms
 [debug] <0.879.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
 [error] <0.871.0> MQTT: a socket write failed, the socket might already be closed
 [debug] <0.871.0> Failed to write to socket #Port<0.60>, error: badarg, frame: {mqtt_frame,
 [debug] <0.871.0>                                                               {mqtt_frame_fixed,
 [debug] <0.871.0>                                                                2,0,0,0},
 [debug] <0.871.0>                                                               {mqtt_frame_connack,
 [debug] <0.871.0>                                                                false,0},
 [debug] <0.871.0>                                                               undefined}
 [info] <0.871.0> accepting MQTT connection <0.871.0> (127.0.0.1:53503 -> 127.0.0.1:21005, client id: simpleClient)
 [info] <0.871.0> MQTT connection "127.0.0.1:53503 -> 127.0.0.1:21005" will terminate because peer closed TCP connection
 [debug] <0.871.0> MQTT: about to send will message (if any) on connection "127.0.0.1:53503 -> 127.0.0.1:21005"
 [debug] <0.906.0> Closing all channels from connection '127.0.0.1:53503 -> 127.0.0.1:21005' because it has been closed
```

Note: that the old behaviour had some benefits of failing fast, avoiding some administrative steps that are not necessary for an already closed connection (like registering client id with raft). However I think this "check" was rather implicit and accidental. Firstly the connection can get closed at every step and it does not make sense to check the connection before every function call. If such a check is deemed useful (makes sense when the connection is unblocked) I am happy to add one with an explicit comment.
 
## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by ansd** [comment]
Hey @gomoripeti, thank you.
The changes make sense to me.

> Note: that the old behaviour had some benefits of failing fast, avoiding some administrative steps that are not necessary for an already closed connection (like registering client id with raft). 

Yes, the resource alarm could be ongoing for some long time, and especially with MQTT there could be many clients connecting during that time. I think failing fast is better in that case.

I created a branch https://github.com/rabbitmq/rabbitmq-server/tree/mqtt-connack-timeout. What do you think?

The log on that branch looks like:
```
[info] <0.306.0> vm_memory_high_watermark set. Memory used:154554368 allowed:3435973
...
[debug] <0.887.0> MQTT accepting TCP connection <0.887.0> (127.0.0.1:55725 -> 127.0.0.1:1883)
...
[info] <0.306.0> vm_memory_high_watermark clear. Memory used:150700032 allowed:13743895347
...
[error] <0.887.0> MQTT protocol error on connection 127.0.0.1:55725 -> 127.0.0.1:1883: peername_not_known
```

**Review by ansd — COMMENTED** [review]
Hey @gomoripeti, thank you.
The changes make sense to me.

> Note: that the old behaviour had some benefits of failing fast, avoiding some administrative steps that are not necessary for an already closed connection (like registering client id with raft). 

Yes, the resource alarm could be ongoing for some long time, and especially with MQTT there could be many clients connecting during that time. I think failing fast is better in that case.

I created a branch https://github.com/rabbitmq/rabbitmq-server/tree/mqtt-connack-timeout. What do you think?

The log on that branch looks like:
```
[info] <0.306.0> vm_memory_high_watermark set. Memory used:154554368 allowed:3435973
...
[debug] <0.887.0> MQTT accepting TCP connection <0.887.0> (127.0.0.1:55725 -> 127.0.0.1:1883)
...
[info] <0.306.0> vm_memory_high_watermark clear. Memory used:150700032 allowed:13743895347
...
[error] <0.887.0> MQTT protocol error on connection 127.0.0.1:55725 -> 127.0.0.1:1883: peername_not_known
```

**Comment by gomoripeti** [comment]
thanks David, your changes look superior and all good

**Comment by ansd** [comment]
Thank you Péter, I opened https://github.com/rabbitmq/rabbitmq-server/pull/5655 (since I cannot push on your fork).

**Pull request closed without merging**
