### PR TITLE
Use separate colours for different queue types (and streams) in memory breakdown chart

### PR DESCRIPTION
**Pull request by ansd**
Before:
before

After:
after

### CODE REVIEW

**Comment by michaelklishin** [comment]
Should we change the label to say "Queues and Streams" then?

**Comment by ansd** [comment]
Sounds good:
queues-and-streams

Alternatively, we could also have separate colours for classic queue, quorum queue, and streams.

**Comment by michaelklishin** [comment]
@ansd that would be even better, assuming it is reasonably easy to do.

**Comment by ansd** [comment]
Color per queue type:
color-per-queue-type

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
