### PR TITLE
Wrap maybe function in quotes, so it is treated as an atom

### PR DESCRIPTION
**Pull request by robertoaloi**
## Proposed Changes

Since `maybe` is added as an optional keyword in OTP 25, quote its usage as an atom, so that it does not break syntax highlighting and other language service features.

## Types of Changes

What types of changes does your code introduce to this project?

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [X] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by mkuratczyk** [comment]
Thanks! Please note that we have a branch with OTP27 support where a similar (but different) change was already made: https://github.com/rabbitmq/rabbitmq-server/tree/otp27-support

I opted for a different name, since we already use it in some other places

**Comment by michaelklishin** [comment]
@mkuratczyk given that OTP 27 support will likely get into v3.13.x, I'm leaning towards keeping the `maybe` name. https://github.com/rabbitmq/rabbitmq-server/commit/7bf9af5256dbc9d635bd66d3a66eaa2a98fa421f uses `opt` but we have kept `maybe` for backwards compatibility when `rabbit_types:option/1` was introduced, IIRC.

**Comment by lhoguin** [comment]
The maybe type is referring to https://wiki.haskell.org/Maybe which is used across languages and projects.

**Comment by michaelklishin** [comment]
@lhoguin but so is `option` in `rabbit_types:option/1`. Java, Rust, Scala use `Option` for the same data type as Haskell's `Maybe`.

**Comment by michaelklishin** [comment]
@robertoaloi thank you. We may change it soon, most likely by switching to `rabbit_types:option/1` which was introduced for the same reason. But I see no harm in accepting this PR for now to unblock the continuous experimentation with EPL and the RabbitMQ codebase.

**Pull request merged**
