### PR TITLE
Fix combination of `amqqueue:get_pid/1` and `node/1`

### LINKED ISSUE #8746: Review use of `amqqueue:get_pid` and `node/1`
### Describe the bug

Related:
* #8564 
* #8595
* [VESC-1076](https://pivotal-esc.atlassian.net/browse/VESC-1076)

In [VESC-1076](https://pivotal-esc.atlassian.net/browse/VESC-1076), we see this stack trace:

```
Making sure data directory 'c:/Users/username/AppData/Roaming/RabbitMQ/db/rabbit@rabbitmq3-mnesia/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
     supervisor: {<0.7418.7>,rabbit_vhost_sup_wrapper}
     errorContext: start_error
     reason: {badarg,
                 [{erlang,node,
                      [{'%2F_Queue','rabbit@rabbitmq3'}],
                      [{error_info,#{module => erl_erts_errors}}]},
                  {rabbit_classic_queue,is_recoverable,1,
                      [{file,"rabbit_classic_queue.erl"},{line,120}]},
                  {rabbit_amqqueue,'-find_local_durable_queues/1-fun-10-',7,
                      [{file,"rabbit_amqqueue.erl"},{line,182}]},
                  {qlc,collect,1,[{file,"qlc.erl"},{line,1373}]},
                  {qlc,eval,2,[{file,"qlc.erl"},{line,301}]},
                  {mnesia_tm,non_transaction,5,
                      [{file,"mnesia_tm.erl"},{line,746}]},
                  {rabbit_amqqueue,mark_local_durable_queues_stopped,1,
                      [{file,"rabbit_amqqueue.erl"},{line,167}]},
                  {rabbit_vhost_process,init,1,
                      [{file,"rabbit_vhost_process.erl"},{line,49}]}]}
     offender: [{pid,undefined},
                {id,rabbit_vhost_process},
                {mfargs,{rabbit_vhost_process,start_link,[<<"/">>]}},
                {restart_type,permanent},
                {significant,false},
                {shutdown,300000},
                {child_type,worker}]
```

Note the `badarg`. This is due to assuming you can call `node/1` on the return value from `amqqueue:get_pid/1`

### Reproduction steps

N/A

### Expected behavior

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #8746

### CODE REVIEW

**Comment by lukebakken** [comment]
I'm sure there will be more places where this will have to be addressed.

**Comment by michaelklishin** [comment]
Oh, nice. I wasn't aware of `amqqueue:qnode/1`. Yes, we probably have more places to hunt down but we can do it one step at a time.

`rabbit_queue_master_location_misc:lookup_master/2` is one place that seems unsafe w.r.t. the queue leader (PID) type.

**Comment by michaelklishin** [comment]
Searching for `amqqueue:get_pid(Q` produces a good sample of code paths to review w.r.t. queue leader type safety.

**Comment by lukebakken** [comment]
> `rabbit_queue_master_location_misc:lookup_master/2` is one place that seems unsafe w.r.t. the queue leader (PID) type. Although that function is likely never used by QQs but we may want to be extra defensive anyway

Right, that's the question ... I think in this case, where a QQ should _never_ be in play, we could either:
* Continue to crash
* Catch and log the `badarg` (but how to recover?)
* Do something else?

I think that crashing is fine as long as it doesn't interrupt the boot sequence (as we see in VESC-1076) and can be recovered (even if that involves deleting and re-creating the queue).

**Comment by michaelklishin** [comment]
Agreed, for those scenarios we likely can only catch and log at best, in order to make the issue more visible.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Merging per verbal review from @kjnilsson.

**Comment by lukebakken** [comment]
Thanks @michaelklishin and @kjnilsson!!

**Pull request merged**
