### PR TITLE
Fixing RABBITMQ_CONFIG_ARG_FILE variable

### PR DESCRIPTION
**Pull request by Gsantomaggio**
The rabbit_prelaunch module can read the `os:getenv(RABBITMQ_CONFIG_ARG_FILE)` correctly

## Proposed Changes
With this PR the `rabbit_prelaunch` can read the variable [RABBITMQ_CONFIG_ARG_FILE](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/src/rabbit_prelaunch.erl#L92) correctly.

Found the bug (RMQ 3.7.11) while I was trying to set:

```
[
 {kernel, [
    {inet_dist_listen_min, 50000},
    {inet_dist_listen_max, 50000}
    ]}
].
```
on the `etc/rabbitmq/advanced.config` file, and did not work.

The `RABBITMQ_CONFIG_ARG_FILE` was not read and the [`rabbitmq-server script`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/scripts/rabbitmq-server#L208) always set the default values (`PRELAUNCH_RESULT` was always 0). 

[3.6.x had to do the same](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/scripts/rabbitmq-server#L81)

## Types of Changes

What types of changes does your code introduce to this project?

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by lukebakken** [comment]
@Gsantomaggio `advanced.config` is only read if `rabbitmq.conf` is also present. You can use `/etc/rabbitmq/rabbitmq.conf` to set those values ([schema](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.11/priv/schema/rabbit.schema#L1345-L1353)):

```
inet_dist_listen_min = 50000
inet_dist_listen_max = 50000
```

**Comment by Gsantomaggio** [comment]
@lukebakken thanks 
but I forgot to mention that:

```
$ cat etc/rabbitmq/rabbitmq.conf
vm_memory_high_watermark.relative = 0.3
inet_dist_listen_min = 50000
inet_dist_listen_max = 50000
```

*does not work* :)  this because of the `RABBITMQ_DIST_PORT` is assigned during the [`rabbit_prelaunch`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/scripts/rabbitmq-server#L190) 

In 3.6.x it worked because of the value was read directly to the [conf file](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/src/rabbit_prelaunch.erl#L77)

in 3.7.x is suppose to read [RABBITMQ_CONFIG_ARG_FILE](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/src/rabbit_prelaunch.erl#L92)

**Comment by lukebakken** [comment]
@Gsantomaggio - I can reproduce this, but the fix will have to take `rabbitmq.conf` into account somehow. Let me see what we can come up with.

**Comment by Gsantomaggio** [comment]
@lukebakken I think the same, I was focusing on the `advanced.config` because  I get this message:

```
Unable to update config for app kernel from a .conf file. The app is already running. 
Use advanced.config instead.
```

**Comment by lukebakken** [comment]
OK, since we generate config from `rabbitmq.conf` after the VM starts, we can't set these `kernel` values at that time. I'll take that into account too.

**Comment by lukebakken** [comment]
@Gsantomaggio I think your chance will suffice, but I'm doing some testing and will remove the settings from the `rabbit.schema` file. I'm also testing `net_ticktime` since I don't trust that it will work.

**Comment by lukebakken** [comment]
You can change `net_ticktime` after the VM starts, but not the dist ports. We would have to run `cuttlefish` as part of the startup scripts to support that.

Also see https://github.com/rabbitmq/rabbitmq-website/pull/687

Thanks @Gsantomaggio

**Comment by michaelklishin** [comment]
@Gsantomaggio please submit all future PRs against `master`.

**Comment by Gsantomaggio** [comment]
@michaelklishin I will.
I was looking for the `stable` branch, but I think you changed the repositories organization :)! 

@lukebakken 
I am going to remove[ this configuration](https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example#L514 
) from the `rabbitmq.conf.example` file

**Pull request merged**
