### PR TITLE
Khepri migration: upgrade #mirrored_sup_childspec{} records for shovel & federation

### PR DESCRIPTION
**Pull request by dcorbacho**
Khepri paths don't support tuples or records, so the key part of the  `#mirrored_sup_childspec{}` used by some plugins must be  transformed in a valid Khepri path during the migration from Mnesia to Khepri. `rabbit_db_msup_m2k_converter` iterates over all registered converters, which must implement `rabbit_mnesia_to_khepri_record_converter` behaviour callbacks.

Callbacks are declared through module attributes, such as:
```
-rabbit_mnesia_records_to_khepri_db(                                            
   [                                                                            
    {rabbit_db_msup_m2k_converter, ?MODULE}
   ]).
```

References https://github.com/rabbitmq/rabbitmq-server/pull/10004

For testing:

- Start a 2-node cluster in 3.11.18
- Declare shovel or federation links, i.e.
```
rabbitmqctl set_policy --apply-to exchanges federate-me "^amq\." '{"federation-upstream-set":"all"}'
rabbitmqctl set_parameter federation-upstream my-upstream '{"uri":"amqp://guest:guest@localhost:5672"}'
```
- Enable all feature flags
- Do a rolling upgrade to this patch
- Enable `khepri_db` feature flag

## Types of Changes
- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by gomoripeti** [comment]
great solution that I couldn't have come up with
note: there is also `rabbit_federation_queue_link_sup_sup` (sorry for commenting on an early draft and you already know)

**Review by michaelklishin — APPROVED** [review]

**Review by michaelklishin — CHANGES_REQUESTED** [review]
@dcorbacho looks like there is a legitimate build failure:

```
rabbit_federation_exchange_link_sup_sup.erl:13:14: can't find include lib "rabbit/src/mirrored_supervisor.hrl"
rabbit_federation_exchange_link_sup_sup.erl:42:16: record mirrored_sup_childspec undefined
rabbit_federation_exchange_link_sup_sup.erl:43:11: record mirrored_sup_childspec undefined
```

Reproducible for me with

```
bazel test //... --test_tag_filters="xref,dialyze"
```

**Comment by michaelklishin** [comment]
@dcorbacho please take a look at how I've resolved a couple of conflicts with `main`.

**Comment by michaelklishin** [comment]
@gomoripeti this is ready for your to test.

**Comment by michaelklishin** [comment]
```
  Proceeding with analysis...
rabbit_db_msup_m2k_converter.erl:69:12: The call rabbit_db_m2k_converter:with_correlation_id
         (fun((_) -> 'ok' | {'error', _}),
          State ::
              #rabbit_db_msup_m2k_converter{store_id :: atom(),
                                            record_converters ::
                                                [atom()]}) does not have an opaque term of type 
          rabbit_db_m2k_converter:state() as 2nd argument
rabbit_db_msup_m2k_converter.erl:84:1: Function delete_from_khepri/3 has no local return
rabbit_db_msup_m2k_converter.erl:100:12: The call rabbit_db_m2k_converter:with_correlation_id
         (fun((_) -> 'ok' | {'error', _}),
          State ::
              #rabbit_db_msup_m2k_converter{store_id :: atom(),
                                            record_converters ::
                                                [atom()]}) does not have an opaque term of type 
          rabbit_db_m2k_converter:state() as 2nd argument
 done in 0m8.56s
done (warnings were emitted)
```

is an outstanding Dialyzer failure.

**Comment by michaelklishin** [comment]
The issue seems to be with `rabbit_db_m2k_converter:with_correlation_id/2` using an opaque type for its argument, and `rabbit_db_msup_m2k_converter` tries to use it with a different module-specific state type.

**Comment by dcorbacho** [comment]
@michaelklishin Yesterday it was merged the change to use async commands to migrate Khepri records https://github.com/rabbitmq/rabbitmq-server/commit/b3313ad21e3a6a8f4aac9fbd3ccd5b21812365ee , and it changed `rabbit_db_m2k_converter` functions. Even though my changes seemed to rebase nicely, they are no longer working.

`copy_to_khepri` and `delete_to_khepri` used to receive the sub state for each module, but now they receive the global opaque state. @the-mikedavis how can we access the sub-state for each module implementing the converter? We store data we need in `rabbit_db_msup_m2k_converter`,  but it's an opaque type with no handling functions implemented. The API has changed and I'd say not having access to the state content is a bug.

**Comment by michaelklishin** [comment]
@dcorbacho @the-mikedavis using a regular (non-opaque) type may be our only option.

We can consider hiring the opaque part in a separate type/value stored in a special field, e.g. `impl`, and keep a map in the "transparent" part. I am not sure if having a field of an opaque type automatically renders the entire enclosing type opaque but at least we can try it.

**Comment by the-mikedavis** [comment]
Accessing the substates was originally part of https://github.com/rabbitmq/rabbitmq-server/pull/9646 but we removed it since no converters used it at the time. I'll add a commit that adds back the function that reads a sub state out of the opaque

**Review by the-mikedavis — APPROVED** [review]

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
