### PR TITLE
QQs: check if schema database record needs an update on tick

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Let QQ run `rabbit_quorum_queue:repair_amqqueue_nodes` on tick to repair potential membership discrepancy (RA members compared to amqqueue state members)

See #11029

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [x] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution
you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This can introduce a lot of CPU burn in clusters with thousands of quorum queues. Has the CPU impact of this been measured?

**Comment by lukebakken** [comment]
Relevant: https://github.com/rabbitmq/rabbitmq-server/issues/7863

**Comment by SimonUnge** [comment]
> This can introduce a lot of CPU burn in clusters with thousands of quorum queues. Has the CPU impact of this been measured?

Nope, but I will run some benchmark tests before final review!

**Comment by SimonUnge** [comment]
@kjnilsson Looking at the `repair_amqqueue_nodes`, what could perhaps be a bit costly is the `ra:members(Leader)` call, perhaps the members could be provided in the tick from RA itself? 

(there are of course costs in actually repairing too, but I would assume that a queue actually needs repairing is unusual, and that a lot of queues needing it even more so)

**Comment by kjnilsson** [comment]
> @kjnilsson Looking at the `repair_amqqueue_nodes`, what could perhaps be a bit costly is the `ra:members(Leader)` call, perhaps the members could be provided in the tick from RA itself?
> 
> (there are of course costs in actually repairing too, but I would assume that a queue actually needs repairing is unusual, and that a lot of queues needing it even more so)

The `ra_leaderboard` should have the current members which you can use to avoid the `ra:members/1` call back into the process.

**Comment by SimonUnge** [comment]
> > @kjnilsson Looking at the `repair_amqqueue_nodes`, what could perhaps be a bit costly is the `ra:members(Leader)` call, perhaps the members could be provided in the tick from RA itself?
> > (there are of course costs in actually repairing too, but I would assume that a queue actually needs repairing is unusual, and that a lot of queues needing it even more so)
> 
> The `ra_leaderboard` should have the current members which you can use to avoid the `ra:members/1` call back into the process.

Aha, I'll update the function to use that one instead.

**Comment by michaelklishin** [comment]
In other words, with the more efficient Ra leaderboard-based implementation we waste about 1% of the CPU with 10K quorum queues.

**Comment by SimonUnge** [comment]
0.5

> In other words, with the more efficient Ra leaderboard-based implementation we waste about 1% of the CPU with 10K quorum queues.

I wrote it a bit off, but it would be 0.5% CPU with 10k QQs in total (the 0.42 is part of the 0.53)

**Comment by michaelklishin** [comment]
@mergifyio backport v3.13.x

**Pull request merged**
