### PR TITLE
Backport #5726 (disk monitor resiliency improvements)

### PR DESCRIPTION
**Pull request by drencrom**
## Proposed Changes

Merging pull request #5726 to 3.9.x branch

We are seeing this issue in Ubuntu installations with rabbitmq 3.9 (Jammy and Kinetic) with `unknown` free disk space breaking `rabbitmqctl status` command.

### CODE REVIEW

**Comment by drencrom** [comment]
> Test suites fail to compile with

My fault. The pull request was missing one change to fix that.

**Comment by michaelklishin** [comment]
Now I wonder if #6614 should be backported to reduce the delta. Probably not.

**Comment by michaelklishin** [comment]
@pivotal-cla this is an obvious fix

**Comment by michaelklishin** [comment]
I get two failures locally from

``` shell
bazel test //deps/rabbit:disk_monitor_SUITE
```

They are

```
=== Location: [{erpc,call,702},
              {disk_monitor_SUITE,disk_monitor,[64](file:///private/var/tmp/_bazel_antares/25b268eeb499d77835ff5396f24e1d0d/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/deps/rabbit/disk_monitor_SUITE/test.outputs/outputs/ct_run.ct-rabbit-disk_monitor_SUITE@klishinm-a02.2022-12-12_21.57.23/deps.rabbit.disk_monitor_SUITE.logs/run.2022-12-12_21.57.24/disk_monitor_suite.src.html#64)},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {exception,
                     {badmatch,false},
                     [{disk_monitor_SUITE,disk_monitor1,1,
                          [{file,"disk_monitor_SUITE.erl"},{line,74}]}]}
  in function  erpc:call/5 (erpc.erl, line 702)
  in call from disk_monitor_SUITE:disk_monitor/1 (disk_monitor_SUITE.erl, line 64)
```

```
=== Location: [{erpc,call,702},
              {disk_monitor_SUITE,disk_monitor_enable,[78](file:///private/var/tmp/_bazel_antares/25b268eeb499d77835ff5396f24e1d0d/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/deps/rabbit/disk_monitor_SUITE/test.outputs/outputs/ct_run.ct-rabbit-disk_monitor_SUITE@klishinm-a02.2022-12-12_21.57.23/deps.rabbit.disk_monitor_SUITE.logs/run.2022-12-12_21.57.24/disk_monitor_suite.src.html#78)},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {exception,
                     {badmatch,false},
                     [{disk_monitor_SUITE,disk_monitor_enable1,1,
                          [{file,"disk_monitor_SUITE.erl"},{line,88}]}]}
  in function  erpc:call/5 (erpc.erl, line 702)
  in call from disk_monitor_SUITE:disk_monitor_enable/1 (disk_monitor_SUITE.erl, line 78)
```

If you haven't used Bazel to work on RabbitMQ before, please [take a look at this contributor guide](https://github.com/rabbitmq/contribute/wiki/Bazel-and-BuildBuddy).

**Pull request merged**
