### PR TITLE
Revert rabbitmq server 2308

### PR DESCRIPTION
**Pull request by lukebakken**
This PR will attempt to fix the flaky tests removed in #2308

### CODE REVIEW

**Comment by lukebakken** [comment]
@gerhard @dumbbell - the tests that continue to fail are not related to this PR. Thanks for the review.

**Comment by gerhard** [comment]
We started looking at this now with @dumbbell.

**Comment by dumbbell** [comment]
Finally merged, thank you!

**Comment by michaelklishin** [comment]
Should this be backported?

**Comment by gerhard** [comment]
Yes, [as soon as `master` checks pass](https://github.com/rabbitmq/rabbitmq-server/runs/667556355).

**Comment by dumbbell** [comment]
Backported to 3.8.x as part of rabbitmq/rabbitmq-server#2343.

**Pull request merged**
