### PR TITLE
fix search field for values containing spaces

### PR DESCRIPTION
**Pull request by luos**
Hi,

Currently when you search for an entity containing spaces the input will display the value incorrectly, cuts it at the first space, but the search does actually work. 

This fixes the display issue. 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
@luos I have a bunch of queues declared, some named "a b c {number}". When I search for "a b" everything seems to work as expected. So how can I reproduce?

**Comment by luos** [comment]
Hi, 

This is a display issue. The problem is that you put "a b" into the `input` after refreshing the page, it will only display "a". The search works anyway. 

I built `master` and the issue seemed to be present for me there as well.

**Review by michaelklishin — APPROVED** [review]
I could reproduce and verify that this PR is effective.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
