### PR TITLE
Read full message body at once when larger than 4MB

### LINKED ISSUE #11072: Optimise how rdq files are scanned at CQ shared message store recovery startup
### Is your feature request related to a problem? Please describe.

The symptom is that after an unclean shutdown when RabbitMQ starts up and runs recovery steps, its memory usage spikes to a seemingly unreasonable way. On smaller servers with let's say only 2GB of memory it causes an OOM (cyclic restarts and the node cannot start up). We have good reason to believe that it is the recovery of the classic queue shared storage, when it reads in all the rdq files, that is responsible for this behaviour. Although there are large rdq files, the total message size of "ready" messages in queues is 1 or 2 orders less than the memory used.

This issue was observer since years from time to time including on 3.12.x

### Describe the solution you'd like

I would like to get early feedback from the Core Team if it is worth investigating (we definitely see this issue often enough) and if contributions would be accepted.

The function [rabbit_msg_store:scan_file_for_valid_messages](https://github.com/rabbitmq/rabbitmq-server/blob/0175c804a26be6769d1f73d4d19fe998ca050d64/deps/rabbit/src/rabbit_msg_store.erl#L1385-L1457) is used to get the MsgIds and their offsets in the file, but at the same time also the message bodies are read in which are thrown away. This might lead to extra large binaries which are not used and extra garbage.

- First it needs to be investigated that indeed this function is the source of excessive memory usage.
- If proven implement a scanning which does not concatenate binaries, and does not create large, unused binaries (instead skipping message bodies)

Part of the problem could be the presence of unreferenced messages in rdq files which are not yet removed from the file. When a server manages to start up after a successful recovery, we've seen the size of the rdq files shrunk. The GC of unreferenced entries changed considerably in 3.13 where the msg store uses a compaction mechanism instead of combining two files. But still there were seen issues (https://github.com/rabbitmq/rabbitmq-server/discussions/10681), so I believe this change could be still relevant. The `scan_file_for_valid_messages` function is not just used at recovery time, but also during compaction and rdq deletion.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gomoripeti**
## Proposed Changes

When a message (much) larger than 4MB is read from an rdq file in `rabbit_msg_store:scan/6)` adjust the read size to the full message size instead of appending it together from 4MB chunks, which leaves a lot of garbage and memory fragmentation behind.

This patch is intentionally limited to 3.13.x. More major changes coming in 4.0 will make it unnecessary.

Closes #11072 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution
you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by gomoripeti** [comment]
failing khepri tests seem to be unrelated - some timeouts in stream and shovel tests

**Review by lhoguin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you. I trust your observations about lower GC pressure but just out of curiosity, what do the before/after numbers look like?

**Comment by lhoguin** [comment]
It's hard to get numbers for this but this helps avoid OOMs in memory constrained environments. It's a good workaround for 3.13 and a proper fix will be included in 4.0.

**Comment by gomoripeti** [comment]
yes, to clarify this change is about to reduce peak memory consumption, and not increasing speed or reducing cpu usage.
In a memory constrained env with a 105MiB message size the original function got OOM-killed with ~660MB RSS while for this patched version `/usr/bin/time -v` reported ~250MB maximum RSS.
I did not experiment with a lot more different sizes or a different server, and I did not fully understand how this looks from inside the Erlang VM (carriers) but tracing garbage_collection did hint at some differences (https://github.com/rabbitmq/rabbitmq-server/issues/11072#issuecomment-2098062224)

**Pull request merged**
