### PR TITLE
Continuously run powershell to get disk free space

### LINKED ISSUE #4140: Retrieving free disk space on Windows can time out
Reported here -

https://groups.google.com/g/rabbitmq-users/c/WwRMEs08MOo

Related to -
#3895
#3970
#3974

### PR DESCRIPTION
**Pull request by lukebakken**
Much faster than starting it every time.

Fixes #4140

### CODE REVIEW

**Comment by lukebakken** [comment]
Here's how I built the windows packages from Linux:

```
make FULL=1 RABBITMQ_PACKAGING_REPO="$HOME/development/rabbitmq/rabbitmq-packaging" UNIX_TO_DOS=unix2dos package-windows
```

I had to use `UNIX_TO_DOS` since I don't have the usual `todos` package.

Then, extract the zip file and start up RabbitMQ. In powershell, I did this:

Config file:

```
log.console = true
log.console.level = debug
log.file.level = debug
```

Commands:

```
$env:RABBITMQ_ALLOW_INPUT='true'
$env:RABBITMQ_CONFIG_FILE='C:\Users\bakkenl\conf\rabbitmq.conf'
.\sbin\rabbitmq-server.bat
```

In the interactive Erlang terminal, you can run the following to see that the free disk space has been retrieved:

```
rabbit_disk_monitor:get_disk_free().
```

You can bring up a program like Task Manager or Process Explorer to see the running powershell instance:

TODO

Go ahead and kill it and you will see it be restarted.

**Comment by dumbbell** [comment]
I tested this branch on a Windows 10 and it worked as advertised. Killing the PowerShell process also worked and `rabbit_disk_monitor:get_disk_free()` continued to report the correct value.

**Review by dumbbell — APPROVED** [review]
Well done! This is really cool

**Comment by lukebakken** [comment]
Thanks @dumbbell for the review!

**Comment by lukebakken** [comment]
@dumbbell @michaelklishin my next step was to look into `disksup` in Erlang/OTP itself. Currently, you can only enable disk monitoring down to the minute, BUT, if you start `os_mon`, look at what you can get:

```
Eshell V13.0.2  (abort with ^G)
1> os_mon_sysinfo:get_disk_info().
** exception exit: {noproc,{gen_server,call,[os_mon_sysinfo,get_disk_info]}}
     in function  gen_server:call/2 (gen_server.erl, line 367)
2> application:ensure_all_started(os_mon).
{ok,[sasl,os_mon]}
3> os_mon_sysinfo:get_disk_info().        
["C:\\ DRIVE_FIXED 720577376256 1013310287872 720577376256\n"
```

AHA! Much better than Powershell. It uses a port program called `win32sysinfo.exe`:

https://github.com/erlang/otp/blob/master/lib/os_mon/c_src/win32sysinfo.c

Expect an updated set of changes for free disk on Win32, and maybe even POSIX.

**Comment by inikulshin** [comment]
@lukebakken @michaelklishin is this PR (and https://github.com/rabbitmq/rabbitmq-server/pull/5241) planned to be merged into `3.9`?

**Pull request merged**
