### PR TITLE
Use powershell as a backup to handle.exe

### LINKED ISSUE #6613: Use powershell if handle.exe is missing or reports an error
Related issues:
* https://github.com/rabbitmq/rabbitmq-management-agent/issues/67
* https://github.com/rabbitmq/rabbitmq-management-agent/issues/90
* https://github.com/rabbitmq/rabbitmq-server/discussions/6612

The issue is that, for some Windows users, `handle.exe` sometimes does **not** output the data line starting with `File` that the stats monitor expects. We have no idea why this happens, and have not been able to reproduce it. However, you _can_ use Powershell to get the total number of handles for a process, which should be a "good enough" fallback.

Here is the output of each command on Windows 11, while I have PerfTest running with 10 consumers and producers:

```
(rabbit@bakkenl-z01)12> string:tokens(os:cmd("handle.exe /accepteula /nobanner /s /p " ++ os:getpid()), "\r\n").
["Handle type summary:","  <Unknown type>  : 2",
 "  <Unknown type>  : 119","  ALPC Port       : 8",
 "  Desktop         : 1","  Directory       : 2",
 "  Event           : 158","  File            : 62",
 "  IoCompletion    : 18","  IoCompletionReserve: 1",
 "  IRTimer         : 6","  Key             : 17",
 "  Mutant          : 2","  Process         : 3",
 "  Section         : 3","  Semaphore       : 8",
 "  Thread          : 23","  TpWorkerFactory : 3",
 "  WaitCompletionPacket: 15","  WindowStation   : 2",
 "Total handles: 453"]

(rabbit@bakkenl-z01)13> os:cmd("pwsh.exe -NoLogo -NoProfile -NonInteractive -Command (Get-Process -Id " ++ os:getpid() ++ ").Handles").
"453\r\n
```

When connections increase, the `File` count goes up (as expected) as do a couple others. But, it is linear, and gives a useful stat. Since the statistic is not used for alarms or rate-limiting RabbitMQ using this as a fallback seems reasonable.

@michaelklishin - thoughts?

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #6613

### CODE REVIEW

**Comment by lukebakken** [comment]
@michaelklishin turns out that Erlang uses `cmd.exe` when `os:cmd` is called to then run `powershell.exe`. Not all that efficient. I have code to execute `powershell.exe` directly via `open_port` ... should I do that in this PR as well?

**Comment by lukebakken** [comment]
@michaelklishin check this commit out, which runs Powershell directly -

https://github.com/rabbitmq/rabbitmq-server/pull/6614/commits/a40c682c001e8dff8f97fb3f63d1b79520c36dde

I did a lot of independent testing using [this code](https://github.com/lukebakken/misc/blob/main/erl/pwsh2.erl) and I'll be testing this branch on Windows a bit more before marking the PR as ready.

**Comment by lukebakken** [comment]
@michaelklishin all set.

**Comment by michaelklishin** [comment]
For some reason I could not build a Windows installer in a Linux VM but this looks good. I will merge and try the Concourse package before backporting.

**Comment by michaelklishin** [comment]
When I try to `gmake package-windows` the first time, it builds successfully but the second time I get a "filename mismatch" from a packaging target that does `unzip -q`.

I ended up testing this with [this alpha build](https://github.com/rabbitmq/rabbitmq-server-binaries-dev/releases/tag/v3.11.5-alpha.21). Works like a charm on a Windows host without `handle.exe`.

**Comment by lukebakken** [comment]
Ah, I think I've seen that. I always remove everything from the `PACKAGES` output directory before each run.

**Pull request merged**
