### PR TITLE
Create el6 and el7 rpm packages

### LINKED ISSUE #932: Add Fedora/RHEL/CentOS systemd service integration
Issue for the remaining work discussed in: https://github.com/rabbitmq/rabbitmq-server/pull/913

Specifically we need to make `make package-rpm` create noarch packages for el6 and el7:

### PR DESCRIPTION
**Pull request by kjnilsson**
Fixes #932 

This PR creates two new packaging targets: `package-rpm-rhel6` and `package-rpm-rhel7` that run rpmbuild as if it was run on a rhel machine in order to create `el6` and `el7` versions of the noarch rpm package. `el7` has systemd support.

`package-rpm` now calls the two new targets instead of `package-rpm-fedora` and generates both packages.

### CODE REVIEW

**Comment by camelpunch** [comment]
Does this mean we can continue building on Debian?

**Comment by kjnilsson** [comment]
@camelpunch yes

**Comment by dcorbacho** [comment]
The new packages seem good to me, built on Ubuntu and tested on Fedora. 👍

**Comment by kjnilsson** [comment]
Website PR: https://github.com/rabbitmq/rabbitmq-website/pull/251

**Pull request merged**
