### PR TITLE
CQv2: Consolidate index writes when possible

### PR DESCRIPTION
**Pull request by lhoguin**
This is done as an extra pass before giving the data
to file:pwrite. This should boost performance in most
cases, especially with large multi-acks.

While it provides a boost in the tested scenarios, I want a more thorough comparison before removing Draft status.

### CODE REVIEW

**Comment by mkuratczyk** [comment]
Great stuff! This PR improves the performance in all the tests I've run. 20-30% throughput improvement in most cases, and basically twice as good after turning off the consumers - on the `Messages Ready & Unacked` graph, you can see how much faster it reached the max length and how much faster the queues were emptied after turning consumers back on but publishers off.

Not directly related to this change but worth nothing how much more predictable lazy queues are - lower memory usage AND in most cases - the same (or even higher!) and more stable throughput.

pr4400

**Comment by michaelklishin** [comment]
I assume you mean lazy CQv2s are more predictable in terms of throughput stability compared to non-lazy CQv2s, not other queue types :)

**Comment by mkuratczyk** [comment]
@michaelklishin I'd say it applies more broadly. For example this is CQv1 lazy (yellow) and non-lazy (green). There are moment when non-lazy has a bit higher throughput but I'd take lazy any day (for this workload at least).

cqv1

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@mkuratczyk yes, we have seen this with CQv1. I thought you were comparing CQv2 with quorum queues.

**Pull request merged**
