### PR TITLE
Add rabbitmq-diagnostics remote_shell

### PR DESCRIPTION
**Pull request by lhoguin**
## Proposed Changes

A new command `rabbitmq-diagnostics remote_shell` to make it simpler to get a remote shell on RabbitMQ nodes for debugging sessions.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

The tests I added work but I have failures for some other (unrelated?) tests. Elixir is a bit confusing to me.

Should we add documentation?

/cc @gerhard @mkuratczyk

### CODE REVIEW

**Comment by lhoguin** [comment]
Example:

```
rabbitmq-diagnostics remote_shell
Starting a shell on node rabbit@lhoguin-a01... Press 'Ctrl+G' then 'q' to exit.
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.1.8  (abort with ^G)
(rabbit@lhoguin-a01)1> process_info(whereis(rabbit), dictionary).
{dictionary,[{{xtype_to_module,headers},
              rabbit_exchange_type_headers},
             {{xtype_to_module,direct},rabbit_exchange_type_direct},
             {{xtype_to_module,fanout},rabbit_exchange_type_fanout},
             {rand_seed,{#{bits => 58,jump => #Fun<rand.3.47293030>,
                           next => #Fun<rand.0.47293030>,type => exsss,
                           uniform => #Fun<rand.1.47293030>,
                           uniform_n => #Fun<rand.2.47293030>},
                         [51467459169805431|101182786376611961]}},
             {guid,{{4042169566,2524327178,1318607056,3937215805},0}},
             {{xtype_to_module,topic},rabbit_exchange_type_topic}]}
```

**Review by michaelklishin — APPROVED** [review]

**Review by michaelklishin — CHANGES_REQUESTED** [review]
This should handle a couple more failure scenarios:

 * An attempt to connect to a running node does not seem to be triggering a clean exit, the only way to terminate the CLI process is Ctrl-C
 * When I shut down the node I have a remote shell to, the only way to terminate the process is Ctrl-C

**Comment by lhoguin** [comment]
You should be able to terminate via `Ctrl+G q` in all cases. (Ctrl+C will leave some terminals in a bad state. It's an old issue, see https://github.com/erlang/otp/issues/3150.)

The problem is that remote shells do not exit on their own when the connection failed, or when the remote node exited, or in any other error scenario. Remote shells are implemented via the `user_drv -> user -> shell` sets of processes. Those are not proper OTP processes. We could find what pid the `shell` process we start has and exit when it does, but the only way to get to the `shell` pid is via links.

Additionally, it is possible to open multiple shells (remote or otherwise) in the same `rabbitmq-diagnostics remote_shell` call after the initial shell was opened by `rabbitmq-diagnostics`. I am not sure that exiting when the initial shell is gone is the right move since that would deviate from Erlang developers expectations about remote shells.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request merged**
