### PR TITLE
Remove pre-virtual_host_metadata feature flag compatibility code

### PR DESCRIPTION
**Pull request by dumbbell**
This feature flag was introduced because a new field was added to the `#vhost{}` record. This was a breaking change the feature flag allowed a RabbitMQ cluster to be upgraded one node at a time, without having to stop the entire cluster.

The compatibility code is in the wild for long enough that we want to support the new `#vhost{}` record only from now on. The
`virtual_host_metadata` feature flag was marked as required in a previous commit (see #5202). This allows us to remove code in this patch.

References #5215.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@mergifyio backport v3.11.x

**Comment by dumbbell** [comment]
@Mergifyio backport v3.11.x

**Comment by dumbbell** [comment]
Mergify can't recreate a new backport, so I will do it manually.

**Comment by dumbbell** [comment]
The backport was repeated in #5435.

**Pull request merged**
