### PR TITLE
By @LoisSotoLopez: Exclude policy_repair QQ test on mixed versions

### PR DESCRIPTION
**Pull request by michaelklishin**
This is #12665 by @LoisSotoLopez. References #12412.

### CODE REVIEW

**Comment by mkuratczyk** [comment]
If possible, the test condition should not be "if it's a mixed version test" but something specific to 4.0-4.1 upgrade.
Once mixed version tests run 4.1-4.2 or anything beyond, it should run without further actions (performing which we are likely to forget)

**Comment by michaelklishin** [comment]
@mkuratczyk you are right but we do not have such a mechanism in CT helpers. And some of our team members have discussed revisiting such excluded tests for 4.1.x specifically, so I think we won't necessarily forget about them.

**Comment by michaelklishin** [comment]
Given that the majority of such excluded tests can be re-enabled when a release series rolls over, I don't think we necessarily need an exclusion mechanism for a specific part of versions.

There are so many build system-related changes going on that I'd rather not try to introduce it in the next few months.

**Comment by michaelklishin** [comment]
Per discussion on the team: we will have to revisit such checks after every release, because in a (future) 4.1/4.0 combination, this test would pass and can be run in mixed version mode.

In the future we will likely support N-2 upgrades (this is not a promise of delivery but just an idea on the team), in which case we'd need new helpers that detect/exclude specific combinations of release series, e.g. 4.1.x and 3.13.x but not 4.1.x and 4.0.x.

**Pull request merged**
