### PR TITLE
MQTT machine versions backward compatibility

### PR DESCRIPTION
**Pull request by kjnilsson**
The previous version of this PR did not include backwards compatibility of the state machine.

### CODE REVIEW

**Comment by kjnilsson** [comment]
actually it's not quite ready yet, still working on it.

**Comment by carlhoerberg** [comment]
Ok, should i give it a spin or not yet?

**Comment by kjnilsson** [comment]
> Ok, should i give it a spin or not yet?
Maybe hold until I can update, the state conversion from old to new isn't quite there yet. Thanks.

**Comment by kjnilsson** [comment]
> Ok, should i give it a spin or not yet?

Ok should be good for a test now, I just wanted to make sure I had something covered which I now realise I already had. Sorry about confusion.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request merged**
