### PR TITLE
Quote -conf_dir/-conf_schema_dir path variables

### LINKED ISSUE #1104: Quote -conf_dir/-conf_schema_dir path variables in server/service.bat
There are a few path variables within rabbitmq-server.bat and rabbitmq-service.bat that aren't quoted, so if there is a space within the path, it would break execution.

### PR DESCRIPTION
**Pull request by Jakauppila**
Fixes #1104

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by Jakauppila** [comment]
Do you like to have associated issues for PRs even when they're something small like this? Or is just the PR fine?

**Comment by michaelklishin** [comment]
They are perfectly fine.

**Comment by michaelklishin** [comment]
Err, a PR alone would have been just fine :)

**Pull request merged**
