### PR TITLE
Create rabbitmq.config on windows installation

### LINKED ISSUE #659: Config is not used by windows service if not present during installation.
If `rabbitmq.config` file doesn't exist during windows service installation, it will not be used when created, even after service restart.  
It makes sense to create file during installation if it doesn't exist.

### PR DESCRIPTION
**Pull request by hairyhum**
Fixes #659

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
I made two tests

1. Setup using the standard configuration and the `rabbitmq.config`is located inside the folder `C:\Users\gabriele\AppData\Roaming\RabbitMQ\`.  **OK**


2.  removed all and reinstalled the setup using `RABBITMQ_BASE`as `c:\test_rmq` and the file `rabbitmq.config` has been created inside  `C:\Users\gabriele\AppData\Roaming\RabbitMQ\`

```
=INFO REPORT==== 3-Mar-2016::16:14:25 ===
node           : rabbit@windowsdev
home dir       : C:\Windows
config file(s) : c:/test_rmq/rabbitmq.config (not found)
```
In this case the file should be created inside `c:/test_rmq/`, isn't it ?

**Comment by hairyhum** [comment]
@Gsantomaggio installer has no information about `RABBITMQ_BASE`. Maybe file creation should be moved to `rabbitmq-service.bat`?

**Comment by Gsantomaggio** [comment]
@hairyhum Yes I think it should be moved.

I'd add that when `RABBITMQ_BASE`is configured the directory `AppData\Roaming\RabbitMQ` shouldn't be created.

Even if `RABBITMQ_BASE`is configured,  the setup creates:

```
Directory di C:\Users\gabriele\AppData\Roaming\RabbitMQ

03/03/2016  16:14    <DIR>          .
03/03/2016  16:14    <DIR>          ..
03/03/2016  16:14    <DIR>          db
03/03/2016  16:14    <DIR>          log
```
The directories are empty.

**Comment by Gsantomaggio** [comment]
@hairyhum what do you think ?

**Comment by hairyhum** [comment]
@Gsantomaggio  In theory it's possible to consider `RABBITMQ_BASE` during installation, but it's not about this issue, I guess.
It still can be discussed here: https://github.com/rabbitmq/rabbitmq-server/issues/626

**Comment by Gsantomaggio** [comment]
@hairyhum I got it, thanks. 
I'd move the file creation to `rabbitmq-service.bat` to close the this issue. 

For the other points I will refer to the #626

**Comment by Gsantomaggio** [comment]
`echo []. > !RABBITMQ_CONFIG_FILE!.config` raises `The system cannot find the path specified.` if the variable `RABBITMQ_CONFIG_FILE`  points to a directory that does not exist.

I tried leaving the default configuration and setting  `RABBITMQ_CONFIG_FILE=C:\test_pull660_1\test_file_conf`, where  `C:\test_pull660_1\` does not exist. I got the error during the setup, and the error inside the log:
`config file(s) : c:/test_pull660_1/test_file_conf.config (not found)`

I read the [comment](https://github.com/rabbitmq/rabbitmq-server/commit/5d0c0c7932cc43dc8387baccdf9a7d5046ee8ac2#diff-d0fc4e42f493273ee25c52fd15d7149bR135), I want to be sure that this is the expected behavior or we should try to create the directory as we do for [RABBITMQ_BASE](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-659/scripts/rabbitmq-env.bat#L56)

**Comment by hairyhum** [comment]
I thought that file directory should exist for default file location. We can try to create directory for this file, but I don't know how to get directory for non-existent file in CMD.

**Comment by Gsantomaggio** [comment]
> `RABBITMQ_CONFIG_FILE`  is The path to the configuration file.

I think that most of the users use the default configuration or they change `RABBITMQ_BASE`.

So, we have two options:

1. Ignore this case, and we suppose that who changed this setting knows what is doing.
2. Find a way to create the directory form. 

Except for this particular situation, the setup works correctly now.

**Comment by hairyhum** [comment]
The initial idea was to make default installation work with default config file location, so I think we can ignore this case.

**Comment by dls314** [comment]
@Gsantomaggio, @hairyhum do you know if there is/was another issue about having the installer use environment values for RABBITMQ_HOME?

I'm glad for this discussion regardless, I just spent a bit finding out/confirming that it doesn't :-\

**Comment by Gsantomaggio** [comment]
@dls314 do you mean  `RABBITMQ_BASE` in Windows ?

maybe this https://github.com/rabbitmq/rabbitmq-server/issues/433

**Comment by dls314** [comment]
@Gsantomaggio I do mean in Windows. Eventually I installed the service by hand to fix my problems and unchecked those options (services and links in the start menu) from the installer.

I'll spin up a new issue I think, #443 seems to be more about the plugins and batch files, and they all seem to work correctly.

**Pull request merged**
