### PR TITLE
rabbit_msg_store: Accept duplicate writes from the same queue

### PR DESCRIPTION
**Pull request by dumbbell**
The situation is this one: if for some reason (i.e. a bug) a queue has the same message referenced twice (or more) in its index and this message is eligible for the message store (as opposed to being entirely stored in the queue index), it will send it multiple times to the message store.

Until now, the code of the message store had two assertions:
* one verified in the context of the queue process to make sure there was no two writes or two removes in a row;
* one verified in the context of the message store process, doing exactly the same.

Consider the following order of events:
1. the queue sends the first copy to the message store
2. the message store handles the first copy
3. the queue sends the second copy to the message
4. the message store handles the second copy

In this scenario, none of the assertions are triggered and the message goes through the message store as if it was coming from different queues (i.e. a fan-out use case).

Now consider this order of events:
1. the queue sends the first copy to the message store
2. the queue sends the second copy to the message store
3. the message store handles the first copy

This time, the code will hit both assertions, leading to the crash of the queue, the crash of the message store and as a consequence, the crash of the entire vhost.

In the case of two consecutive writes, those assertions are useless because the message store already knows how to handle multiple copies of the same message. However, the consequence are catastrophic: a single queue with a duplicate message could take down an entire vhost.

This patch relaxes the assertion in the case of two consecutive writes. Now, both scenarii described above will be consistent: the copies from the same queue will be handled as any copies and the message store and the vhost will continue to work as usual.

Note that this patch doesn't cover the reason why there were multiple copies in the queue in the first place! So the initial reason for this to happen is still there lurking somewhere. The user who saw this problem had duplicate messages in a dead-letter queue. Perhaps something related to the lack of publisher-confirms between the initial queue and the dead-letter one?

### CODE REVIEW

**Comment by dumbbell** [comment]
There is no testcase associated with this change unfortunately. We have no way to reproduce the situation reliably.

I modified the code of RabbitMQ to explicitely trigger that scenario:
1.  I duplicated the call to `client_update_flying()`:
    ```erlang
    client_write(MsgId, Msg, Flow,
                 CState = #client_msstate { cur_file_cache_ets = CurFileCacheEts,
                                            client_ref         = CRef }) ->
        file_handle_cache_stats:update(msg_store_write),
        ok = client_update_flying(+1, MsgId, CState),
        ok = update_msg_cache(CurFileCacheEts, MsgId, Msg),
        ok = server_cast(CState, {write, CRef, MsgId, Flow}),
        %% Code duplicated below:
        ok = client_update_flying(+1, MsgId, CState),
        ok = update_msg_cache(CurFileCacheEts, MsgId, Msg),
        ok = server_cast(CState, {write, CRef, MsgId, Flow}).
    ```
2.  I added a 200ms pause in the message store process:

    ```erlang
    handle_cast({write, CRef, MsgId, Flow},
                State = #msstate { cur_file_cache_ets = CurFileCacheEts,
                                   clients            = Clients,
                                   credit_disc_bound  = CreditDiscBound }) ->
        timer:sleep(200),
        %% (...)
        ```

**Comment by lukebakken** [comment]
Is it worth logging this exceptional case?

**Comment by lhoguin** [comment]
We discussed adding a log line and decided against. We changed the implementation to make this "not a bug" for the time being. In the future we will measure and most likely remove this optimisation entirely. The optimisation predates many many changes to CQs such as embedded messages and additional optimisations to avoid writing to disk. It was introduced in https://github.com/rabbitmq/rabbitmq-server/commit/b78a8db06e81908db2d2ed75dc0f5eaae54f37f1 (this says it's a second try so it probably originates from even earlier). So it is highly likely that this optimisation just adds complexity for little to no return in performance.

**Comment by lhoguin** [comment]
It would still be useful to figure out what makes it possible for a (dead letter) queue to have 2 identical messages but the log line is unlikely to tell us why it happened. I think this is a scenario where a property based suite has the more chances of catching the problem.

**Comment by lukebakken** [comment]
@lhoguin I appreciate the backstory.

**Pull request merged**
