### PR TITLE
Queue length limit by byte size and number of messages (Drop head only)

### PR DESCRIPTION
**Pull request by dcorbacho**
By length and byte size
Only drop-head overflow strategy
Existing max length tests for classic queues run now on all queue types

[#161247380]

## Types of Changes
- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Merged per discussion with @kjnilsson. There will be another leg of the length limit work, so any new findings in this area can still be addressed.

**Comment by kstreichergb** [comment]
Is there any ETA on when reject-publish will become available?

**Comment by michaelklishin** [comment]
@kstreichergb it [already is](https://www.rabbitmq.com/maxlength.html#definition-using-x-args).

**Comment by kstreichergb** [comment]
@michaelklishin sorry, I've not been precise enoguh. I meant: When it will become available for quorum queues, the [documentation](https://www.rabbitmq.com/quorum-queues.html) lists drop-head only
image

**Comment by michaelklishin** [comment]
Possibly never.

**Pull request merged**
