### PR TITLE
Handle undefined args case

### LINKED ISSUE #2668: Handle the case where definitions.json file is missing expected queue arguments
Reported in this `rabbitmq-users` discussion:

https://groups.google.com/g/rabbitmq-users/c/izPLZUYQqEY

To reproduce, use the attached files:

[arguments-missing-definitions-crash-izPLZUYQqEY.zip](https://github.com/rabbitmq/rabbitmq-server/files/5631526/arguments-missing-definitions-crash-izPLZUYQqEY.zip)

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #2668

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lukebakken would it be worth adding a new [test case [file]](https://github.com/rabbitmq/rabbitmq-server/tree/master/deps/rabbit/test/definition_import_SUITE_data) for?

**Comment by lukebakken** [comment]
Ah! Forgot about that cool feature. On it.

**Comment by lukebakken** [comment]
@michaelklishin done

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request merged**
