### PR TITLE
queue limit per node

### PR DESCRIPTION
**Pull request by SimonUnge**
if anyone would like to look at the code for any crazyness, please point it out. I would specifically want a pointer on better way to count queues per node. Counters maybe?
## Proposed Changes

As per discussion https://github.com/rabbitmq/rabbitmq-server/discussions/10748

Added hard limit check for queues per node, with the following logic:

Exclusive queues
Regardless of type (classic, classic mirror, QQ, Stream...), if the limit is reached on the node that receives the declaration request, the request is denied, and the CONNECTION is terminated.

Non Exclusive queues
For QQ, Stream and Classic MIRROR Queue: If the limit is reached on the node that receives the declaration request, the request is denied with the CHANNEL terminated.

For Classic Queue that is NOT mirrored: If the limit is reached on the node that receives the declaration request, see if any other node in the cluster has capacity. If yes, redirect the declaration to that node. If no, the request is denied with the CHANNEL terminated.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [x] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by mkuratczyk** [comment]
I will leave some comments as I play around with this PR.

First, a formatter crash when the limit is reached while importing definitions (https://github.com/rabbitmq/sample-configs/blob/main/queues/100k-classic-queues.json):
```
reason: {error,badarg,
            [{io_lib,format,
                 ["Definition import: a work pool operation has thrown an exception ~st, stacktrace: ~p",
                  [{amqp_error,precondition_failed,
                       "cannot declare queue 'q92101': queue limit on every node is reached.",
                       none},
                   [{rabbit_misc,protocol_error,1,
                        [{file,"rabbit_misc.erl"},{line,290}]},
                    {rabbit_mirror_queue_misc,initial_queue_node,2,
                        [{file,"rabbit_mirror_queue_misc.erl"},
                         {line,613}]},
                    {rabbit_classic_queue,declare,2,
                        [{file,"rabbit_classic_queue.erl"},{line,85}]},
                    {rabbit_definitions,
                        '-do_concurrent_for_all/2-fun-1-',3,
                        [{file,"rabbit_definitions.erl"},{line,664}]},
                    {worker_pool_worker,handle_cast,2,
                        [{file,"worker_pool_worker.erl"},{line,113}]},
                    {gen_server2,handle_msg,2,
                        [{file,"gen_server2.erl"},{line,1056}]},
                    {proc_lib,wake_up,3,
                        [{file,"proc_lib.erl"},{line,251}]}]]],
                 [{file,"io_lib.erl"},{line,189}]},
             {rabbit_logger_text_fmt,format,2,
                 [{file,"rabbit_logger_text_fmt.erl"},{line,15}]}]}
```

**Comment by mkuratczyk** [comment]
I imported 1k-classic-queues.json to a 3-node cluster with `queue_max_per_node.hard_limit = 400`  set and the result is this:
```
> rabbitmqctl -n rabbit-1 list_queues pid | rg rabbit- | sed 's/@.*//' | sort | uniq -c
 402 <rabbit-1
 406 <rabbit-2
 192 <rabbit-3
```

First - the limit is slightly exceeded. I think that's due to the parallel nature of the import and personally I think that's ok. On the other hand, I'm sure sooner or later someone will complain, or at least ask about it.

More importantly, I'd argue that once the limit is exceeded, we should probably randomize placement between the nodes with available capacity, so that the outcome would be more like 400:300:300.

**Comment by mkuratczyk** [comment]
streams seem to be completely broken when using a cluster (works with single node). When I run `stream-perf-test`, with no arguments, it declares the stream and tries to establish a connection but it's just looping between handshake states:
```
2024-05-08 15:14:13.182827+02:00 [debug] <0.1443.0> Transitioned from tcp_connected to peer_properties_exchanged
2024-05-08 15:14:13.183950+02:00 [debug] <0.1443.0> Transitioned from peer_properties_exchanged to authenticating
2024-05-08 15:14:13.184190+02:00 [debug] <0.1443.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2024-05-08 15:14:13.184237+02:00 [debug] <0.1443.0> Transitioned from authenticating to authenticated
2024-05-08 15:14:13.185105+02:00 [debug] <0.1443.0> Tuning response 1048576 60
2024-05-08 15:14:13.185202+02:00 [debug] <0.1443.0> Transitioned from tuning to tuned
2024-05-08 15:14:13.185221+02:00 [debug] <0.1443.0> Open frame received for /
2024-05-08 15:14:13.185265+02:00 [debug] <0.1443.0> sending open response ok /
2024-05-08 15:14:13.185286+02:00 [debug] <0.1443.0> Checking token expiry
2024-05-08 15:14:13.185302+02:00 [debug] <0.1443.0> Transitioned from tuned to opened
2024-05-08 15:14:13.202961+02:00 [debug] <0.1449.0> Transitioned from tcp_connected to peer_properties_exchanged
2024-05-08 15:14:13.204244+02:00 [debug] <0.1449.0> Transitioned from peer_properties_exchanged to authenticating
2024-05-08 15:14:13.204536+02:00 [debug] <0.1449.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2024-05-08 15:14:13.204588+02:00 [debug] <0.1449.0> Transitioned from authenticating to authenticated
2024-05-08 15:14:13.205543+02:00 [debug] <0.1449.0> Tuning response 1048576 60
2024-05-08 15:14:13.205592+02:00 [debug] <0.1449.0> Transitioned from tuning to tuned
2024-05-08 15:14:13.205703+02:00 [debug] <0.1449.0> Open frame received for /
2024-05-08 15:14:13.205748+02:00 [debug] <0.1449.0> sending open response ok /
2024-05-08 15:14:13.205772+02:00 [debug] <0.1449.0> Checking token expiry
2024-05-08 15:14:13.205784+02:00 [debug] <0.1449.0> Transitioned from tuned to opened
2024-05-08 15:14:13.206459+02:00 [debug] <0.1449.0> Stream protocol reader received close command 1 <<"OK">>
2024-05-08 15:14:13.206582+02:00 [debug] <0.1449.0> rabbit_stream_reader terminating in state 'open' with reason 'normal'
2024-05-08 15:14:14.235730+02:00 [debug] <0.1459.0> Transitioned from tcp_connected to peer_properties_exchanged
2024-05-08 15:14:14.237249+02:00 [debug] <0.1459.0> Transitioned from peer_properties_exchanged to authenticating
2024-05-08 15:14:14.238951+02:00 [debug] <0.1459.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2024-05-08 15:14:14.239071+02:00 [debug] <0.1459.0> Transitioned from authenticating to authenticated
2024-05-08 15:14:14.239363+02:00 [debug] <0.1459.0> Tuning response 1048576 60
2024-05-08 15:14:14.239525+02:00 [debug] <0.1459.0> Transitioned from tuning to tuned
2024-05-08 15:14:14.239576+02:00 [debug] <0.1459.0> Open frame received for /
2024-05-08 15:14:14.239664+02:00 [debug] <0.1459.0> sending open response ok /
2024-05-08 15:14:14.239738+02:00 [debug] <0.1459.0> Checking token expiry
2024-05-08 15:14:14.239769+02:00 [debug] <0.1459.0> Transitioned from tuned to opened
2024-05-08 15:14:14.240504+02:00 [debug] <0.1459.0> Stream protocol reader received close command 1 <<"OK">>
2024-05-08 15:14:14.240661+02:00 [debug] <0.1459.0> rabbit_stream_reader terminating in state 'open' with reason 'normal'
2024-05-08 15:14:15.255532+02:00 [debug] <0.1467.0> Transitioned from tcp_connected to peer_properties_exchanged
2024-05-08 15:14:15.257334+02:00 [debug] <0.1467.0> Transitioned from peer_properties_exchanged to authenticating
2024-05-08 15:14:15.257708+02:00 [debug] <0.1467.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2024-05-08 15:14:15.257785+02:00 [debug] <0.1467.0> Transitioned from authenticating to authenticated
2024-05-08 15:14:15.258077+02:00 [debug] <0.1467.0> Tuning response 1048576 60
2024-05-08 15:14:15.258158+02:00 [debug] <0.1467.0> Transitioned from tuning to tuned
2024-05-08 15:14:15.258180+02:00 [debug] <0.1467.0> Open frame received for /
2024-05-08 15:14:15.258269+02:00 [debug] <0.1467.0> sending open response ok /
2024-05-08 15:14:15.258313+02:00 [debug] <0.1467.0> Checking token expiry
2024-05-08 15:14:15.258333+02:00 [debug] <0.1467.0> Transitioned from tuned to opened
2024-05-08 15:14:15.259218+02:00 [debug] <0.1467.0> Stream protocol reader received close command 1 <<"OK">>
2024-05-08 15:14:15.259314+02:00 [debug] <0.1467.0> rabbit_stream_reader terminating in state 'open' with reason 'normal'
[same thing over and over]```

**Comment by SimonUnge** [comment]
> res the stream and tries to es

**Comment by michaelklishin** [comment]
The consensus on the core team about this approach is that "the last 2%" of this PR may be impossible to address, that is, certain edge cases will be so complex to resolve than an external monitoring system that would enforce this limit would be a simpler solution.

**Pull request closed without merging**
