### PR TITLE
Ensure maintenance mode state table exists after node [re]boot

### LINKED ISSUE #4755: Maintenance mode: restore maintenance state table upon node boot
Per discussion in https://github.com/rabbitmq/discussions/issues/183#issuecomment-1119849840.

This would make maintenance mode tracking slightly more predictable and would not require any extra
upgrade machinery.

The table should only be restored if the maintenance mode feature flag is enabled.

### PR DESCRIPTION
**Pull request by michaelklishin**
## Proposed Changes

Some users were surprised by the current approach to
state table setup, so let's set make sure we ensure the table exists
on every boot (if the feature flag is enabled).

Per discussion in https://github.com/rabbitmq/discussions/issues/183#issuecomment-1119849840.
Closes #4755.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes issue #755)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by michaelklishin** [comment]
@TheGOro does this look like an improvement to you?

**Comment by TheGOro** [comment]
For the first glance it seems like that, but would it be okay to have different type of copies (ram copy on the first node that starts the cluster formation, then disc copies on the rest) of that table among the cluster members?
I'll give a spin to it on Monday.

**Comment by michaelklishin** [comment]
Changing table type would be too risky for mixed version clusters and upgrades. I'd leave the type as is, the table is lightly used that
it can be anything.

Also, in future versions where this might use Khepri, RAM tables won't be an option at all.

**Comment by michaelklishin** [comment]
I will look into the failures.

**Comment by michaelklishin** [comment]
So the failures are legitimate, the current approach is not always safe. I'll look into that.

**Comment by michaelklishin** [comment]
Not forcing a local copy helped. Writes to a created table without a forced local copy succeed, so do reads, so this accomplishes what the previous design did with more certainly that the table will be there after node boot.

**Comment by TheGOro** [comment]
> Not forcing a local copy helped.

My understanding is that this was the very issue that started the original discussion. However, I have no idea how the reporter managed to reach and observe such scenario (having different type of copies of the table among the cluster members), as it doesn't seem to be possible with any version of the upstream code...

I did some trials with your change, by simply just wrapping the compiled beam module into an .ez archive, to be loaded as a plugin. With that in place, I was not able to reproduce the issue where various kind of mnesia resets could eradicate the reminiscence of the maintenance status table from the whole cluster. Therefore, I think this will be fine.
Thanks for your work!

**Comment by michaelklishin** [comment]
@TheGOro thank you for reporting back. For tables that store semantically persistent data, forcing a local copy would be necessary. However here, we only need a couple of things:

 * The table must exist after the node's finished booting
 * The table must allow for status writes

and the current state accomplishes that with very little effort.

**Pull request merged**
