### PR TITLE
CQ: don't deliver right before acking in the index

### PR DESCRIPTION
**Pull request by lhoguin**
## Proposed Changes

Per short discussion with @michaelklishin I have removed the deliver before ack when writing into the index. This is used during purge and when removing expired messages.

I have not ran tests, let's see what CI tells us.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by lhoguin** [comment]
While the tests pass I will double check to make sure there isn't more assumptions in the index with regards to "acked messages are always delivered" before this can be merged.

**Comment by michaelklishin** [comment]
@lhoguin this has passed my upgrade tests. LGTM.

**Comment by lhoguin** [comment]
OK thanks. Let me do one final code read to make sure I've not missed anything and let's merge this afterwards!

**Comment by lhoguin** [comment]
@michaelklishin Should we backport this to 3.8?

**Comment by michaelklishin** [comment]
@lhoguin yes but let's wait for the pipeline to pass, including upgrade tests

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request merged**
