### PR TITLE
A way to configure a cluster wide queue limit

### PR DESCRIPTION
**Pull request by SimonUnge**
## Proposed Changes

Much simpler approach to https://github.com/rabbitmq/rabbitmq-server/discussions/10748.

Version for `main`: https://github.com/rabbitmq/rabbitmq-server/pull/11212.

This solution uses a limit conf setting. 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [x] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [x] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution
you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by SimonUnge** [comment]
@michaelklishin @mkuratczyk this is a simpler approach. 

Another way to 'store' the cluster wide queue limit, instead of config, would perhaps be to store it as a global parameter?
i.e `rabbitmqctl set_global_parameter cluster_limit '{"queue":"5"}'`

**Comment by michaelklishin** [comment]
No, we should not use global parameters for this that are not dynamic in nature, and knowing the background on this, this is something that an absolute majority of installations will set in stone and rarely change. Or not set in the first place.

**Comment by SimonUnge** [comment]
OK, ill leave as is and add some tests.

**Comment by michaelklishin** [comment]
@SimonUnge as for setting this cluster-wide setting on every node, since most cluster provisioning needs perform config generation one way or another, this won't be an issue. As long as the value is identical on all nodes anyway, which we can assume to be the case most of the time and/or eventually after a redeployment.

**Comment by SimonUnge** [comment]
yes, I agree. Its the easiest and most straightforward approach to setting it.

**Comment by mkuratczyk** [comment]
Thanks Simon. The limit is enforced in the wrong place however - it's only applicable to AMQP 0.9.1 and "non-native" protocols, so that'd be just STOMP in 4.0 or perhaps not even that. I can easily declare more queues than the limit I set by:
* importing definitions
* starting MQTT subscriptions
* using stream-perf-test
and probably a few other ways

I think these checks should be moved to `rabbit_queue_type:declare`

**Comment by SimonUnge** [comment]
@mkuratczyk ah right you are, I'll move it (I basically just placed it where the vhost queue limit is). I'll move it to a better place.

**Comment by SimonUnge** [comment]
@michaelklishin noticed I pointed this one to v3.13.x... Should I switch to main?

**Comment by michaelklishin** [comment]
You need to create a new branch off of main, cherry-pick the commit(s) there and push it, then submit a PR against main.

**Comment by SimonUnge** [comment]
@michaelklishin Done. Also squashed this commit.

**Comment by SimonUnge** [comment]
Will rebase on https://github.com/rabbitmq/rabbitmq-server/pull/11222 once merged, to combine the logic a bit.

**Pull request merged**
