### PR TITLE
Autoheal: the "autoheal_safe_to_start" state transition is not guaranteed to arrive on time

### PR DESCRIPTION
**Pull request by michaelklishin**
This is an extended version of #2208 by @tomyouyou which also updates a test so that it does not time out.

@tomyouyou if you have a way to reproduce the original problem, please give this PR a shot.

### CODE REVIEW

**Comment by tomyouyou** [comment]
Our testers reported that it has happened in an unstable network. I analyzed the log and found the issue.

**Comment by michaelklishin** [comment]
@tomyouyou thank you. Are my changes fine with you?

**Comment by michaelklishin** [comment]
I got a verbal approval from @dumbbell @dcorbacho.

**Comment by michaelklishin** [comment]
Will wait for 3.9 pipeline to pass before backporting. @tomyouyou the core team appreciates your ongoing contributions and persistence in making sure RabbitMQ works well for your needs :)

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` and `v3.7.x`.

**Pull request merged**
