### PR TITLE
Fix issue 7301 - broken vhost link

### LINKED ISSUE #7301: Browsing to a vhost by clicking on the name is broken
To reproduce:
* Start a broker
* Open management UI
* Click "Admin"
* Click "Virtual Hosts"
* Click the `/` virtual host name in the table
* 💥 

image

### PR DESCRIPTION
**Pull request by MarcialRosales**
The root cause is that the templates that renders permissions and topic permissions within the vhost page assumes that the `users` attribute has a paged list of users (i.e. wrapped around an `items` attribute) however the attribute is just a plain array.

## Proposed Changes

Modified the affected templates to list users assuming they are just a plain array rather than an array under `items`. 
Added selenium tests.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

Fixes #7301.

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]
I could reproduce the issue with `3.11.8` and this PR does address it.

**Review by lukebakken — APPROVED** [review]
Fixed!

**Comment by michaelklishin** [comment]
@mergifyio backport v3.12.x v3.11.x

**Comment by michaelklishin** [comment]
Automatic backport to `v3.10.x` introduces other regressions and had to be reverted.

Backporting this to `v3.10.x` would have to be manual.

**Comment by gomoripeti** [comment]
thanks for the manual effort

**Pull request merged**
