### PR TITLE
Fix win32 memory leak by using `raw` file operations

### PR DESCRIPTION
**Pull request by lukebakken**
Not ideal but this skips all file servers.

### CODE REVIEW

**Review by lhoguin — APPROVED** [review]

**Comment by lhoguin** [comment]
The commit title is a bit inaccurate as we were already using prim_file which is essentially the same as a raw operation. It would be better to describe that you are using read instead of read_file.

**Comment by kjnilsson** [comment]
could the leak be in `with_handle` which I also believe is bypassed by this commit?

**Comment by lukebakken** [comment]
@jhogberg figured it out in record time - https://github.com/erlang/otp/issues/5527#

**Comment by lukebakken** [comment]
@lhoguin I will rewrite the commit message, thanks for pointing that out.

**Comment by lukebakken** [comment]
@kjnilsson that's what I originally thought but it's not the FHC.

**Comment by lukebakken** [comment]
> The commit title is a bit inaccurate as we were already using prim_file which is essentially the same as a raw operation.

FWIW `prim_file:read_file/1` leaks, but `file:read` in `raw` mode does not 🤷

**Comment by lukebakken** [comment]
@lhoguin @michaelklishin I'll re-test this on my Windows system this coming Monday, then I'll move it out of draft.

**Comment by lukebakken** [comment]
procexp-erl-rmq-gh-3895-20211218_1200

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
