### PR TITLE
OAuth 2, breaking change: upgrade oidc-client-ts library to a new major

### PR DESCRIPTION
**Pull request by MarcialRosales**
## Proposed Changes

Address issue https://github.com/rabbitmq/rabbitmq-server/issues/11400

*Note*: This PR should not be merged to 3.13. It has a breaking change. 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

### CODE REVIEW

**Comment by michaelklishin** [comment]
The forced-push was a rebase.

**Comment by michaelklishin** [comment]
@MarcialRosales is this still a WIP or should it be marked as ready for review?

**Comment by michaelklishin** [comment]
The forced push was a rebase.

**Comment by MarcialRosales** [comment]
@michaelklishin yes, it is ready for review. I just changed it.

**Review by michaelklishin — APPROVED** [review]

**Pull request merged**
