### PR TITLE
Run checks & tests in GitHub Actions on every push

### PR DESCRIPTION
**Pull request by gerhard**
This is related to https://github.com/rabbitmq/rabbitmq-common/pull/361

Leaving as WIP since it's not finished.

### CODE REVIEW

**Comment by gerhard** [comment]
These tests sometimes pass and sometimes fail, same as they did in Concourse, so this has nothing to do with GitHub Actions.

When a test fails, does it fail because it's a race condition in the test or in the code? Maybe the test fails for a genuine reason, but only sometimes, so how can I tell since I have no context on the feature or the test? Yes, I could spend time to investigate, but then a change that should take a few weeks at most snowballs into a few months, or even longer - none knows. Some test suites have been fixed and as a result un-deleted, so if this is the desired outcome, let's split the deleted test suites among all those that will be joining this undertaking and fix them.

Alternatively, and this is the option that doesn't impose on anyone's time, let's delete all tests that sometimes fail, and stay focused on what is expected from this PR.

What makes sense to you?

**Comment by michaelklishin** [comment]
I can see how some very intricate multi-node tests can be considered not worth the effort (perhaps we should do more property-based or workload simulation testing elsewhere) but deleting dozens of tests because one of them hangs on CI https://github.com/rabbitmq/rabbitmq-server/commit/3d09f39263a57e5b941f78089c9065f4bffbc989 is complete overkill.

**Comment by michaelklishin** [comment]
I am splitting those kitchen sink test suites dozens of small ones in master. This way it would be a lot easier to investigate failures.

**Comment by gerhard** [comment]
**clustering_management_SUITE > unclustered_2_nodes > cluster_size_2 > erlang_config** continues to fail predictably on both OTP [v21.3](https://github.com/rabbitmq/rabbitmq-server/runs/549369764?check_suite_focus=true#step:6:81) & [v22.3](https://github.com/rabbitmq/rabbitmq-server/runs/549371440?check_suite_focus=true#step:6:81)

Just fixed **ct-cluster_formation_locking** & rebased onto `master`.

**Comment by gerhard** [comment]
Requires the following to be merged as well:

- https://github.com/rabbitmq/rabbitmq-erlang-client/tree/github-actions
- https://github.com/rabbitmq/rabbitmq-common/tree/github-actions
- https://github.com/rabbitmq/rabbitmq-cli/tree/github-actions

**Comment by gerhard** [comment]
No tests were deleted, all checks pass, merging :shipit:

**Pull request merged**
