### PR TITLE
rabbit: Change start_apps/2 to call application:ensure_all_started/2

### PR DESCRIPTION
**Pull request by dumbbell**
.. instead of reinventing about the same logic.

start_apps/2 is not called to start the `rabbit` application anymore (it is started as a normal Erlang application now). It means it's only used to start plugins which are also supposed to be regular Erlang
applications.

It runs boot steps unconditionally as well (because this function never starts `rabbit).

One difference with the previous code is that the previous code started all loaded applications. This seemed unnecessary and even caused issues with testsuites where some applications were loaded like `rabbitmqctl` but were not meant to be started.

Another difference is that before, all boot steps were executed at once, then all plugins were started. Now, to improve consistency and make sure that a dependency is fully ready before a plugin which depends on it starts, for each application we execute the boot steps then start it, before moving to the next.

### CODE REVIEW

**Comment by dumbbell** [comment]
The failure I mention in the commit happens all the time in Travis CI for instance. I couldn't reproduce it locally however. Perhaps there is a timing issue somewhere, I don't know... Anyway, I looked at the history of that code starting applications back to May 2012 but no commits explain the reason behind it.

**Comment by dumbbell** [comment]
Currently, the `start_apps/2` function (both before and after this patch) runs all boot steps it finds, then starts all applications.

We want to change that to a loop where, for each application, it runs the boot steps for this application, then starts it (and continues with the next application). This should be more consistent w.r.t. what a particular application can expect. For instance, a plugin's boot steps could rely on the fact dependencies will always be running. This is not the case currently, depending on how dependencies are started.

Also, we found an issue, introduced with rabbitmq/rabbitmq-server#2180, with plugins' boot steps executed as part of RabbitMQ startup: a plugin's boot steps are executed after the plugin is started.

**Comment by michaelklishin** [comment]
@dumbbell this does not backport cleanly, I'll assume this is because the `rabbit_env` and `rabbit_prelaunch` transition hasn't been backported so far, so those changes have to be backported together.

**Comment by dumbbell** [comment]
Yes, that's correct. This patch is linked to the "master" issue (#2180) so we remember to backport it as well.

Thank you for merging it!

**Pull request merged**
