### PR TITLE
Keep listeners on a local ram table

### PR DESCRIPTION
**Pull request by dcorbacho**
## Proposed Changes

Keep listeners on a local ram table instead of a replicated table. This avoids an unnecessary cleanup on node down, as listeners are linked to a node's life.

## Types of Changes
- [x] Bug fix (non-breaking change which fixes issue #5213)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Review by michaelklishin — CHANGES_REQUESTED** [review]
The test failures are repeatable and can be reproduced locally

**Comment by gomoripeti** [comment]
wondering what is the benefit of using ram-only mnesia tables with node-specific name and content instead of just an ets table. It is harder to change the schema eg adding a field to the listener record. Also what will happen with these tables after migration to khepri?
asking because this is also relevant for connection and channel tracking tables.

**Comment by michaelklishin** [comment]
@gomoripeti we would have to give up or change all queries. Here the goal is to simply Khepri integration, not much else.

**Comment by michaelklishin** [comment]
The failures are due to an ongoing BuildBuddy issue.

**Comment by gomoripeti** [comment]
> @gomoripeti we would have to give up or change all queries. Here the goal is to simply Khepri integration, not much else.

aha, so the goal in this particular PR is to keep the code change and the chance of any regression minimal, makes sense, thanks!

**Pull request merged**
