### PR TITLE
Optimise MQTT state machine

### PR DESCRIPTION
**Pull request by kjnilsson**
It was particularly slow when processing down commands.

See: https://github.com/rabbitmq/rabbitmq-server/discussions/2688

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Comment by carlhoerberg** [comment]
didn't go so well:
[rabbit@carl-xps13-fedora.log.gz](https://github.com/rabbitmq/rabbitmq-server/files/5726996/rabbit%40carl-xps13-fedora.log.gz)

**Comment by kjnilsson** [comment]
oh bother, I just realised I broke backwards compatibility. @michaelklishin we're going to have to remove the backport until I can fix this.

**Comment by kjnilsson** [comment]
@carlhoerberg I've created a new PR https://github.com/rabbitmq/rabbitmq-server/pull/2693 that includes backwards compatibility. I'm still testing this but we'd welcome more testing of course. :)

**Pull request merged**
