### PR TITLE
'basic.publish' reports 'not found' when getting no queues by 'rabbit_exchange:route'

### PR DESCRIPTION
**Pull request by tomyouyou**
to reproduce the issue by the follow steps:
1. node1(192.168.1.217) and node2(192.168.1.220) join a cluster.
2. publish/consume a confirm-selected message in node2:
    python msg_test.py create_queue 192.168.1.220 'queue=q11;durable=false' 
    python msg_test.py create_exchange 192.168.1.220 'exchange=ex11;exchange_type=topic'
    python msg_test.py bind 192.168.1.220 'exchange=ex11;queue=q11;routing_key=exq11'
    python msg_test.py publish 192.168.1.220 'exchange=ex11;routing_key=exq11;msg="_unique_id:123";count=1'
    python msg_test.py consume 192.168.1.220 'queue=q11;auto_ack=false'
3. stop rabbitmq in node2. so the queue 'q11' and its binding would be deleted, 
    while the exchange 'ex11' is preserved.
4. publish a confirm-selected message in node1 and return ok. but the message was dropped in fact, and 
    the client do not known that.
    
    python msg_test.py publish 192.168.1.217 'exchange=ex11;routing_key=exq11;msg="_unique_id:123";count=1'
    
    after resolved this issue, the client will catch a exceptions:
    (404, "NOT_FOUND - no queues for exchange 'ex11' with routing key 'exq11'")

Note: the code 'msg_test.py' ,see  'https://github.com/rabbitmq/rabbitmq-server/pull/2096',
the difference is: 
the channel is confirm-selected, please insert ‘’ channel.confirm_delivery() ‘’ after "channel = connection.channel()"

### CODE REVIEW

**Comment by lukebakken** [comment]
Thank you for the report.

Please attach the code you used when testing this issue.

It is much more helpful to attach the _full_ copy of code you are using, rather than describing what you are doing. In #2096 we would have saved a lot of time by having your code from the start.

**Comment by michaelklishin** [comment]
This reinvents [Unroutable Message Handling](https://www.rabbitmq.com/publishers.html#unroutable) and is a breaking protocol change. Sorry, we can't accept this.

**Comment by lukebakken** [comment]
@tomyouyou - please re-run your test. Use publisher confirms _and_ use the `mandatory` flag. You will receive an exception.

**Comment by michaelklishin** [comment]
It's worth mentioning that [the spec says](https://www.rabbitmq.com/amqp-0-9-1-reference.html):

```
The client attempted to work with a server entity that does not exist.
```

In this case the exchange *does* exist. Looking further you'd find [the mandatory flag](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.publish.mandatory) that exists because

```
This flag tells the server how to react if the message cannot be routed to a queue.
If this flag is set, the server will return an unroutable message with a Return method.
If this flag is zero, the server silently drops the message.
```

Not only this is [the documented behavior](https://www.rabbitmq.com/publishers.html#unroutable), in 3.8 we have a new metric for the "silently dropped" case (a rate). Returned message rate has been around for years.

So instead of introducing a breaking protocol change, please register a returned message handler
and publish with the mandatory flag set to `true`.

**Comment by tomyouyou** [comment]
@michaelklishin @lukebakken  Thank you for your explanation. 

For clients, as long as the server cluster is available, even if a node is powered down, resulting in temporary unroutable, they hope that the published messages can always be delivered to the receiver.

There are several situations:
1. When the exchange does not exist, server will report a 'not found' exception. As long as the client catches the exception, it decides whether to resend the message or not.

2. When the exchange exists and the routing-key is unroutable, server will discard the message and confirm it normally. If mandatory flag is true, sever will send a 'basic.return'. 
This means that every message sent by the client will be cached after it is sent, and it needs to wait for a period of time to determine whether the 'basic.return' will be received, so as to decide whether to resend it.
First of all, this time is not easy to set. In addition, in a large-scale cluster, there are thousands of messages per second, which may be a disaster for the client.

**Comment by michaelklishin** [comment]
@tomyouyou that's the sad reality of distributed systems. Things are not guaranteed to happen and more importantly, not guaranteed to happen instantly or within a certain period of time.

Your publisher will have to wait or be prepared to handle asynchronous failures with [publisher confirms](https://www.rabbitmq.com/publishers.html#data-safety) as well.

We won't accept this breaking change. It reinvents existing features available in the protocol since 1.0 (for over a decade).

**Comment by lukebakken** [comment]
> This means that every message sent by the client will be cached after it is sent, and it needs to wait for a period of time to determine whether the 'basic.return' will be received, so as to decide whether to resend it.

This isn't unique to RabbitMQ. If you need 100% reliable communication over a network a response that confirms that the data is accepted must be sent back to the client, and the client **must** keep the data around until the response is seen.

**Pull request closed without merging**
