### PR TITLE
fix up bazel build of rabbitmq_cli when branch switching

### PR DESCRIPTION
**Pull request by pjk25**
It seems to be the case that sometime after switching branch there are errors when building the cli, that are fixed with a `bazel clean`, such as:

```
ERROR: /Users/mkuratczyk/rabbitmq/rabbitmq-server/deps/rabbitmq_cli/BUILD.bazel:11:12: MIX deps/rabbitmq_cli/escript/rabbitmqctl failed: (Exit 1): bash failed: error executing command (from target //deps/rabbitmq_cli:rabbitmqctl) /bin/bash -c ... (remaining 1 argument skipped)
cp: /Users/mkuratczyk/data/_bazel_mkuratczyk/c6c37788822ef0f8af3f5b88cfd34f26/execroot/_main/bazel-out/darwin_arm64-dbg/bin/deps/rabbitmq_cli/rabbitmqctl_deps/rabbit_common/src/rabbit_exchange_type.erl: No such file or directory
```

A bazel clean can be rather expensive, though, so it would be nice to avoid it.

### CODE REVIEW

**Comment by pjk25** [comment]
@mkuratczyk I guess the proper way to test this is to cherry-pick https://github.com/rabbitmq/rabbitmq-server/pull/7692/commits/87fc43df1159a440997868fc69d06bdf6e7b78b4 onto two branches locally, then try the switch back and forth?

**Comment by mkuratczyk** [comment]
Seems like `v3.11.x` -> `main` is fixed with this PR indeed. The problem is with `main` -> `v3.11.x`:
```
+ [[ -f /Users/mkuratczyk/data/rabbit@mkuratczykPF0JR/rabbit@mkuratczykPF0JR.pid ]]
++ cat /Users/mkuratczyk/data/rabbit@mkuratczykPF0JR/rabbit@mkuratczykPF0JR.pid
+ kill -9 17619
/Users/mkuratczyk/bin/fresh-broker: line 8: kill: (17619) - No such process
+ rm -rf /Users/mkuratczyk/data/rabbit@mkuratczykPF0JR/
+ cd /Users/mkuratczyk/rabbitmq/rabbitmq-server/
+ OVERRIDES=
+ bazel run -c dbg broker RABBITMQ_ENABLED_PLUGINS=rabbitmq_management,rabbitmq_prometheus,rabbitmq_stream '' ''
$TEST_TMPDIR defined: output root default is '/Users/mkuratczyk/data/' and max_idle_secs default is '15'.
RULES_ERLANG: Final package list:
RULES_ERLANG:     accept@0.3.5
RULES_ERLANG:     aten@0.5.8
RULES_ERLANG:     base64url@1.0.1
RULES_ERLANG:     cowboy@2.8.0
RULES_ERLANG:     cowlib@2.9.1
RULES_ERLANG:     credentials_obfuscation@3.2.0
RULES_ERLANG:     csv@2.4.1
RULES_ERLANG:     cuttlefish@3.1.0
RULES_ERLANG:     eetcd@0.3.6
RULES_ERLANG:     enough@0.1.0
RULES_ERLANG:     gen_batch_server@0.8.7
RULES_ERLANG:     getopt@1.0.2
RULES_ERLANG:     gun@1.3.3
RULES_ERLANG:     json@1.4.1
RULES_ERLANG:     thoas@1.0.0
RULES_ERLANG:     observer_cli@1.7.3
RULES_ERLANG:     prometheus@4.10.0
RULES_ERLANG:     quantile_estimator@0.2.1
RULES_ERLANG:     ra@2.4.9
RULES_ERLANG:     ranch@2.1.0
RULES_ERLANG:     recon@2.5.3
RULES_ERLANG:     redbug@2.0.7
RULES_ERLANG:     seshat@0.4.0
RULES_ERLANG:     stdout_formatter@0.2.4
RULES_ERLANG:     sysmon_handler@1.3.0
RULES_ERLANG:     systemd@0.6.1
RULES_ERLANG:     jose@d63c1c5c8f9c1a4f1438e234b886de8607a0034e
RULES_ERLANG:     osiris@v1.4.3
RULES_ERLANG:     syslog@4.0.0
RULES_ERLANG:     ct_helper@master
RULES_ERLANG:     emqtt@1.8.2
RULES_ERLANG:     inet_tcp_proxy_dist@master
RULES_ERLANG:     meck@master
RULES_ERLANG:     proper@master
DEBUG: Rule 'rules_erlang~3.9.9~erlang_package~osiris' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "52842e66c91a393d347c64487b8e3a12911dde54" and dropping ["tag", "branch"]
DEBUG: Repository rules_erlang~3.9.9~erlang_package~osiris instantiated at:
  callstack not available
Repository rule git_repository defined at:
  /Users/mkuratczyk/data/_bazel_mkuratczyk/c6c37788822ef0f8af3f5b88cfd34f26/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
INFO: Analyzed target //:broker (178 packages loaded, 3393 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule //deps/rabbitmq_management:rabbitmqadmin:
+ sed s/%%VSN%%/3.11.0/ deps/rabbitmq_management/bin/rabbitmqadmin
INFO: From ERLC external/rules_erlang~3.9.9~erlang_package~ra/ebin/ra.beam:
Inlining: inline_size=24 inline_effort=150
Inlining: inline_size=24 inline_effort=150
Old inliner: threshold=0 functions=[{handle_raft_state,3}]
ERROR: /Users/mkuratczyk/rabbitmq/rabbitmq-server/deps/rabbit/BUILD.bazel:189:13: ERLC deps/rabbit/ebin/amqqueue.beam failed: (Exit 1): bash failed: error executing command (from target //deps/rabbit:beam_files) /bin/bash -c ... (remaining 195 arguments skipped)
Old inliner: threshold=0 functions=[{r2f,2},{f2r,2}]
compile: warnings being treated as errors
deps/rabbit/src/rabbit_exchange_type_direct.erl:11:2: undefined callback function delete/2 (behaviour 'rabbit_exchange_type')
%   11| -behaviour(rabbit_exchange_type).
%     |  ^

Target //:broker failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.443s, Critical Path: 16.81s
INFO: 1199 processes: 1157 internal, 42 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

**Comment by pjk25** [comment]
The arity of `rabbit_exchange_type_direct:delete` is different in v3.11.x and main. It's a callback of the `rabbit_exchange_type` module, where the arity changed as well. However on top of that, the module moved from `rabbit_common` to `rabbit`. I'm guessing that as a side effect of the lighter macos sandboxing we are using, the compile of rabbit is seeing the leftover copy of the `rabbit_exchange_type` module from the other branch. I suspect that #6466 might fix this since it eliminates the dynamic two-phase compilation step and therefore has a slightly cleaner code path for compilation.

**Comment by pjk25** [comment]
The arity of `rabbit_exchange_type_direct:delete` is different in v3.11.x and main. It's a callback of the `rabbit_exchange_type` module, where the arity changed as well. However on top of that, the module moved from `rabbit_common` to `rabbit`. I'm guessing that as a side effect of the lighter macos sandboxing we are using, the compile of rabbit is seeing the leftover copy of the `rabbit_exchange_type` module from the other branch. I suspect that #6466 might fix this since it eliminates the dynamic two-phase compilation step and therefore has a slightly cleaner code path for compilation.

**Comment by pjk25** [comment]
The arity of `rabbit_exchange_type_direct:delete` is different in v3.11.x and main. It's a callback of the `rabbit_exchange_type` module, where the arity changed as well. However on top of that, the module moved from `rabbit_common` to `rabbit`. I'm guessing that as a side effect of the lighter macos sandboxing we are using, the compile of rabbit is seeing the leftover copy of the `rabbit_exchange_type` module from the other branch. I suspect that #6466 might fix this since it eliminates the dynamic two-phase compilation step and therefore has a slightly cleaner code path for compilation.

**Comment by pjk25** [comment]
The arity of `rabbit_exchange_type_direct:delete` is different in v3.11.x and main. It's a callback of the `rabbit_exchange_type` module, where the arity changed as well. However on top of that, the module moved from `rabbit_common` to `rabbit`. I'm guessing that as a side effect of the lighter macos sandboxing we are using, the compile of rabbit is seeing the leftover copy of the `rabbit_exchange_type` module from the other branch. I suspect that #6466 might fix this since it eliminates the dynamic two-phase compilation step and therefore has a slightly cleaner code path for compilation.

**Comment by pjk25** [comment]
I will merge this since I think the `main` -> `v3.11.x` can be addressed independently, either by #6466 or another PR.

**Pull request merged**
