### PR TITLE
Add systemd hardening parameters in rabbitmq-server.service.example

### PR DESCRIPTION
**Pull request by easyteacher**
## Proposed Changes

systemd offers various options to harden services. These options offer mitigations for rabbitmq-server.

To see details please visit https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [x] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

### CODE REVIEW

**Comment by michaelklishin** [comment]
@easyteacher are all of these safe to suggest uncommented by default? Or should some be commented out as suggestions to consider?

**Comment by michaelklishin** [comment]
My point is that some people will copy this file as is and run with it. We have seen this happen too many times with other examples.

**Comment by easyteacher** [comment]
> are all of these safe to suggest uncommented by default?

rabbitmq-server.service can still be started sucessfully, and currently no bugs have been reported after https://build.opensuse.org/request/show/926714 is accepted a month ago.

Those options are designed to protect system key components from being illegally modified, like hostname/user home/clock/kernel modules. I think rabbitmq-server doesn't need those privileges normally.

> My point is that some people will copy this file as is and run with it. We have seen this happen too many times with other examples.

I didn't realize they should be commented.  I have pushed a new commit and added information to the example.

```
# Note: You *may* wish to uncomment the following lines to apply systemd
# hardening effort to RabbitMQ, to prevent your system from being illegally 
# modified by undiscovered vulnerabilities in RabbitMQ.
```

**Comment by lukebakken** [comment]
What version of `systemd` added these options? If someone is using `systemd` that does not support these options, are they ignored or do they cause errors?

**Comment by easyteacher** [comment]
> What version of `systemd` added these options? 

According to https://www.redhat.com/sysadmin/mastering-systemd, `ProtectSystem`, `ProtectHome`, `ProtectDevices` were introduced in RHEL7 (at least systemd v219), and other options were introduced in RHEL8 (at least systemd v234).

> If someone is using `systemd` that does not support these options, are they ignored or do they cause errors?

Tested with systemd v249,  unknown options will be ignored.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
