### PR TITLE
CQv1: Disable expensive stats killing v1 performance

### PR DESCRIPTION
**Pull request by lhoguin**
In particular:

 - io_file_handle_open_attempt
 - queue_index_journal_write

Neither have proven to be very useful in recent years
and with the move to FHC-less and journal-less v2 index
they will slowly become irrelevant. This should be a
good compromise until we can switch to v2 permanently
or rework the stats module to use counters.

Proposal for https://github.com/rabbitmq/rabbitmq-server/pull/4275.

@felixhuettner's comparison of this PR to #4275: https://github.com/rabbitmq/rabbitmq-server/pull/4275#issuecomment-1088472795.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Should we remove them from the UI and possibly API responses, too?

**Comment by lhoguin** [comment]
@michaelklishin Didn't realise it appeared somewhere in the UI. Can you point me to where we can see this?

**Comment by lhoguin** [comment]
Nevermind, found them.

**Comment by michaelklishin** [comment]
Individual queue and node metric pages.

**Comment by lhoguin** [comment]
I did not find anything on individual queue pages. I am not sure what the implications of modifying stats with regard to mixed version clusters. If there's no problem just removing the stats entirely I can do that, otherwise just remove from the UI?

**Review by lukebakken — APPROVED** [review]

**Comment by lukebakken** [comment]
I doubt anyone would notice these being removed from the UI and/or API. FWIW I never used these stats to diagnose an issue with RabbitMQ.

**Comment by michaelklishin** [comment]
@lhoguin we can try removing them and running management suite tests in mixed version mode.

**Comment by lhoguin** [comment]
There are some mixed version failures around the node stats making the /nodes and /overview resources fail with a 500 error. It is caused by a function_clause crash due to differing number of stats expected/received (it's using tuples so not ideal). I guess I could leave the tuple size and thus number of stats as before, but still remove them from API results and UI. I will try that after a break.

**Comment by michaelklishin** [comment]
Yes, that's a major pain point with how stats are currently stored. I remember we had to add code when adding new metrics with @dcorbacho.

Filtering out those metrics from API responses sounds OK to me.

**Comment by lhoguin** [comment]
All tests pass!

**Comment by michaelklishin** [comment]
Three HTTP API client test suites pass with this change: Ruby, Hop (Java) and rabbit-hole (Go).

**Pull request merged**
