### PR TITLE
Made rabbit_fifo_client:pick_server/1 pick randomly

### PR DESCRIPTION
**Pull request by ariel-anieli**
## Proposed Changes

* instead of first server, picks randomly among the servers
* replaced case statement in `set_timer/2` with `pick_server/1`.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

None.

### CODE REVIEW

**Comment by michaelklishin** [comment]
I'm afraid we will not accept a quorum queue (-related) change like this without a good justification.

Consider starting a discussion first when you want to touch an essential part of the codebase.

**Comment by michaelklishin** [comment]
Also, if a change is on the hot code path of publishers and consumers, use PerfTest to prove that the change does not introduce regressions.

A nice little refactoring and duplication removal can result in a 30% throughput drop, we've been there before.

**Comment by ariel-anieli** [comment]
> I'm afraid we will not accept a quorum queue (-related) change like this without a good justification.
> 
> Consider starting a discussion first when you want to touch an essential part of the codebase.

I will do that; thanks for the feedback.

> Also, if a change is on the hot code path of publishers and consumers, use PerfTest to prove that the change does not introduce regressions.
> 
> A nice little refactoring and duplication removal can result in a 30% throughput drop, we've been there before.

I didn't do it, indeed; I will check if the changes come with drawbacks.

**Comment by ariel-anieli** [comment]
Herewith the discussion: https://github.com/rabbitmq/rabbitmq-server/discussions/10435

**Pull request closed without merging**
