### PR TITLE
Use gazelle for some maintenance of bazel BUILD files

### PR DESCRIPTION
**Pull request by pjk25**
## Proposed Changes

Make use files generated with the somewhat experimental erlang language extension for [gazelle](https://github.com/bazelbuild/bazel-gazelle) provided by [rules_erlang](https://github.com/rabbitmq/rules_erlang).

Running `bazel run gazelle` should non-destructively update the rules when needed. Typically this won't be necessary for changes to existing modules, but adding new modules, or new dependencies between rabbitmq plugins will.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [x] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

This is not ready to merge yet, until the gazelle extension is more stable.

### CODE REVIEW

**Comment by PraveenNanda124** [comment]
Good work

**Comment by pjk25** [comment]
Some of these changes will have already been made in #6928

**Comment by michaelklishin** [comment]
I keep running into an exception with

```
bazel run gazelle
```

```
Configure: deps/observer_cli <nil>
Configure: deps/observer_cli/ebin <nil>
GenerateRules: deps/observer_cli/ebin <nil>
Configure: deps/observer_cli/include <nil>
GenerateRules: deps/observer_cli/include <nil>
Configure: deps/observer_cli/src <nil>
GenerateRules: deps/observer_cli/src <nil>
GenerateRules: deps/observer_cli <nil>
    Importing Rebar from /Users/antares/Development/RabbitMQ/main.git/deps/observer_cli/rebar.config
escript: exception error: no function clause matching
                 rebar_config_to_json__escript__1677__182284__834756__8:conformErlOpt({src_dirs,
                                                                                       ["src",
                                                                                        "test"]}) (/private/var/tmp/_bazel_antares/14f90f8a31f5e7ccfc4ded95d3ba96d8/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/gazelle.runfiles/rules_erlang~3.9.7/gazelle/rebar_config_to_json, line 71)
  in function  rebar_config_to_json__escript__1677__182284__834756__8:'-conformConfig/1-lc$^0/1-0-'/1 (/private/var/tmp/_bazel_antares/14f90f8a31f5e7ccfc4ded95d3ba96d8/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/gazelle.runfiles/rules_erlang~3.9.7/gazelle/rebar_config_to_json, line 88)
  in call from maps:map_1/2 (maps.erl, line 439)
  in call from maps:map_1/2 (maps.erl, line 439)
  in call from maps:map/2 (maps.erl, line 429)
  in call from rebar_config_to_json__escript__1677__182284__834756__8:parse/1 (/private/var/tmp/_bazel_antares/14f90f8a31f5e7ccfc4ded95d3ba96d8/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/gazelle.runfiles/rules_erlang~3.9.7/gazelle/rebar_config_to_json, line 108)
  in call from rebar_config_to_json__escript__1677__182284__834756__8:main/1 (/private/var/tmp/_bazel_antares/14f90f8a31f5e7ccfc4ded95d3ba96d8/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/gazelle.runfiles/rules_erlang~3.9.7/gazelle/rebar_config_to_json, line 18)
gazelle: ERROR: failed to parse: read |0: file already closed
gazelle: failed to wait for rebar_config_to_json: exit status 127
```

**Comment by pjk25** [comment]
Thanks for testing this Michael. What has happened in this case is that gazelle is scanning the directories fetched with `make` and hit a case not currently covered. One option is just to clean the deps dir first, I'll make some adjustments to exclude these directories.

**Comment by pjk25** [comment]
@michaelklishin I made a few changes to cover the case of running this after running `make`, as seems to be the situation you encountered, and rebased it. It seems to be stable at this point. No rush, but if you want to take another look at this, I think it's ready.

**Pull request merged**
