### PR TITLE
Asynchronous resource alarm tracker registration for protocol connections

### PR DESCRIPTION
**Pull request by Ayanda-D**
## Proposed Changes

When connections start, they all register/subscribe to the rabbit-alarm manager and listen for resource alarms and respond accordingly, e.g. throttle connections. All along this has been carried out via the synchronous `rabbit_alarm:register/2` [call](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_reader.erl#L1232), which in-turn calls `gen_event:call/4` with a timeout `infinity`. This path is OK when only a few connections are in use and reconnect near concurrently. However, as connection counts increase to the order of thousands and millions (as seen with common MQTT/IoT use cases), the `rabbit_alarm` gen_server process becomes a bottleneck, queueing up thousands of connection registration requests in its message queue.  This in-turn blocks the socket reader process from proceeding with processing incoming protocol frames from the client, until successful registration in the rabbit-alarm manager. 

This PR changes the the way different protocol connections register/subscribe to resource alarms. This is now done in a non-blocking async manner, where registration request spawns a process and allows the socket reader process to proceed processing with resource alarm registration confirmation following after, allowing socket reader processes to complete initialization fast to start processing ingress frames immediately (this should be OK and should not have any reason to be blocked or interfered by alarm registration). Effects of the existing blocking effects of rabbit_alarm manager can be observed by inserting code to log: `{message_queue_len, L} = erlang:process_info(whereis(rabbit_alarm), message_queue_len).` after the existing `rabbit_alarm:register/2` calls in the different protocol reader processes. The message queue can be observed growing, and thus slowing down the socket reader/connection initialisation. 

Asynchronous rabbit-alarm registration support in this PR is currently added for:
- AMQP-0.9.1
- AMQP-1.0
- MQTT (v4 and v5)
- STOMP

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
So what is the problem this addresses? A spike in new connections is now "processed" quicker?

There is a downside to registering asynchronously: new connections is a cluster in alarmed state would have a chance to send more data initially. I don't think that's going to change much but it was brought up by a core team member.

**Comment by michaelklishin** [comment]
Do you have any numbers that demonstrate the effectiveness of this change?

**Comment by michaelklishin** [comment]
Another idea expressed on the team is to see what in `rabbit_alarm` can be optimized instead. We expect that with a fast handler, nodes may be able to handle a few thousands of `gen_event:call/4` per second. And we generally do not care to support higher rates of new connections.

**Comment by ansd** [comment]
@Ayanda-D can you please identify what exactly in the `rabbit_alarm` handling code causes the bottleneck?
E.g. using maps instead of `dict` could make registration a bit faster.

**Comment by Ayanda-D** [comment]
@ansd it's `rabbit_alarm` itself. It's a known Erlang and concurrency design problem - alarm registry using synchronous `gen_event:call/4` (i.e. https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen_event.erl#L488) on parallel processes, you're basically going through a single process message queue. The concept of alarm management is OK, OTP-design wise (hence I didnt change rabbit-alarm itself), but the problem is how parallel (isolated) connections are registering/subscribing to alarms. We need to maintain the parallelism there as well. Fire and forget the registry request, and handle the reply moments/immediately after in async. There's no need to wait for the alarm manager to go through its pending messages in its message queue before the reader processes can complete initialization.

**Comment by michaelklishin** [comment]
This PR currently fails to build with Bazel:

```
reader_SUITE.erl:12:14: can't find include lib "amqp_client/include/amqp_client.hrl"
```

Running

``` shell
bazel run gazelle
```

adds a missing dependency to the `test/reader_SUITE.beam` compilation rule.

**Comment by ansd** [comment]
@Ayanda-D I just ran a simple benchmark. Even with only a 1 single Erlang scheduler, i.e. no parallelism going on at all, I can easily run 100,000 concurrent clients each synchronously calling into an event manager process via `gen_event:call/3` once a second, and that event manager process is able to sustain the throughput of 100,000 requests / second with low response time observed by the clients.

All these `rabbit_alarm` registrations are happening node local.
So, your claim that a synchronous `gen:call/4` is the bottleneck here is not true.

While async alarm registration might be a 2nd step, the 1st step is identifying the bottleneck. The bottleneck is that something inside the `rabbit_alarm` event manager process is slow and blocks for too long. Please identify this bottleneck first before coming up with a complex workaround as done in this PR.
Your code looks to me very complex and hard to maintain: it creates processes, uses process dictionary, fires timers, retries, catches all exceptions, etc... For example, a nicer solution would be to use `gen_event:send_request/3,4` for async requests.

But again before directly going with this workaround as step 2, please do step 1 first: identifying what exactly in the `rabbit_alarm` process blocks or takes long to process. If these bottlenecks have been removed and we don't see anything further to optimise within the event manager process itself, then we can talk about this PR as step 2.

**Comment by Ayanda-D** [comment]
> that event manager process is able to sustain the throughput of 100,000 requests / second with low response time observed by the clients

@ansd start a single rabbit node, spawn just 100 processes that open connections at the same time and observe the alarm message queue grow. The approach is to first _avoid the single point of contention_, then you can look optimizing data structures and processing in the alarm manager. Whats the point of concurrent connections, Ranch acceptor pool, if down the line we're going through a single process. We're addressing a design problem first, then you can look at optimizing processing within the alarm manager. 

I'm also not sure whats too complex here, this approach is quite straight-forward and already similar in use within the broker:
https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_connection_tracking.erl#L62
https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_channel_tracking.erl#L49

The only difference here is we're handling the response to ensure alarm registration was done, and scheduling a check to verify that the reader process isn't running without being registered in the alarm handler (thats the purpose of timers). In the past, we've also had serious problems with similar single points of contention, e.g. management plugin event collector which had to be redesigned for better parallelism. The alarm manager may not be inducing severe side effects, but 1-million simultaneous connections being blocked by a single process (even if throughput is high) is bad design to begin with.

**Comment by ansd** [comment]
Closing this PR since feedback has not been addressed.
Please:
1. Identify the bottleneck in `rabbit_alarm` event manager process why client registrations cannot be served fast enough.
2. Fix the identified bottlenecks.
3. If client registrations still cannot be served fast enough, go with an async registration approach as intended by this PR. However, please increase code quality (For example, I hinted above to use https://www.erlang.org/doc/man/gen_event#send_request-3).
4. Ensure message publishes from (newly registered) clients are not processed when an alarm is active.

**Comment by Ayanda-D** [comment]
So as it stands: ALL concurrent protocol connections, AMQP 0.9.1, AMQP-1.0, MQTT and STOMP (imagine a broker with all plugins enabled) will all served and blocked by a single gen-event process **_rabbit_alarm_** for simple alarm management subscription on connection establishment, regardless of how big things like the tcp acceptor pool size is tuned for concurrency. The bottleneck is the single process `rabbit_alarm` itself which is supposed to be serving thousands, or even millions of multi-protocol connections across all plugins from a single message queue. 

We are already using this patch for AMQP-0.9.1 connections on our custom rabbit forks, and thought we'd forward upstream (but uptake is not guaranteed). Then regarding https://www.erlang.org/doc/man/gen_event#send_request-3 - its not a code quality question - it wont work, as we still want synchronous guarantee between the short-lived proxy spawned process and the response from the `register` request from rabbit-alarm, while non-blocking the reader process. If a simple test with 100 concurrent connections illustrating message queue build up on rabbit-alarm to do some basic preprocessing and `dict:store/3` (Erlang isn't that slow btw), then thats as far as we can go with illustrating this problem as unpaid open source work, amidst the other important deliverables we have. On our side, we simply cant afford to have such blocking components which deviate from concurrent design patterns on our deployments (due to frequent node restarts while SLAs for fast reconnects). Thanks though :) 👍

**Comment by michaelklishin** [comment]
@Ayanda-D most users likely do not have those "SLAs for fast reconnects". "My cluster cannot take in 5K connections in a second" is not a complaint we hear about.

There are no objections to the general directions, in fact, some recently revisited protocol implementations already implement some alarms-related bits differently from the original AMQP 0-9-1 `rabbit_reader`.

You get this software for free, it has been the case for almost 17 years now. You also get the right to modify it. You cannot be too upset about your contributions not being accepted with a specific set of recommendations.

**Comment by michaelklishin** [comment]
A quite of what we likely would accept from one of our team members:

> As is I don't think it should be accepted because if I'm not mistaken this means new connections won't be blocked when
> there is an alarm (the block will be delayed until the registration is processed)
> but a PR reworking rabbit_alarm to avoid delaying new connections when there's no need to block (and only then),
> we should accept

A somewhat different implementation would have had a good chance. Now, I don't know if anyone cares enough about this problem to produce it but at least we can publicly share a few key observations from our internal discussion.

**Comment by Ayanda-D** [comment]
> You cannot be too upset about your contributions not being accepted with a specific set of recommendations.

@michaelklishin no, dont get me wrong, i'm not upset at all :) what matters is that the user concerned and their use-case is being handled OK. We thought it a kind gesture to just forward this piece of work upstream as well. Whether its taken up or not is up to you guys to decide. The bigger concern is to see erlang's benefits of concurrency not being followed on some critical parts of rabbit.

Similar to how RPC posed issues with the `rex` server in past (before `erpc`), in case folks didnt now, `gen_event` has long being known to potentially pose very similar node-wide problems if not used with such things as highlighted in this PR in mind (story for another day). The `rabbit_alarm` remains a bottleneck on that code path. I guess we also have high expectations from you folks on best practice on such matters, which are can be pain points on the community end.

But luckily, yes I agree its a blessing that we get the right to modify it however you see fit (those who can) and use it in commercial products and arent tied down to some ways in which things are done which we dont always agree with. As mentioned, patch already in use for AMQP-0.9.1 on end already. So we're OK! :) Thanks! 👍

**Comment by lukebakken** [comment]
> I guess we also have high expectations from you folks on best practice on such matters,

Yes, and in this case, the best practice is to not accept a complex PR without more analysis.

**Comment by Ayanda-D** [comment]
hi @lukebakken 

> Yes, and in this case, the best practice is to not accept a complex PR without more analysis.

Ok 👍 

Regarding the test, observer likely wont show the blocking effect we're concerned about. Its only for a short moment, on connection establishment when we see the spike(s).

I added logging to the `rabbit_alarm:register/2` call here https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_reader.erl#L1232 :

```
    {message_queue_len, L} = erlang:process_info(whereis(rabbit_alarm), message_queue_len),
    Alarms = rabbit_alarm:register(self(), {?MODULE, conserve_resources, []}),
    rabbit_log:info(">>>> RABBIT ALARM MESSAGE QUEUE LENGTH: ~tp", [L]),
```

and `gmake run-broker`.

Clone and build https://github.com/pma/amqp.git and start interactive shell, and spawn connections:
```
user@host amqp % iex -S mix
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.15.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
nil
iex(2)> for _ <- 0..150, do: spawn( fn -> AMQP.Connection.open() end )
```

Check the rabbit log file. I see a few of these:

```
2024-01-12 11:35:50.849847+02:00 [info] <0.6607.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 3
2024-01-12 11:35:50.849851+02:00 [info] <0.6796.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 2
2024-01-12 11:35:50.849927+02:00 [info] <0.6649.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 4
2024-01-12 11:35:50.849793+02:00 [info] <0.6520.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 5
2024-01-12 11:35:50.849862+02:00 [info] <0.6739.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 11
2024-01-12 11:35:50.849938+02:00 [info] <0.6721.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 4
2024-01-12 11:35:50.849673+02:00 [info] <0.6580.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 2
2024-01-12 11:35:50.849879+02:00 [info] <0.6718.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 1
2024-01-12 11:35:50.849888+02:00 [info] <0.6793.0> >>>> RABBIT ALARM MESSAGE QUEUE LENGTH: 2
```

Message queue build up to 11, for only 150 connections. What more 100k, 1million. etc. I agree `rabbit_alarm` may still be optimized for fast processing, but message queue piling up is still inevitable (thats typical OTP gen-server/event code and message queuing in `proc_lib` which we cant avoid). 

I also understand concerns on alarmed nodes etc. however, alarms are sent back to the connection/reader process async via message passing only a few milliseconds after (& only for AMQP-0.9.1 & 1.0 connections. Other protocols ignore the [initial alarmed state](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_mqtt/src/rabbit_mqtt_reader.erl#L81) on connection establishment).

**Pull request closed without merging**
