### PR TITLE
Make slaves wait timeout configurable instead of hardcoded 15000

### PR DESCRIPTION
**Pull request by lemenkov**
This slightly improves rabbitmq/rabbitmq-server#584

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you. Did you mean this to go into `3.6.x`? (we can cherry-pick, since it's a single commit)

**Comment by lemenkov** [comment]
@michaelklishin yes, I believe this should be applied to 3.6.x.

**Comment by michaelklishin** [comment]
@lemenkov OK, I will cherry-pick, no need to re-submit. Thank you.

**Comment by michaelklishin** [comment]
@lemenkov also, what lead you to making the change? Is 15s not high enough for your case? Should we bump the default somewhat?

**Comment by lemenkov** [comment]
Nope, nothing in particular. We just feel uncomfortable w/o ability to change that setting fast enough. Frankly speaking, "15 seconds" sounds too arbitrary, so we're certain there will be situations when we have to change it.

**Comment by michaelklishin** [comment]
Amended the PR a bit, cherry-picked both commits to `stable`. Thank you, @lemenkov!

**Pull request merged**
