### PR TITLE
Disable +deterministic in compilation_mode dbg under bazel

### PR DESCRIPTION
**Pull request by pjk25**
This allows compiling and reloading code from the erlang shell when running the broker with `bazel run -c dbg broker`

### CODE REVIEW

**Comment by lukebakken** [comment]
I'm going to test building RabbitMQ with Bazel on Windows, and then test this out. I hope it works because building RMQ on Windows using msys2 is sloooow.

**Comment by pjk25** [comment]
I've not tried with Windows at all yet. This could be interesting. Let me know what you find @lukebakken.

**Review by mkuratczyk — APPROVED** [review]
Works for me. Thanks!

**Comment by pjk25** [comment]
@mergifyio backport v3.9.x

**Pull request merged**
